import { hidden, test, type CategoryBank } from "./types.js";

export const props: CategoryBank = {
  category: "Props",
  level: 3,
  type: "COMPONENT",
  prerequisites: ["JSX", "Components"],
  problems: [
    {
      slug: "pass-a-prop",
      title: "Display a Name Prop",
      difficulty: "BEGINNER",
      tags: ["props"],
      estimatedMinutes: 5,
      description:
        "Props are how a parent passes data into a component. They arrive as a single object argument.\n\nMake `Greeting` accept a `name` prop and render `<p>Hello, {name}!</p>`. For example, `<Greeting name=\"Sam\" />` renders `Hello, Sam!`.",
      requirements: ["Accepts a 'name' prop", "Renders 'Hello, <name>!'"],
      hints: [
        "Props arrive as the first argument of your component function.",
        "Destructure it: function Greeting({ name }: GreetingProps) { ... }",
      ],
      starterCode: `interface GreetingProps {\n  name: string;\n}\n\nfunction Greeting(props: GreetingProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Greeting;\n`,
      solutionCode: `interface GreetingProps {\n  name: string;\n}\n\nfunction Greeting({ name }: GreetingProps) {\n  return <p>Hello, {name}!</p>;\n}\n\nexport default Greeting;\n`,
      explanation: "Props flow one way, from parent to child, as a plain object. Destructuring in the parameter list pulls out the values you need.",
      commonMistakes: ["Writing `function Greeting(name)` — the argument is the whole props object, so you'd render [object Object]."],
      tests: [
        test("renders the passed name", `renderComponent({ name: "Sam" });\nexpectText("Hello, Sam!");`),
        hidden("works with a different name", `renderComponent({ name: "Priya" });\nexpectText("Hello, Priya!");`),
      ],
      wrongSolutions: [`function Greeting() {\n  return <p>Hello, Sam!</p>;\n}\n\nexport default Greeting;\n`],
    },
    {
      slug: "props-number",
      title: "Display a Number Prop",
      difficulty: "BEGINNER",
      tags: ["props"],
      estimatedMinutes: 3,
      description: "Make `AgeDisplay` accept an `age` prop (a number) and render `<p>Age: {age}</p>`.\n\nParents pass numbers with braces: `<AgeDisplay age={25} />`.",
      requirements: ["Renders 'Age: <age>'"],
      hints: ["Destructure `age` from props.", "Numbers render as text just like strings."],
      starterCode: `interface AgeDisplayProps {\n  age: number;\n}\n\nfunction AgeDisplay(props: AgeDisplayProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default AgeDisplay;\n`,
      solutionCode: `interface AgeDisplayProps {\n  age: number;\n}\n\nfunction AgeDisplay({ age }: AgeDisplayProps) {\n  return <p>Age: {age}</p>;\n}\n\nexport default AgeDisplay;\n`,
      explanation: "Any JavaScript value can be a prop. Strings can use quotes (name=\"Sam\"); everything else uses braces (age={25}).",
      tests: [
        test("renders the age", `renderComponent({ age: 25 });\nexpectText("Age: 25");`),
        hidden("renders a different age", `renderComponent({ age: 7 });\nexpectText("Age: 7");`),
      ],
      wrongSolutions: [`function AgeDisplay() {\n  return <p>Age: 25</p>;\n}\n\nexport default AgeDisplay;\n`],
    },
    {
      slug: "props-multiple",
      title: "Display Multiple Props",
      difficulty: "BEGINNER",
      tags: ["props"],
      estimatedMinutes: 5,
      description:
        "Make `Book` accept `title`, `author`, and `year`, and render:\n\n- `<h3>{title}</h3>`\n- `<p>by {author} ({year})</p>`\n\nExample: `by Frank Herbert (1965)`.",
      requirements: ["Renders the title in an h3", "Renders 'by <author> (<year>)'"],
      hints: ["Destructure several props at once: ({ title, author, year })", "Mix text and expressions freely inside the <p>."],
      starterCode: `interface BookProps {\n  title: string;\n  author: string;\n  year: number;\n}\n\nfunction Book(props: BookProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Book;\n`,
      solutionCode: `interface BookProps {\n  title: string;\n  author: string;\n  year: number;\n}\n\nfunction Book({ title, author, year }: BookProps) {\n  return (\n    <div>\n      <h3>{title}</h3>\n      <p>\n        by {author} ({year})\n      </p>\n    </div>\n  );\n}\n\nexport default Book;\n`,
      explanation: "A component can take as many props as it needs. A TypeScript interface documents exactly which ones those are.",
      tests: [
        test("renders the book", `renderComponent({ title: "Dune", author: "Frank Herbert", year: 1965 });\nscreen.getByRole("heading", { name: "Dune" });\nexpectText("by Frank Herbert (1965)");`),
        hidden("renders a different book", `renderComponent({ title: "Emma", author: "Jane Austen", year: 1815 });\nscreen.getByRole("heading", { level: 3, name: "Emma" });\nexpectText("by Jane Austen (1815)");`),
      ],
    },
    {
      slug: "user-profile",
      title: "Render a User Profile From Props",
      difficulty: "BEGINNER",
      tags: ["props"],
      estimatedMinutes: 5,
      description: "Make `UserProfile` accept `name` and `role` props. Render the name in an `<h2>` and the role in a `<p>` below it.",
      requirements: ["Renders the name in an h2", "Renders the role"],
      hints: ["You can destructure multiple props at once.", "Return a <div> containing the <h2> and the <p>."],
      starterCode: `interface UserProfileProps {\n  name: string;\n  role: string;\n}\n\nfunction UserProfile(props: UserProfileProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default UserProfile;\n`,
      solutionCode: `interface UserProfileProps {\n  name: string;\n  role: string;\n}\n\nfunction UserProfile({ name, role }: UserProfileProps) {\n  return (\n    <div>\n      <h2>{name}</h2>\n      <p>{role}</p>\n    </div>\n  );\n}\n\nexport default UserProfile;\n`,
      explanation: "Each prop is just a value passed down. Render as many of them as you need.",
      tests: [
        test("renders name and role", `renderComponent({ name: "Ada Lovelace", role: "Engineer" });\nscreen.getByRole("heading", { level: 2, name: "Ada Lovelace" });\nexpectText("Engineer");`),
        hidden("renders different props", `renderComponent({ name: "Grace Hopper", role: "Admiral" });\nscreen.getByRole("heading", { level: 2, name: "Grace Hopper" });\nexpectText("Admiral");`),
      ],
      wrongSolutions: [`function UserProfile() {\n  return (<div><h2>Ada Lovelace</h2><p>Engineer</p></div>);\n}\n\nexport default UserProfile;\n`],
    },
    {
      slug: "props-object",
      title: "Pass an Object as a Prop",
      difficulty: "BEGINNER",
      tags: ["props", "objects"],
      estimatedMinutes: 8,
      description:
        "Make `ProductCard` accept a single `product` prop shaped like `{ name: string; price: number }`.\n\nRender the name in an `<h3>` and the price with two decimals, e.g. a price of `5` → `<p>$5.00</p>`.",
      requirements: ["Renders product.name in an h3", "Renders the price as $X.XX"],
      hints: ["Access nested values with product.name and product.price.", "number.toFixed(2) formats to two decimal places."],
      starterCode: `interface Product {\n  name: string;\n  price: number;\n}\n\ninterface ProductCardProps {\n  product: Product;\n}\n\nfunction ProductCard(props: ProductCardProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default ProductCard;\n`,
      solutionCode: `interface Product {\n  name: string;\n  price: number;\n}\n\ninterface ProductCardProps {\n  product: Product;\n}\n\nfunction ProductCard({ product }: ProductCardProps) {\n  return (\n    <div>\n      <h3>{product.name}</h3>\n      <p>\${product.price.toFixed(2)}</p>\n    </div>\n  );\n}\n\nexport default ProductCard;\n`,
      explanation: "Passing one object keeps related data together. In JSX, `$` followed by `{...}` is plain text then an expression — not a template literal.",
      commonMistakes: ["Rendering {product} directly throws: objects are not valid as a React child."],
      tests: [
        test("renders the product", `renderComponent({ product: { name: "Coffee", price: 5 } });\nscreen.getByRole("heading", { name: "Coffee" });\nexpectText("$5.00");`),
        hidden("formats other prices", `renderComponent({ product: { name: "Tea Set", price: 24.5 } });\nscreen.getByRole("heading", { name: "Tea Set" });\nexpectText("$24.50");`),
      ],
      wrongSolutions: [`function ProductCard({ product }) {\n  return (<div><h3>{product.name}</h3><p>\${product.price}</p></div>);\n}\n\nexport default ProductCard;\n`],
    },
    {
      slug: "props-array-join",
      title: "Pass an Array as a Prop",
      difficulty: "BEGINNER",
      tags: ["props", "arrays"],
      estimatedMinutes: 5,
      description:
        "Make `TagSummary` accept a `tags` prop (an array of strings) and render them as one comma-separated sentence:\n\n`[\"react\", \"hooks\"]` → `<p>Tags: react, hooks</p>`",
      requirements: ["Renders 'Tags: ' followed by the tags joined with ', '"],
      hints: ["Arrays have a join method.", "tags.join(\", \")"],
      starterCode: `interface TagSummaryProps {\n  tags: string[];\n}\n\nfunction TagSummary(props: TagSummaryProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default TagSummary;\n`,
      solutionCode: `interface TagSummaryProps {\n  tags: string[];\n}\n\nfunction TagSummary({ tags }: TagSummaryProps) {\n  return <p>Tags: {tags.join(", ")}</p>;\n}\n\nexport default TagSummary;\n`,
      explanation: "Rendering an array of strings directly glues them together ('reacthooks'). join() turns it into one formatted string first.",
      tests: [
        test("joins the tags", `renderComponent({ tags: ["react", "hooks"] });\nexpectText("Tags: react, hooks");`),
        hidden("works with three tags", `renderComponent({ tags: ["css", "html", "js"] });\nexpectText("Tags: css, html, js");`),
      ],
      wrongSolutions: [`function TagSummary({ tags }) {\n  return <p>Tags: {tags}</p>;\n}\n\nexport default TagSummary;\n`],
    },
    {
      slug: "props-boolean",
      title: "Boolean Props",
      difficulty: "BEGINNER",
      tags: ["props"],
      estimatedMinutes: 5,
      description:
        "Make `SubmitButton` accept `label` (string) and `disabled` (boolean), and render a button with that label that is disabled when `disabled` is true.",
      requirements: ["Shows the label", "Disabled exactly when the `disabled` prop is true"],
      hints: ["Destructure both props.", "Pass a prop straight through to an attribute: disabled={disabled}"],
      starterCode: `interface SubmitButtonProps {\n  label: string;\n  disabled: boolean;\n}\n\nfunction SubmitButton(props: SubmitButtonProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default SubmitButton;\n`,
      solutionCode: `interface SubmitButtonProps {\n  label: string;\n  disabled: boolean;\n}\n\nfunction SubmitButton({ label, disabled }: SubmitButtonProps) {\n  return <button disabled={disabled}>{label}</button>;\n}\n\nexport default SubmitButton;\n`,
      explanation: "Props can be passed straight through to DOM attributes. The button reflects whatever the parent decides.",
      tests: [
        test("is disabled when disabled is true", `renderComponent({ label: "Save", disabled: true });\nassert(screen.getByRole("button", { name: "Save" }).disabled, "Expected the button to be disabled");`),
        hidden("is enabled when disabled is false", `renderComponent({ label: "Send", disabled: false });\nassert(!screen.getByRole("button", { name: "Send" }).disabled, "Expected the button to be enabled");`),
      ],
      wrongSolutions: [`function SubmitButton({ label }) {\n  return <button disabled>{label}</button>;\n}\n\nexport default SubmitButton;\n`],
    },
    {
      slug: "props-default-value",
      title: "Default Prop Values",
      difficulty: "BEGINNER",
      tags: ["props", "default-props"],
      estimatedMinutes: 5,
      description:
        "Make `Welcome` accept an optional `name` prop. Render `<p>Welcome, {name}!</p>`, but when no name is passed, use `Guest`.",
      requirements: ["Renders the given name", "Falls back to 'Guest' when name is missing"],
      hints: ["Destructuring supports default values.", "function Welcome({ name = \"Guest\" }: WelcomeProps)"],
      starterCode: `interface WelcomeProps {\n  name?: string;\n}\n\nfunction Welcome(props: WelcomeProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Welcome;\n`,
      solutionCode: `interface WelcomeProps {\n  name?: string;\n}\n\nfunction Welcome({ name = "Guest" }: WelcomeProps) {\n  return <p>Welcome, {name}!</p>;\n}\n\nexport default Welcome;\n`,
      explanation: "Destructuring defaults apply when a prop is `undefined`, which is what you get when the parent doesn't pass it. This replaced the old `defaultProps` API.",
      commonMistakes: ["Using `name || \"Guest\"` also replaces an empty string — usually fine, but it's a different rule than a default."],
      tests: [
        test("uses Guest when no name is passed", `renderComponent({});\nexpectText("Welcome, Guest!");`),
        hidden("uses the name when passed", `renderComponent({ name: "Kai" });\nexpectText("Welcome, Kai!");`),
      ],
      wrongSolutions: [`function Welcome({ name }) {\n  return <p>Welcome, {name}!</p>;\n}\n\nexport default Welcome;\n`, `function Welcome() {\n  return <p>Welcome, Guest!</p>;\n}\n\nexport default Welcome;\n`],
    },
    {
      slug: "props-optional",
      title: "Optional Props",
      difficulty: "BEGINNER",
      tags: ["props", "conditional-rendering"],
      estimatedMinutes: 8,
      description:
        "Make `Profile` accept a required `name` and an optional `bio`. Always render the name in an `<h2>`. Render `<p>{bio}</p>` **only** when a bio was given.",
      requirements: ["Always renders the name", "Renders the bio paragraph only when bio is provided"],
      hints: ["`bio?: string` means bio may be undefined.", "{bio && <p>{bio}</p>} renders nothing when bio is undefined."],
      starterCode: `interface ProfileProps {\n  name: string;\n  bio?: string;\n}\n\nfunction Profile(props: ProfileProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Profile;\n`,
      solutionCode: `interface ProfileProps {\n  name: string;\n  bio?: string;\n}\n\nfunction Profile({ name, bio }: ProfileProps) {\n  return (\n    <div>\n      <h2>{name}</h2>\n      {bio && <p>{bio}</p>}\n    </div>\n  );\n}\n\nexport default Profile;\n`,
      explanation: "Optional props are just undefined when omitted. `&&` renders the right-hand side only when the left is truthy.",
      tests: [
        test("renders name and bio", `renderComponent({ name: "Lin", bio: "Loves hiking." });\nscreen.getByRole("heading", { name: "Lin" });\nexpectText("Loves hiking.");`),
        hidden("renders no empty paragraph without a bio", `const { container } = renderComponent({ name: "Lin" });\nscreen.getByRole("heading", { name: "Lin" });\nassertEqual(container.querySelectorAll("p").length, 0, "No <p> should render when bio is missing");`),
      ],
      wrongSolutions: [`function Profile({ name, bio }) {\n  return (<div><h2>{name}</h2><p>{bio}</p></div>);\n}\n\nexport default Profile;\n`],
    },
    {
      slug: "props-computed",
      title: "Compute a Value From Props",
      difficulty: "BEGINNER",
      tags: ["props", "expressions"],
      estimatedMinutes: 5,
      description: "Make `Rectangle` accept `width` and `height` and render `<p>Area: {width × height}</p>`. For example 5 and 10 → `Area: 50`.",
      requirements: ["Renders the area computed from the props"],
      hints: ["You can compute values in the function body before returning.", "const area = width * height;"],
      starterCode: `interface RectangleProps {\n  width: number;\n  height: number;\n}\n\nfunction Rectangle(props: RectangleProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Rectangle;\n`,
      solutionCode: `interface RectangleProps {\n  width: number;\n  height: number;\n}\n\nfunction Rectangle({ width, height }: RectangleProps) {\n  const area = width * height;\n  return <p>Area: {area}</p>;\n}\n\nexport default Rectangle;\n`,
      explanation: "Values derived from props are recalculated on every render, so they can never go stale. No need to store them anywhere.",
      tests: [
        test("computes the area", `renderComponent({ width: 5, height: 10 });\nexpectText("Area: 50");`),
        hidden("computes other areas", `renderComponent({ width: 3, height: 7 });\nexpectText("Area: 21");`),
      ],
      wrongSolutions: [`function Rectangle() {\n  return <p>Area: 50</p>;\n}\n\nexport default Rectangle;\n`],
    },
    {
      slug: "props-style",
      title: "Style a Button From Props",
      difficulty: "BEGINNER",
      tags: ["props", "styling"],
      estimatedMinutes: 5,
      description: "Make `ColorButton` accept `label` and `color`. Render a button showing `label` whose background colour is `color`.",
      requirements: ["Shows the label", "Background colour comes from the color prop"],
      hints: ["The style prop takes an object.", "style={{ backgroundColor: color }}"],
      starterCode: `interface ColorButtonProps {\n  label: string;\n  color: string;\n}\n\nfunction ColorButton(props: ColorButtonProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default ColorButton;\n`,
      solutionCode: `interface ColorButtonProps {\n  label: string;\n  color: string;\n}\n\nfunction ColorButton({ label, color }: ColorButtonProps) {\n  return <button style={{ backgroundColor: color }}>{label}</button>;\n}\n\nexport default ColorButton;\n`,
      explanation: "Style objects can mix fixed values and props, so one component can render many variations.",
      tests: [
        test("uses the color prop", `renderComponent({ label: "Buy", color: "green" });\nassertEqual(screen.getByRole("button", { name: "Buy" }).style.backgroundColor, "green");`),
        hidden("works with another color", `renderComponent({ label: "Delete", color: "red" });\nassertEqual(screen.getByRole("button", { name: "Delete" }).style.backgroundColor, "red");`),
      ],
      wrongSolutions: [`function ColorButton({ label }) {\n  return <button style={{ backgroundColor: "green" }}>{label}</button>;\n}\n\nexport default ColorButton;\n`],
    },
    {
      slug: "props-classname-variant",
      title: "Choose a CSS Class From a Prop",
      difficulty: "BEGINNER",
      tags: ["props", "styling"],
      estimatedMinutes: 8,
      description:
        "Make `Alert` accept `type` (`\"info\" | \"success\" | \"error\"`) and `message`. Render a `<div role=\"alert\">` showing the message, with the class names `alert alert-{type}` — e.g. `alert alert-error`.",
      requirements: ["role='alert' with the message", "className is 'alert alert-<type>'"],
      hints: ["Build the class string from the prop.", "className={\"alert alert-\" + type} or a template literal."],
      starterCode: `interface AlertProps {\n  type: "info" | "success" | "error";\n  message: string;\n}\n\nfunction Alert(props: AlertProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Alert;\n`,
      solutionCode: `interface AlertProps {\n  type: "info" | "success" | "error";\n  message: string;\n}\n\nfunction Alert({ type, message }: AlertProps) {\n  return (\n    <div role="alert" className={\`alert alert-\${type}\`}>\n      {message}\n    </div>\n  );\n}\n\nexport default Alert;\n`,
      explanation: "A union type like \"info\" | \"success\" | \"error\" documents (and type-checks) exactly which variants exist.",
      tests: [
        test("renders an error alert", `renderComponent({ type: "error", message: "Payment failed" });\nconst alert = screen.getByRole("alert");\nassertEqual(alert.textContent, "Payment failed");\nassertEqual(alert.className, "alert alert-error");`),
        hidden("renders a success alert", `renderComponent({ type: "success", message: "Saved" });\nassertEqual(screen.getByRole("alert").className, "alert alert-success");`),
      ],
      wrongSolutions: [`function Alert({ message }) {\n  return <div role="alert" className="alert alert-error">{message}</div>;\n}\n\nexport default Alert;\n`],
    },
    {
      slug: "props-function",
      title: "Function Props",
      difficulty: "EASY",
      tags: ["props", "events", "callbacks"],
      type: "COMPONENT",
      estimatedMinutes: 8,
      description:
        "Props can be functions too. Make `ActionButton` accept `label` and `onClick`, and render a button that calls `onClick` when clicked.",
      requirements: ["Shows the label", "Calls the onClick prop once per click"],
      hints: ["Pass the function to the button: onClick={onClick}", "Pass the function itself — don't call it with ()."],
      starterCode: `interface ActionButtonProps {\n  label: string;\n  onClick: () => void;\n}\n\nfunction ActionButton(props: ActionButtonProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default ActionButton;\n`,
      solutionCode: `interface ActionButtonProps {\n  label: string;\n  onClick: () => void;\n}\n\nfunction ActionButton({ label, onClick }: ActionButtonProps) {\n  return <button onClick={onClick}>{label}</button>;\n}\n\nexport default ActionButton;\n`,
      explanation: "Passing functions down lets the parent decide what a click means while the child just reports it. This is how children talk to parents in React.",
      commonMistakes: ["onClick={onClick()} calls the function during render instead of on click."],
      tests: [
        test("calls onClick when clicked", `const onClick = mockFn();\nrenderComponent({ label: "Delete", onClick });\nfireEvent.click(screen.getByRole("button", { name: "Delete" }));\nassertEqual(onClick.calls.length, 1, "onClick should be called once per click");`),
        hidden("does not call onClick during render", `const onClick = mockFn();\nrenderComponent({ label: "Delete", onClick });\nassertEqual(onClick.calls.length, 0, "onClick was called before any click — did you write onClick={onClick()}?");\nfireEvent.click(screen.getByRole("button"));\nfireEvent.click(screen.getByRole("button"));\nassertEqual(onClick.calls.length, 2);`),
      ],
      wrongSolutions: [`function ActionButton({ label }) {\n  return <button>{label}</button>;\n}\n\nexport default ActionButton;\n`],
    },
    {
      slug: "props-callback-argument",
      title: "Pass a Value Back Through a Callback",
      difficulty: "EASY",
      tags: ["props", "events", "callbacks"],
      estimatedMinutes: 8,
      description:
        "Make `VoteButtons` accept an `onVote` prop with type `(choice: \"yes\" | \"no\") => void`. Render two buttons, `Yes` and `No`. Clicking `Yes` calls `onVote(\"yes\")`; clicking `No` calls `onVote(\"no\")`.",
      requirements: ["Two buttons, Yes and No", "Each calls onVote with its own value"],
      hints: ["Wrap the call in an arrow function so you can pass an argument.", "onClick={() => onVote(\"yes\")}"],
      starterCode: `interface VoteButtonsProps {\n  onVote: (choice: "yes" | "no") => void;\n}\n\nfunction VoteButtons(props: VoteButtonsProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default VoteButtons;\n`,
      solutionCode: `interface VoteButtonsProps {\n  onVote: (choice: "yes" | "no") => void;\n}\n\nfunction VoteButtons({ onVote }: VoteButtonsProps) {\n  return (\n    <div>\n      <button onClick={() => onVote("yes")}>Yes</button>\n      <button onClick={() => onVote("no")}>No</button>\n    </div>\n  );\n}\n\nexport default VoteButtons;\n`,
      explanation: "An inline arrow function creates a handler that calls onVote with a specific argument when the click happens.",
      commonMistakes: ["onClick={onVote(\"yes\")} — this calls onVote immediately while rendering."],
      tests: [
        test("Yes calls onVote('yes')", `const onVote = mockFn();\nrenderComponent({ onVote });\nfireEvent.click(screen.getByRole("button", { name: "Yes" }));\nassertEqual(onVote.calls, [["yes"]]);`),
        hidden("No calls onVote('no') and nothing fires on render", `const onVote = mockFn();\nrenderComponent({ onVote });\nassertEqual(onVote.calls.length, 0);\nfireEvent.click(screen.getByRole("button", { name: "No" }));\nassertEqual(onVote.calls, [["no"]]);`),
      ],
      wrongSolutions: [`function VoteButtons({ onVote }) {\n  return (<div><button onClick={() => onVote("yes")}>Yes</button><button onClick={() => onVote("yes")}>No</button></div>);\n}\n\nexport default VoteButtons;\n`],
    },
    {
      slug: "props-spread-rest",
      title: "Forward the Rest of the Props",
      difficulty: "EASY",
      tags: ["props", "spread", "forms"],
      estimatedMinutes: 10,
      description:
        "Make `TextField` accept a `label` plus **any** other input attributes (`placeholder`, `type`, `name`, ...). Render:\n\n```\n<label>\n  {label}\n  <input {...everythingElse} />\n</label>\n```\n\nUse rest syntax to collect the other props and spread them onto the `<input>`.",
      requirements: ["The label text labels the input", "All other props are forwarded to the <input>"],
      hints: ["Rest destructuring: ({ label, ...rest })", "Spread onto the element: <input {...rest} />"],
      starterCode: `import type { InputHTMLAttributes } from "react";\n\ninterface TextFieldProps extends InputHTMLAttributes<HTMLInputElement> {\n  label: string;\n}\n\nfunction TextField(props: TextFieldProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default TextField;\n`,
      solutionCode: `import type { InputHTMLAttributes } from "react";\n\ninterface TextFieldProps extends InputHTMLAttributes<HTMLInputElement> {\n  label: string;\n}\n\nfunction TextField({ label, ...rest }: TextFieldProps) {\n  return (\n    <label>\n      {label}\n      <input {...rest} />\n    </label>\n  );\n}\n\nexport default TextField;\n`,
      explanation: "Rest/spread lets a wrapper component accept every attribute the underlying element supports without listing them one by one.",
      tests: [
        test("forwards placeholder", `renderComponent({ label: "City", placeholder: "e.g. Berlin" });\nassertEqual(screen.getByLabelText("City").getAttribute("placeholder"), "e.g. Berlin");`),
        hidden("forwards any attribute", `renderComponent({ label: "Email", type: "email", name: "email", required: true });\nconst input = screen.getByLabelText("Email");\nassertEqual(input.getAttribute("type"), "email");\nassertEqual(input.getAttribute("name"), "email");\nassert(input.required, "required should be forwarded");`),
      ],
      wrongSolutions: [`function TextField({ label, placeholder }) {\n  return (<label>{label}<input placeholder={placeholder} /></label>);\n}\n\nexport default TextField;\n`],
    },
    {
      slug: "props-lookup-object",
      title: "Map a Prop to a Label",
      difficulty: "EASY",
      tags: ["props", "objects"],
      estimatedMinutes: 8,
      description:
        "Make `StatusBadge` accept `status`: `\"online\" | \"away\" | \"offline\"`, and render a `<span>` with the matching label:\n\n| status | label |\n|---|---|\n| online | 🟢 Online |\n| away | 🟡 Away |\n| offline | ⚪ Offline |\n\nUse a lookup object instead of a chain of if statements.",
      requirements: ["Renders the right label for each status"],
      hints: ["Define const LABELS = { online: \"...\", ... } outside the component.", "Then render LABELS[status]."],
      starterCode: `type Status = "online" | "away" | "offline";\n\ninterface StatusBadgeProps {\n  status: Status;\n}\n\nfunction StatusBadge(props: StatusBadgeProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default StatusBadge;\n`,
      solutionCode: `type Status = "online" | "away" | "offline";\n\nconst LABELS: Record<Status, string> = {\n  online: "🟢 Online",\n  away: "🟡 Away",\n  offline: "⚪ Offline",\n};\n\ninterface StatusBadgeProps {\n  status: Status;\n}\n\nfunction StatusBadge({ status }: StatusBadgeProps) {\n  return <span>{LABELS[status]}</span>;\n}\n\nexport default StatusBadge;\n`,
      explanation: "A lookup object maps each possible value to its output in one place. Adding a status means adding one line, and `Record<Status, string>` makes TypeScript check you covered every case.",
      tests: [
        test("renders online", `renderComponent({ status: "online" });\nexpectText("🟢 Online");`),
        hidden("renders away and offline", `const { rerender } = renderComponent({ status: "away" });\nexpectText("🟡 Away");\nrerender(<Component status="offline" />);\nexpectText("⚪ Offline");`),
      ],
      wrongSolutions: [`function StatusBadge({ status }) {\n  return <span>{status === "online" ? "🟢 Online" : "⚪ Offline"}</span>;\n}\n\nexport default StatusBadge;\n`],
    },
    {
      slug: "props-discount-price",
      title: "Show a Discounted Price",
      difficulty: "EASY",
      tags: ["props", "conditional-rendering"],
      estimatedMinutes: 10,
      description:
        "Make `Price` accept `price` and `discountPercent`.\n\n- With a discount: render the original price in `<s>` (strikethrough) and the discounted price in `<strong>`, both with two decimals. `price=100, discountPercent=20` → `<s>$100.00</s> <strong>$80.00</strong>`.\n- With `discountPercent` of `0`: render only `<strong>$100.00</strong>` — no `<s>` element.",
      requirements: ["Discounted price is computed correctly", "Original price shown struck through only when discounted"],
      hints: ["final = price * (1 - discountPercent / 100)", "Render the <s> conditionally: {discountPercent > 0 && <s>...</s>}"],
      starterCode: `interface PriceProps {\n  price: number;\n  discountPercent: number;\n}\n\nfunction Price(props: PriceProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Price;\n`,
      solutionCode: `interface PriceProps {\n  price: number;\n  discountPercent: number;\n}\n\nfunction Price({ price, discountPercent }: PriceProps) {\n  const finalPrice = price * (1 - discountPercent / 100);\n  return (\n    <p>\n      {discountPercent > 0 && <s>\${price.toFixed(2)}</s>} <strong>\${finalPrice.toFixed(2)}</strong>\n    </p>\n  );\n}\n\nexport default Price;\n`,
      explanation: "Derived values (the final price) are computed during render, and conditional rendering decides whether the original price appears at all.",
      commonMistakes: ["`{discountPercent && <s>...}` renders a literal 0 when the discount is 0."],
      tests: [
        test("shows the discounted price", `const { container } = renderComponent({ price: 100, discountPercent: 20 });\nassertEqual(container.querySelector("strong")?.textContent, "$80.00");\nassertEqual(container.querySelector("s")?.textContent, "$100.00");`),
        hidden("no strikethrough and no stray 0 without a discount", `const { container } = renderComponent({ price: 40, discountPercent: 0 });\nassertEqual(container.querySelector("strong")?.textContent, "$40.00");\nassert(!container.querySelector("s"), "No <s> should render without a discount");\nassertEqual(container.textContent.trim(), "$40.00");`),
      ],
      wrongSolutions: [`function Price({ price, discountPercent }) {\n  const finalPrice = price * (1 - discountPercent / 100);\n  return (<p>{discountPercent && <s>\${price.toFixed(2)}</s>} <strong>\${finalPrice.toFixed(2)}</strong></p>);\n}\n\nexport default Price;\n`],
    },
    {
      slug: "props-drilling",
      title: "Pass Props Down Two Levels",
      difficulty: "EASY",
      tags: ["props", "composition"],
      estimatedMinutes: 10,
      description:
        "Data often passes through several components. Complete the three components:\n\n- `Avatar({ name, url })` → an `<img>` with `src` = url and alt text `<name>'s avatar` (e.g. `Noor's avatar`)\n- `ProfileCard({ user })` → an `<h2>` with `user.name`, then an `Avatar` with the user's name and avatarUrl\n- `App` (default) → `<ProfileCard user={user} />` using the provided `user` object\n\nExport `Avatar` and `ProfileCard`.",
      requirements: ["Avatar renders an image with the right src and alt", "ProfileCard passes data down to Avatar", "App renders the profile for the given user"],
      hints: ["ProfileCard receives `user` and passes `user.name` and `user.avatarUrl` on to Avatar.", "<Avatar name={user.name} url={user.avatarUrl} />"],
      starterCode: `interface User {\n  name: string;\n  avatarUrl: string;\n}\n\nexport function Avatar(props: { name: string; url: string }) {\n  return null;\n}\n\nexport function ProfileCard(props: { user: User }) {\n  return null;\n}\n\nfunction App() {\n  const user: User = { name: "Noor", avatarUrl: "/noor.png" };\n  return null;\n}\n\nexport default App;\n`,
      solutionCode: `interface User {\n  name: string;\n  avatarUrl: string;\n}\n\nexport function Avatar({ name, url }: { name: string; url: string }) {\n  return <img src={url} alt={\`\${name}'s avatar\`} />;\n}\n\nexport function ProfileCard({ user }: { user: User }) {\n  return (\n    <div>\n      <h2>{user.name}</h2>\n      <Avatar name={user.name} url={user.avatarUrl} />\n    </div>\n  );\n}\n\nfunction App() {\n  const user: User = { name: "Noor", avatarUrl: "/noor.png" };\n  return <ProfileCard user={user} />;\n}\n\nexport default App;\n`,
      explanation: "Each component only receives what it needs: ProfileCard gets the whole user, Avatar just a name and a URL. Passing data through several layers is called 'prop drilling'. Context solves it when the chain gets long.",
      tests: [
        test("App renders the profile", `renderComponent();\nscreen.getByRole("heading", { name: "Noor" });\nassertEqual(screen.getByRole("img", { name: "Noor's avatar" }).getAttribute("src"), "/noor.png");`),
        hidden("ProfileCard works with any user", `render(<userExports.ProfileCard user={{ name: "Tomas", avatarUrl: "/t.png" }} />);\nscreen.getByRole("heading", { name: "Tomas" });\nassertEqual(screen.getByRole("img", { name: "Tomas's avatar" }).getAttribute("src"), "/t.png");`),
      ],
      wrongSolutions: [`export function Avatar() { return <img src="/noor.png" alt="Noor's avatar" />; }\nexport function ProfileCard({ user }) { return (<div><h2>{user.name}</h2><Avatar /></div>); }\nfunction App() { return <ProfileCard user={{ name: "Noor", avatarUrl: "/noor.png" }} />; }\nexport default App;\n`],
    },
    {
      slug: "props-button-api",
      title: "Design a Reusable Button API",
      difficulty: "EASY",
      tags: ["props", "default-props", "reusable-components"],
      estimatedMinutes: 12,
      description:
        "Build a reusable `Button` with this API:\n\n| prop | type | default |\n|---|---|---|\n| `label` | string | — |\n| `variant` | `\"primary\" \\| \"secondary\" \\| \"danger\"` | `\"primary\"` |\n| `size` | `\"sm\" \\| \"md\" \\| \"lg\"` | `\"md\"` |\n| `onClick` | `() => void` | optional |\n\nRender a `<button type=\"button\">` with `className` `btn btn-{variant} btn-{size}`.",
      requirements: ["Defaults to primary / md", "className reflects variant and size", "type='button'", "Calls onClick when clicked"],
      hints: ["Use destructuring defaults for variant and size.", "type=\"button\" stops the button from submitting a surrounding form."],
      starterCode: `interface ButtonProps {\n  label: string;\n  variant?: "primary" | "secondary" | "danger";\n  size?: "sm" | "md" | "lg";\n  onClick?: () => void;\n}\n\nfunction Button(props: ButtonProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Button;\n`,
      solutionCode: `interface ButtonProps {\n  label: string;\n  variant?: "primary" | "secondary" | "danger";\n  size?: "sm" | "md" | "lg";\n  onClick?: () => void;\n}\n\nfunction Button({ label, variant = "primary", size = "md", onClick }: ButtonProps) {\n  return (\n    <button type="button" className={\`btn btn-\${variant} btn-\${size}\`} onClick={onClick}>\n      {label}\n    </button>\n  );\n}\n\nexport default Button;\n`,
      explanation: "A good component API has sensible defaults, a small set of allowed values (union types), and forwards behaviour (onClick) to the underlying element.",
      tests: [
        test("uses defaults", `renderComponent({ label: "Save" });\nconst b = screen.getByRole("button", { name: "Save" });\nassertEqual(b.className, "btn btn-primary btn-md");\nassertEqual(b.getAttribute("type"), "button");`),
        hidden("respects variant, size and onClick", `const onClick = mockFn();\nrenderComponent({ label: "Delete", variant: "danger", size: "lg", onClick });\nconst b = screen.getByRole("button", { name: "Delete" });\nassertEqual(b.className, "btn btn-danger btn-lg");\nfireEvent.click(b);\nassertEqual(onClick.calls.length, 1);`),
      ],
      wrongSolutions: [`function Button({ label, onClick }) {\n  return <button type="button" className="btn btn-primary btn-md" onClick={onClick}>{label}</button>;\n}\n\nexport default Button;\n`],
    },
    {
      slug: "props-never-mutate",
      title: "Fix: Never Mutate Props",
      difficulty: "EASY",
      tags: ["props", "debugging", "immutability"],
      problemType: "DEBUG",
      estimatedMinutes: 8,
      description:
        "`UserTag` should display the user's name in upper case. It looks right on screen, but it has a sneaky bug: it **changes the parent's `user` object**, so the rest of the app now sees `\"ADA\"` everywhere.\n\nFix it so the name is still shown upper-cased, but the `user` prop is never modified.",
      requirements: ["Renders the name in upper case", "Does not modify the `user` object it receives"],
      hints: ["Props are read-only inputs. Treat them like function arguments you must not change.", "Compute a new variable instead: const displayName = user.name.toUpperCase();"],
      starterCode: `interface UserTagProps {\n  user: { name: string };\n}\n\nfunction UserTag({ user }: UserTagProps) {\n  user.name = user.name.toUpperCase();\n  return <span>{user.name}</span>;\n}\n\nexport default UserTag;\n`,
      solutionCode: `interface UserTagProps {\n  user: { name: string };\n}\n\nfunction UserTag({ user }: UserTagProps) {\n  const displayName = user.name.toUpperCase();\n  return <span>{displayName}</span>;\n}\n\nexport default UserTag;\n`,
      explanation: "Components must be pure: given the same props they render the same output and change nothing outside themselves. Mutating a prop changes data the parent owns, which causes bugs far from where they started.",
      tests: [
        test("shows the name in upper case", `renderComponent({ user: { name: "Ada" } });\nexpectText("ADA");`),
        hidden("does not mutate the user prop", `const user = { name: "Grace" };\nrenderComponent({ user });\nexpectText("GRACE");\nassertEqual(user.name, "Grace", "The user object passed in was modified");`),
      ],
    },
  ],
};
