import { hidden, test, type CategoryBank } from "./types.js";

export const children: CategoryBank = {
  category: "Children",
  level: 4,
  type: "COMPONENT",
  prerequisites: ["Components", "Props"],
  problems: [
    {
      slug: "children-render",
      title: "Render Children",
      difficulty: "BEGINNER",
      tags: ["children", "composition"],
      estimatedMinutes: 5,
      description:
        "Whatever you put **between** a component's opening and closing tags arrives as a special prop called `children`.\n\nMake `Card` render `<div className=\"card\">{children}</div>`, so that\n\n```\n<Card><p>Hello</p></Card>\n```\n\nrenders the paragraph inside the card.",
      requirements: ["Renders a div with class 'card'", "Renders whatever children it receives inside it"],
      hints: ["children is just another prop: ({ children })", "Place {children} where the content should go."],
      starterCode: `import type { ReactNode } from "react";\n\ninterface CardProps {\n  children: ReactNode;\n}\n\nfunction Card(props: CardProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Card;\n`,
      solutionCode: `import type { ReactNode } from "react";\n\ninterface CardProps {\n  children: ReactNode;\n}\n\nfunction Card({ children }: CardProps) {\n  return <div className="card">{children}</div>;\n}\n\nexport default Card;\n`,
      explanation: "`children` lets a component wrap content it knows nothing about. That's what makes generic containers like Card, Modal, and Layout possible.",
      tests: [
        test("renders its children inside .card", `const { container } = render(<Component><p>Hello</p></Component>);\nconst card = container.querySelector(".card");\nassert(card, "Expected a .card element");\nwithin(card).getByText("Hello");`),
        hidden("renders any children", `render(<Component><h2>Title</h2><button>Go</button></Component>);\nscreen.getByRole("heading", { name: "Title" });\nscreen.getByRole("button", { name: "Go" });`),
      ],
      wrongSolutions: [`function Card() {\n  return <div className="card"><p>Hello</p></div>;\n}\n\nexport default Card;\n`],
    },
    {
      slug: "children-panel-title",
      title: "Panel With a Title and Children",
      difficulty: "BEGINNER",
      tags: ["children", "props"],
      estimatedMinutes: 5,
      description: "Make `Panel` accept a `title` prop and `children`. Render a `<section>` containing an `<h3>` with the title, followed by the children.",
      requirements: ["Renders the title in an h3", "Renders children after the title"],
      hints: ["children works alongside normal props: ({ title, children })", "<section><h3>{title}</h3>{children}</section>"],
      starterCode: `import type { ReactNode } from "react";\n\ninterface PanelProps {\n  title: string;\n  children: ReactNode;\n}\n\nfunction Panel(props: PanelProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Panel;\n`,
      solutionCode: `import type { ReactNode } from "react";\n\ninterface PanelProps {\n  title: string;\n  children: ReactNode;\n}\n\nfunction Panel({ title, children }: PanelProps) {\n  return (\n    <section>\n      <h3>{title}</h3>\n      {children}\n    </section>\n  );\n}\n\nexport default Panel;\n`,
      explanation: "A component can mix configuration props (title) with free-form content (children).",
      tests: [
        test("renders title and content", `render(<Component title="Settings"><p>Change your preferences.</p></Component>);\nscreen.getByRole("heading", { level: 3, name: "Settings" });\nexpectText("Change your preferences.");`),
        hidden("title comes before children", `const { container } = render(<Component title="Stats"><p>42 users</p></Component>);\nconst section = container.querySelector("section");\nassert(section, "Expected a <section>");\nassertEqual(Array.from(section.children).map((c) => c.tagName), ["H3", "P"]);`),
      ],
    },
    {
      slug: "children-button",
      title: "Button With Children",
      difficulty: "BEGINNER",
      tags: ["children", "events"],
      estimatedMinutes: 5,
      description:
        "Make `Button` render its `children` inside a `<button>` and call `onClick` when clicked. Using children instead of a `label` prop means callers can put icons or formatting inside:\n\n```\n<Button onClick={save}><span>💾</span> Save</Button>\n```",
      requirements: ["Renders children inside a <button>", "Calls onClick when clicked"],
      hints: ["({ children, onClick })", "<button onClick={onClick}>{children}</button>"],
      starterCode: `import type { ReactNode } from "react";\n\ninterface ButtonProps {\n  children: ReactNode;\n  onClick?: () => void;\n}\n\nfunction Button(props: ButtonProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Button;\n`,
      solutionCode: `import type { ReactNode } from "react";\n\ninterface ButtonProps {\n  children: ReactNode;\n  onClick?: () => void;\n}\n\nfunction Button({ children, onClick }: ButtonProps) {\n  return <button onClick={onClick}>{children}</button>;\n}\n\nexport default Button;\n`,
      explanation: "Children make a component's API more flexible than a string prop: callers can pass any JSX.",
      tests: [
        test("renders rich children", `render(<Component><span>💾</span> Save</Component>);\nscreen.getByRole("button", { name: "💾 Save" });`),
        hidden("calls onClick", `const onClick = mockFn();\nrender(<Component onClick={onClick}><b>Go</b></Component>);\nfireEvent.click(screen.getByRole("button", { name: "Go" }));\nassertEqual(onClick.calls.length, 1);`),
      ],
    },
    {
      slug: "children-layout-slots",
      title: "Layout With Named Slots",
      difficulty: "EASY",
      tags: ["children", "composition", "layout"],
      estimatedMinutes: 10,
      description:
        "Sometimes one `children` isn't enough. Make `Layout` accept three slots:\n\n- `header` (ReactNode) → rendered inside `<header>`\n- `children` → rendered inside `<main>`\n- `footer` (ReactNode) → rendered inside `<footer>`",
      requirements: ["header prop inside <header>", "children inside <main>", "footer prop inside <footer>"],
      hints: ["Any prop can hold JSX, not only children.", "<header>{header}</header><main>{children}</main><footer>{footer}</footer>"],
      starterCode: `import type { ReactNode } from "react";\n\ninterface LayoutProps {\n  header: ReactNode;\n  footer: ReactNode;\n  children: ReactNode;\n}\n\nfunction Layout(props: LayoutProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Layout;\n`,
      solutionCode: `import type { ReactNode } from "react";\n\ninterface LayoutProps {\n  header: ReactNode;\n  footer: ReactNode;\n  children: ReactNode;\n}\n\nfunction Layout({ header, footer, children }: LayoutProps) {\n  return (\n    <>\n      <header>{header}</header>\n      <main>{children}</main>\n      <footer>{footer}</footer>\n    </>\n  );\n}\n\nexport default Layout;\n`,
      explanation: "Passing JSX through named props ('slots') lets one component define the structure while the caller supplies every piece of content.",
      tests: [
        test("places each slot correctly", `render(<Component header={<h1>Site</h1>} footer={<p>© Me</p>}><p>Body</p></Component>);\nwithin(screen.getByRole("banner")).getByText("Site");\nwithin(screen.getByRole("main")).getByText("Body");\nwithin(screen.getByRole("contentinfo")).getByText("© Me");`),
        hidden("works with other content", `render(<Component header={<nav>Nav</nav>} footer="Footer text"><button>Click</button></Component>);\nwithin(screen.getByRole("main")).getByRole("button", { name: "Click" });\nwithin(screen.getByRole("contentinfo")).getByText("Footer text");`),
      ],
    },
    {
      slug: "children-modal",
      title: "Modal With Children",
      difficulty: "EASY",
      tags: ["children", "conditional-rendering", "accessibility"],
      estimatedMinutes: 10,
      description:
        "Make `Modal` accept `isOpen`, `title`, and `children`.\n\n- When `isOpen` is false, render nothing.\n- When open, render `<div role=\"dialog\" aria-labelledby=\"modal-title\">` containing `<h2 id=\"modal-title\">{title}</h2>` followed by the children.\n\n`aria-labelledby` gives the dialog its accessible name from the heading.",
      requirements: ["Renders nothing when closed", "Renders a dialog named by its title when open", "Renders children inside the dialog"],
      hints: ["Return null early when !isOpen.", "The id on the h2 must match aria-labelledby."],
      starterCode: `import type { ReactNode } from "react";\n\ninterface ModalProps {\n  isOpen: boolean;\n  title: string;\n  children: ReactNode;\n}\n\nfunction Modal(props: ModalProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Modal;\n`,
      solutionCode: `import type { ReactNode } from "react";\n\ninterface ModalProps {\n  isOpen: boolean;\n  title: string;\n  children: ReactNode;\n}\n\nfunction Modal({ isOpen, title, children }: ModalProps) {\n  if (!isOpen) return null;\n\n  return (\n    <div role="dialog" aria-labelledby="modal-title">\n      <h2 id="modal-title">{title}</h2>\n      {children}\n    </div>\n  );\n}\n\nexport default Modal;\n`,
      explanation: "The parent controls whether the modal is open; the modal controls how it looks. Linking the title with aria-labelledby is what lets screen readers announce 'Delete file, dialog'.",
      tests: [
        test("renders an accessible dialog when open", `render(<Component isOpen title="Delete file?"><p>This cannot be undone.</p></Component>);\nconst dialog = screen.getByRole("dialog", { name: "Delete file?" });\nwithin(dialog).getByText("This cannot be undone.");`),
        hidden("renders nothing when closed", `const { container } = render(<Component isOpen={false} title="Hidden"><p>Secret</p></Component>);\nassertEqual(container.innerHTML, "", "A closed modal should render nothing");`),
      ],
      wrongSolutions: [`function Modal({ title, children }) {\n  return (<div role="dialog" aria-labelledby="modal-title"><h2 id="modal-title">{title}</h2>{children}</div>);\n}\n\nexport default Modal;\n`],
    },
    {
      slug: "children-dialog-actions",
      title: "Dialog With an Actions Slot",
      difficulty: "EASY",
      tags: ["children", "composition"],
      estimatedMinutes: 10,
      description:
        "Make `ConfirmDialog` accept `title`, `children` (the message), and `actions` (buttons). Render:\n\n```\n<div role=\"alertdialog\" aria-label={title}>\n  <h2>{title}</h2>\n  <div className=\"body\">{children}</div>\n  <div className=\"actions\">{actions}</div>\n</div>\n```",
      requirements: ["alertdialog named by title", "children inside .body", "actions inside .actions"],
      hints: ["`actions` is a ReactNode prop, just like children.", "Query-friendly class names make each area easy to find."],
      starterCode: `import type { ReactNode } from "react";\n\ninterface ConfirmDialogProps {\n  title: string;\n  children: ReactNode;\n  actions: ReactNode;\n}\n\nfunction ConfirmDialog(props: ConfirmDialogProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default ConfirmDialog;\n`,
      solutionCode: `import type { ReactNode } from "react";\n\ninterface ConfirmDialogProps {\n  title: string;\n  children: ReactNode;\n  actions: ReactNode;\n}\n\nfunction ConfirmDialog({ title, children, actions }: ConfirmDialogProps) {\n  return (\n    <div role="alertdialog" aria-label={title}>\n      <h2>{title}</h2>\n      <div className="body">{children}</div>\n      <div className="actions">{actions}</div>\n    </div>\n  );\n}\n\nexport default ConfirmDialog;\n`,
      explanation: "Slots let the caller decide which buttons a dialog has (Cancel/Delete, OK, Retry...) without the dialog needing a prop for each case.",
      tests: [
        test("renders message and actions", `render(<Component title="Discard draft?" actions={<><button>Cancel</button><button>Discard</button></>}>Your changes will be lost.</Component>);\nconst d = screen.getByRole("alertdialog", { name: "Discard draft?" });\nwithin(d).getByRole("button", { name: "Discard" });\nwithin(d).getByText("Your changes will be lost.");`),
        hidden("puts each part in its own area", `const { container } = render(<Component title="T" actions={<button>OK</button>}><p>Msg</p></Component>);\nwithin(container.querySelector(".body")).getByText("Msg");\nwithin(container.querySelector(".actions")).getByRole("button", { name: "OK" });`),
      ],
    },
    {
      slug: "children-count",
      title: "Count Children With React.Children",
      difficulty: "EASY",
      tags: ["children", "react-api"],
      estimatedMinutes: 8,
      description:
        "Make `ItemList` render its children inside a `<ul>`, preceded by `<p>{n} items</p>`, where `n` is the number of children.\n\nUse `Children.count(children)` from React — `children` may be a single element, an array, or nothing, so `.length` isn't reliable.",
      requirements: ["Shows the correct count", "Renders children inside a <ul>"],
      hints: ["import { Children } from \"react\";", "Children.count(children) counts the child nodes."],
      starterCode: `import { Children, type ReactNode } from "react";\n\ninterface ItemListProps {\n  children: ReactNode;\n}\n\nfunction ItemList(props: ItemListProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default ItemList;\n`,
      solutionCode: `import { Children, type ReactNode } from "react";\n\ninterface ItemListProps {\n  children: ReactNode;\n}\n\nfunction ItemList({ children }: ItemListProps) {\n  return (\n    <div>\n      <p>{Children.count(children)} items</p>\n      <ul>{children}</ul>\n    </div>\n  );\n}\n\nexport default ItemList;\n`,
      explanation: "`children` is opaque: one child is a single element, several are an array. `Children.count` handles every shape correctly.",
      commonMistakes: ["children.length is undefined for a single child and counts characters for a string child."],
      tests: [
        test("counts three children", `render(<Component><li>A</li><li>B</li><li>C</li></Component>);\nexpectText("3 items");\nassertEqual(screen.getAllByRole("listitem").length, 3);`),
        hidden("counts a single child", `render(<Component><li>Only</li></Component>);\nexpectText("1 items");`),
      ],
      wrongSolutions: [`function ItemList({ children }) {\n  return (<div><p>{children.length} items</p><ul>{children}</ul></div>);\n}\n\nexport default ItemList;\n`],
    },
    {
      slug: "children-labelled-section",
      title: "Reusable Labelled Section",
      difficulty: "EASY",
      tags: ["children", "accessibility"],
      estimatedMinutes: 10,
      description:
        "Make `Section` accept `id`, `heading`, and `children`. Render a `<section>` labelled by its heading, so screen readers announce it as a named region:\n\n```\n<section aria-labelledby={`${id}-heading`}>\n  <h2 id={`${id}-heading`}>{heading}</h2>\n  {children}\n</section>\n```",
      requirements: ["The section is a region named by the heading", "Children render inside the section", "Heading id is derived from the id prop"],
      hints: ["Both ids must be computed from the same `id` prop.", "A <section> with an accessible name gets the 'region' role."],
      starterCode: `import type { ReactNode } from "react";\n\ninterface SectionProps {\n  id: string;\n  heading: string;\n  children: ReactNode;\n}\n\nfunction Section(props: SectionProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Section;\n`,
      solutionCode: `import type { ReactNode } from "react";\n\ninterface SectionProps {\n  id: string;\n  heading: string;\n  children: ReactNode;\n}\n\nfunction Section({ id, heading, children }: SectionProps) {\n  const headingId = \`\${id}-heading\`;\n  return (\n    <section aria-labelledby={headingId}>\n      <h2 id={headingId}>{heading}</h2>\n      {children}\n    </section>\n  );\n}\n\nexport default Section;\n`,
      explanation: "Deriving ids from a prop keeps them unique when the component is used several times on one page.",
      tests: [
        test("is a named region", `render(<Component id="faq" heading="FAQ"><p>Answers</p></Component>);\nconst region = screen.getByRole("region", { name: "FAQ" });\nwithin(region).getByText("Answers");`),
        hidden("two sections get distinct ids", `const { container } = render(<><Component id="a" heading="Alpha"><p>1</p></Component><Component id="b" heading="Beta"><p>2</p></Component></>);\nscreen.getByRole("region", { name: "Alpha" });\nscreen.getByRole("region", { name: "Beta" });\nassert(container.querySelector("#b-heading"), "Expected heading id 'b-heading'");`),
      ],
      wrongSolutions: [`function Section({ heading, children }) {\n  return (<section aria-labelledby="section-heading"><h2 id="section-heading">{heading}</h2>{children}</section>);\n}\n\nexport default Section;\n`],
    },
  ],
};
