import { hidden, test, type CategoryBank } from "./types.js";

export const conditional: CategoryBank = {
  category: "Conditional Rendering",
  level: 5,
  type: "COMPONENT",
  prerequisites: ["JSX", "Props"],
  problems: [
    {
      slug: "conditional-rendering",
      title: "Ternary Rendering: Logged In or Out",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering", "ternary"],
      estimatedMinutes: 5,
      description: "Make `LoginStatus` accept `isLoggedIn`. Render `<p>Welcome back!</p>` when it's true and `<p>Please log in.</p>` when it's false.",
      requirements: ["'Welcome back!' when logged in", "'Please log in.' when logged out"],
      hints: ["A ternary chooses between two values: condition ? a : b", "<p>{isLoggedIn ? \"Welcome back!\" : \"Please log in.\"}</p>"],
      starterCode: `interface LoginStatusProps {\n  isLoggedIn: boolean;\n}\n\nfunction LoginStatus(props: LoginStatusProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default LoginStatus;\n`,
      solutionCode: `interface LoginStatusProps {\n  isLoggedIn: boolean;\n}\n\nfunction LoginStatus({ isLoggedIn }: LoginStatusProps) {\n  return <p>{isLoggedIn ? "Welcome back!" : "Please log in."}</p>;\n}\n\nexport default LoginStatus;\n`,
      explanation: "JSX is JavaScript, so a ternary expression can choose what gets rendered.",
      tests: [
        test("shows 'Welcome back!' when logged in", `renderComponent({ isLoggedIn: true });\nexpectText("Welcome back!");`),
        hidden("shows 'Please log in.' when logged out", `renderComponent({ isLoggedIn: false });\nexpectText("Please log in.");\nexpectNoText("Welcome back!");`),
      ],
      wrongSolutions: [`function LoginStatus() {\n  return <p>Welcome back!</p>;\n}\n\nexport default LoginStatus;\n`],
    },
    {
      slug: "cond-and-operator",
      title: "&& Rendering and the Zero Trap",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering", "logical-and"],
      estimatedMinutes: 8,
      description:
        "Make `UnreadBadge` accept `count`. When `count` is greater than 0, render `<p>You have {count} new messages</p>`. Otherwise render **nothing at all**.\n\nCareful: `{count && <p>...</p>}` renders a literal `0` when count is 0!",
      requirements: ["Shows the message when count > 0", "Renders nothing (not even '0') when count is 0"],
      hints: ["`&&` returns its left side when that side is falsy, and React renders the number 0.", "Make the left side a real boolean: {count > 0 && ...}"],
      starterCode: `interface UnreadBadgeProps {\n  count: number;\n}\n\nfunction UnreadBadge(props: UnreadBadgeProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default UnreadBadge;\n`,
      solutionCode: `interface UnreadBadgeProps {\n  count: number;\n}\n\nfunction UnreadBadge({ count }: UnreadBadgeProps) {\n  return <div>{count > 0 && <p>You have {count} new messages</p>}</div>;\n}\n\nexport default UnreadBadge;\n`,
      explanation: "React skips false, null and undefined, but renders numbers — including 0. Comparing (count > 0) produces a boolean, so nothing renders when there are no messages.",
      commonMistakes: ["{count && <p>...</p>} shows a stray '0' on screen."],
      tests: [
        test("shows the count", `renderComponent({ count: 3 });\nexpectText("You have 3 new messages");`),
        hidden("renders no stray 0", `const { container } = renderComponent({ count: 0 });\nassertEqual(container.textContent, "", "Nothing should be rendered when count is 0");`),
      ],
      wrongSolutions: [`function UnreadBadge({ count }) {\n  return <div>{count && <p>You have {count} new messages</p>}</div>;\n}\n\nexport default UnreadBadge;\n`],
    },
    {
      slug: "cond-early-return",
      title: "Early Return",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering"],
      estimatedMinutes: 5,
      description:
        "Make `UserGreeting` accept `user`, which is either `null` or `{ name: string }`.\n\n- If there is no user, **return early** with `<p>Please sign in.</p>`.\n- Otherwise render `<p>Welcome back, {user.name}!</p>`.",
      requirements: ["Handles a null user", "Greets a signed-in user by name"],
      hints: ["An if statement before the main return works well here.", "if (!user) return <p>Please sign in.</p>;"],
      starterCode: `interface UserGreetingProps {\n  user: { name: string } | null;\n}\n\nfunction UserGreeting(props: UserGreetingProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default UserGreeting;\n`,
      solutionCode: `interface UserGreetingProps {\n  user: { name: string } | null;\n}\n\nfunction UserGreeting({ user }: UserGreetingProps) {\n  if (!user) {\n    return <p>Please sign in.</p>;\n  }\n  return <p>Welcome back, {user.name}!</p>;\n}\n\nexport default UserGreeting;\n`,
      explanation: "Early returns handle special cases first, so the main JSX doesn't need nested ternaries. TypeScript also knows `user` isn't null after the check.",
      commonMistakes: ["Reading user.name before checking for null crashes with 'Cannot read properties of null'."],
      tests: [
        test("greets a user", `renderComponent({ user: { name: "Ola" } });\nexpectText("Welcome back, Ola!");`),
        hidden("handles a missing user", `renderComponent({ user: null });\nexpectText("Please sign in.");`),
      ],
    },
    {
      slug: "cond-return-null",
      title: "Render Nothing With null",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering"],
      estimatedMinutes: 5,
      description:
        "Make `Banner` accept an optional `message`. When there is a non-empty message, render `<div className=\"banner\">{message}</div>`. When the message is missing or an empty string, return `null` so nothing appears.",
      requirements: ["Shows the banner when there's a message", "Renders nothing for undefined or ''"],
      hints: ["A component may return null to render nothing.", "if (!message) return null;"],
      starterCode: `interface BannerProps {\n  message?: string;\n}\n\nfunction Banner(props: BannerProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Banner;\n`,
      solutionCode: `interface BannerProps {\n  message?: string;\n}\n\nfunction Banner({ message }: BannerProps) {\n  if (!message) return null;\n  return <div className="banner">{message}</div>;\n}\n\nexport default Banner;\n`,
      explanation: "Returning null is how a component opts out of rendering while still being 'mounted' in the tree.",
      tests: [
        test("shows a message", `const { container } = renderComponent({ message: "Sale ends today" });\nassertEqual(container.querySelector(".banner")?.textContent, "Sale ends today");`),
        hidden("renders nothing for empty or missing messages", `const { container, rerender } = renderComponent({ message: "" });\nassertEqual(container.innerHTML, "");\nrerender(<Component />);\nassertEqual(container.innerHTML, "");`),
      ],
      wrongSolutions: [`function Banner({ message }) {\n  return <div className="banner">{message}</div>;\n}\n\nexport default Banner;\n`],
    },
    {
      slug: "cond-stock-status",
      title: "Three-Way Stock Status",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering"],
      estimatedMinutes: 8,
      description:
        "Make `StockStatus` accept `quantity` and render a `<span>`:\n\n- `0` → `Out of stock`\n- `1` to `5` → `Only {quantity} left`\n- more than `5` → `In stock`",
      requirements: ["Handles 0, low stock, and plenty of stock"],
      hints: ["Check the most specific condition first.", "Use if/else if/else before returning, or compute a `label` variable."],
      starterCode: `interface StockStatusProps {\n  quantity: number;\n}\n\nfunction StockStatus(props: StockStatusProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default StockStatus;\n`,
      solutionCode: `interface StockStatusProps {\n  quantity: number;\n}\n\nfunction StockStatus({ quantity }: StockStatusProps) {\n  let label: string;\n  if (quantity === 0) {\n    label = "Out of stock";\n  } else if (quantity <= 5) {\n    label = \`Only \${quantity} left\`;\n  } else {\n    label = "In stock";\n  }\n  return <span>{label}</span>;\n}\n\nexport default StockStatus;\n`,
      explanation: "With more than two outcomes, computing a variable with if/else keeps the JSX simple and avoids nested ternaries.",
      tests: [
        test("plenty of stock", `renderComponent({ quantity: 20 });\nexpectText("In stock");`),
        hidden("low and zero stock", `const { rerender } = renderComponent({ quantity: 3 });\nexpectText("Only 3 left");\nrerender(<Component quantity={5} />);\nexpectText("Only 5 left");\nrerender(<Component quantity={0} />);\nexpectText("Out of stock");`),
      ],
      wrongSolutions: [`function StockStatus({ quantity }) {\n  return <span>{quantity > 0 ? "In stock" : "Out of stock"}</span>;\n}\n\nexport default StockStatus;\n`],
    },
    {
      slug: "cond-switch-status",
      title: "Switch on an Order Status",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering", "switch"],
      estimatedMinutes: 8,
      description:
        "Make `OrderStatus` accept `status` and render a `<p>`:\n\n| status | text |\n|---|---|\n| pending | ⏳ Waiting for payment |\n| shipped | 🚚 On its way |\n| delivered | ✅ Delivered |\n| cancelled | ❌ Cancelled |\n\nUse a `switch` statement in a helper function.",
      requirements: ["Correct text for all four statuses"],
      hints: ["Write function getMessage(status) { switch (status) { case \"pending\": return ...; } }", "Call it in JSX: <p>{getMessage(status)}</p>"],
      starterCode: `type Status = "pending" | "shipped" | "delivered" | "cancelled";\n\ninterface OrderStatusProps {\n  status: Status;\n}\n\nfunction OrderStatus(props: OrderStatusProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default OrderStatus;\n`,
      solutionCode: `type Status = "pending" | "shipped" | "delivered" | "cancelled";\n\nfunction getMessage(status: Status) {\n  switch (status) {\n    case "pending":\n      return "⏳ Waiting for payment";\n    case "shipped":\n      return "🚚 On its way";\n    case "delivered":\n      return "✅ Delivered";\n    case "cancelled":\n      return "❌ Cancelled";\n  }\n}\n\ninterface OrderStatusProps {\n  status: Status;\n}\n\nfunction OrderStatus({ status }: OrderStatusProps) {\n  return <p>{getMessage(status)}</p>;\n}\n\nexport default OrderStatus;\n`,
      explanation: "switch can't go directly inside JSX (it's a statement, not an expression), so it lives in a helper function that returns the value to render.",
      alternativeApproach: "A lookup object { pending: \"...\", ... } does the same job in less code when every case returns a simple value.",
      tests: [
        test("pending", `renderComponent({ status: "pending" });\nexpectText("⏳ Waiting for payment");`),
        hidden("every other status", `const { rerender } = renderComponent({ status: "shipped" });\nexpectText("🚚 On its way");\nrerender(<Component status="delivered" />);\nexpectText("✅ Delivered");\nrerender(<Component status="cancelled" />);\nexpectText("❌ Cancelled");`),
      ],
    },
    {
      slug: "cond-independent-badges",
      title: "Independent Conditional Badges",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering", "logical-and"],
      estimatedMinutes: 8,
      description:
        "Make `UserCard` accept `name`, `isPremium`, and `isVerified`. Render the name in an `<h3>`. Then, independently:\n\n- if `isPremium`, render `<span>Premium</span>`\n- if `isVerified`, render `<span>Verified</span>`\n\nA user can have both badges, one, or neither.",
      requirements: ["Each badge appears only when its flag is true", "Both can appear together"],
      hints: ["Use one && per badge.", "Booleans are safe on the left of && (no zero trap)."],
      starterCode: `interface UserCardProps {\n  name: string;\n  isPremium: boolean;\n  isVerified: boolean;\n}\n\nfunction UserCard(props: UserCardProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default UserCard;\n`,
      solutionCode: `interface UserCardProps {\n  name: string;\n  isPremium: boolean;\n  isVerified: boolean;\n}\n\nfunction UserCard({ name, isPremium, isVerified }: UserCardProps) {\n  return (\n    <div>\n      <h3>{name}</h3>\n      {isPremium && <span>Premium</span>}\n      {isVerified && <span>Verified</span>}\n    </div>\n  );\n}\n\nexport default UserCard;\n`,
      explanation: "Independent conditions get independent checks. A ternary would wrongly force a choice between the two badges.",
      tests: [
        test("shows both badges", `renderComponent({ name: "Ivy", isPremium: true, isVerified: true });\nexpectText("Premium");\nexpectText("Verified");`),
        hidden("shows only the badges that apply", `const { rerender } = renderComponent({ name: "Ivy", isPremium: false, isVerified: true });\nexpectNoText("Premium");\nexpectText("Verified");\nrerender(<Component name="Ivy" isPremium={false} isVerified={false} />);\nexpectNoText("Verified");\nscreen.getByRole("heading", { name: "Ivy" });`),
      ],
      wrongSolutions: [`function UserCard({ name, isPremium }) {\n  return (<div><h3>{name}</h3>{isPremium ? <span>Premium</span> : <span>Verified</span>}</div>);\n}\n\nexport default UserCard;\n`],
    },
    {
      slug: "cond-classname",
      title: "Conditional Class Names",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering", "styling"],
      estimatedMinutes: 5,
      description:
        "Make `TaskItem` accept `title` and `done`. Render `<li>{title}</li>` with the class `task` always, plus `done` when the task is complete: `className=\"task done\"`.",
      requirements: ["className 'task' when not done", "className 'task done' when done"],
      hints: ["Build the string with a ternary.", "className={done ? \"task done\" : \"task\"}"],
      starterCode: `interface TaskItemProps {\n  title: string;\n  done: boolean;\n}\n\nfunction TaskItem(props: TaskItemProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default TaskItem;\n`,
      solutionCode: `interface TaskItemProps {\n  title: string;\n  done: boolean;\n}\n\nfunction TaskItem({ title, done }: TaskItemProps) {\n  return <li className={done ? "task done" : "task"}>{title}</li>;\n}\n\nexport default TaskItem;\n`,
      explanation: "Conditionally adding classes is the most common way to style UI by state. Libraries like `clsx` help once there are many conditions.",
      tests: [
        test("adds done when complete", `renderComponent({ title: "Buy milk", done: true });\nassertEqual(expectText("Buy milk").className, "task done");`),
        hidden("plain task class when not done", `renderComponent({ title: "Walk dog", done: false });\nassertEqual(expectText("Walk dog").className, "task");`),
      ],
      wrongSolutions: [`function TaskItem({ title }) {\n  return <li className="task done">{title}</li>;\n}\n\nexport default TaskItem;\n`],
    },
    {
      slug: "cond-nested",
      title: "Nested Conditions",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering"],
      estimatedMinutes: 8,
      description:
        "Make `WeatherAdvice` accept `temperature` (°C) and `isRaining`, and render one `<p>`:\n\n- raining → `Bring an umbrella`\n- not raining and temperature above 25 → `Wear sunscreen`\n- not raining and 5 or below → `Wear a coat`\n- otherwise → `Enjoy the day`",
      requirements: ["Rain takes priority", "Temperature decides the rest"],
      hints: ["Handle rain first, then check temperatures.", "A small helper function with if/return statements reads best."],
      starterCode: `interface WeatherAdviceProps {\n  temperature: number;\n  isRaining: boolean;\n}\n\nfunction WeatherAdvice(props: WeatherAdviceProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default WeatherAdvice;\n`,
      solutionCode: `interface WeatherAdviceProps {\n  temperature: number;\n  isRaining: boolean;\n}\n\nfunction getAdvice(temperature: number, isRaining: boolean) {\n  if (isRaining) return "Bring an umbrella";\n  if (temperature > 25) return "Wear sunscreen";\n  if (temperature <= 5) return "Wear a coat";\n  return "Enjoy the day";\n}\n\nfunction WeatherAdvice({ temperature, isRaining }: WeatherAdviceProps) {\n  return <p>{getAdvice(temperature, isRaining)}</p>;\n}\n\nexport default WeatherAdvice;\n`,
      explanation: "Ordering conditions by priority and returning early turns nested logic into a flat, readable list.",
      tests: [
        test("rain wins", `renderComponent({ temperature: 30, isRaining: true });\nexpectText("Bring an umbrella");`),
        hidden("temperature cases", `const { rerender } = renderComponent({ temperature: 30, isRaining: false });\nexpectText("Wear sunscreen");\nrerender(<Component temperature={5} isRaining={false} />);\nexpectText("Wear a coat");\nrerender(<Component temperature={15} isRaining={false} />);\nexpectText("Enjoy the day");`),
      ],
      wrongSolutions: [`function WeatherAdvice({ temperature, isRaining }) {\n  if (temperature > 25) return <p>Wear sunscreen</p>;\n  if (isRaining) return <p>Bring an umbrella</p>;\n  return <p>Enjoy the day</p>;\n}\n\nexport default WeatherAdvice;\n`],
    },
    {
      slug: "cond-role-ui",
      title: "Show Controls Based on Role",
      difficulty: "EASY",
      tags: ["conditional-rendering", "authorization"],
      estimatedMinutes: 10,
      description:
        "Make `DocumentToolbar` accept `role`: `\"admin\" | \"editor\" | \"viewer\"`.\n\n- admin → buttons `Edit` and `Delete`\n- editor → button `Edit` only\n- viewer → no buttons, and the text `Read only`",
      requirements: ["Admins can edit and delete", "Editors can only edit", "Viewers see 'Read only'"],
      hints: ["Compute booleans first: const canEdit = role === \"admin\" || role === \"editor\";", "Then render each button with &&."],
      starterCode: `interface DocumentToolbarProps {\n  role: "admin" | "editor" | "viewer";\n}\n\nfunction DocumentToolbar(props: DocumentToolbarProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default DocumentToolbar;\n`,
      solutionCode: `interface DocumentToolbarProps {\n  role: "admin" | "editor" | "viewer";\n}\n\nfunction DocumentToolbar({ role }: DocumentToolbarProps) {\n  const canEdit = role === "admin" || role === "editor";\n  const canDelete = role === "admin";\n\n  return (\n    <div>\n      {canEdit && <button>Edit</button>}\n      {canDelete && <button>Delete</button>}\n      {!canEdit && <p>Read only</p>}\n    </div>\n  );\n}\n\nexport default DocumentToolbar;\n`,
      explanation: "Naming permissions (canEdit, canDelete) separates 'who can do what' from 'what gets rendered'. Note that hiding a button is only UX — the server must still check permissions.",
      tests: [
        test("admin sees both buttons", `renderComponent({ role: "admin" });\nscreen.getByRole("button", { name: "Edit" });\nscreen.getByRole("button", { name: "Delete" });`),
        hidden("editor and viewer", `const { rerender } = renderComponent({ role: "editor" });\nscreen.getByRole("button", { name: "Edit" });\nassert(!screen.queryByRole("button", { name: "Delete" }), "Editors must not see Delete");\nrerender(<Component role="viewer" />);\nassertEqual(screen.queryAllByRole("button").length, 0, "Viewers should see no buttons");\nexpectText("Read only");`),
      ],
      wrongSolutions: [`function DocumentToolbar({ role }) {\n  return (<div>{role !== "viewer" && <><button>Edit</button><button>Delete</button></>}{role === "viewer" && <p>Read only</p>}</div>);\n}\n\nexport default DocumentToolbar;\n`],
    },
    {
      slug: "cond-loading-error-data",
      title: "Loading, Error, Empty, or Data",
      difficulty: "EASY",
      tags: ["conditional-rendering", "async-ui"],
      estimatedMinutes: 10,
      description:
        "Make `ResultsView` accept `loading`, `error` (string or null), and `items` (string[]). Render exactly one of these, checked in this priority order:\n\n1. `loading` → `<p>Loading...</p>`\n2. `error` → `<p role=\"alert\">{error}</p>`\n3. empty `items` → `<p>No results</p>`\n4. otherwise → a `<ul>` with one `<li>` per item",
      requirements: ["Follows the priority order", "Only one state is shown at a time"],
      hints: ["A series of early returns maps directly onto the priority list.", "You'll see this exact pattern again with useEffect and APIs."],
      starterCode: `interface ResultsViewProps {\n  loading: boolean;\n  error: string | null;\n  items: string[];\n}\n\nfunction ResultsView(props: ResultsViewProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default ResultsView;\n`,
      solutionCode: `interface ResultsViewProps {\n  loading: boolean;\n  error: string | null;\n  items: string[];\n}\n\nfunction ResultsView({ loading, error, items }: ResultsViewProps) {\n  if (loading) return <p>Loading...</p>;\n  if (error) return <p role="alert">{error}</p>;\n  if (items.length === 0) return <p>No results</p>;\n\n  return (\n    <ul>\n      {items.map((item) => (\n        <li key={item}>{item}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default ResultsView;\n`,
      explanation: "Async UI always has these four states. Making their priority explicit avoids showing a spinner and an error at the same time.",
      tests: [
        test("shows data", `renderComponent({ loading: false, error: null, items: ["Alpha", "Beta"] });\nassertEqual(screen.getAllByRole("listitem").map((li) => li.textContent), ["Alpha", "Beta"]);`),
        hidden("respects priority", `const { rerender } = renderComponent({ loading: true, error: "Boom", items: ["A"] });\nexpectText("Loading...");\nexpectNoText("Boom");\nrerender(<Component loading={false} error="Boom" items={["A"]} />);\nassertEqual(screen.getByRole("alert").textContent, "Boom");\nassert(!screen.queryByRole("list"), "The list must not show while there's an error");\nrerender(<Component loading={false} error={null} items={[]} />);\nexpectText("No results");`),
      ],
      wrongSolutions: [`function ResultsView({ loading, error, items }) {\n  return (<div>{loading && <p>Loading...</p>}{error && <p role="alert">{error}</p>}<ul>{items.map((i) => <li key={i}>{i}</li>)}</ul></div>);\n}\n\nexport default ResultsView;\n`],
    },
    {
      slug: "cond-choose-component",
      title: "Choose Which Component to Render",
      difficulty: "EASY",
      tags: ["conditional-rendering", "components"],
      estimatedMinutes: 10,
      description:
        "The starter code has two layout components, `GridView` and `ListView`. Make `Gallery` accept `layout` (`\"grid\" | \"list\"`) and `items`, and render the matching component with the items.\n\nStore the chosen component in a variable: `const View = layout === \"grid\" ? GridView : ListView;` then render `<View items={items} />`.",
      requirements: ["layout='list' renders ListView", "layout='grid' renders GridView"],
      hints: ["Components are values — you can store them in a variable.", "The variable must be capitalized to be used as a JSX tag."],
      starterCode: `interface ViewProps {\n  items: string[];\n}\n\nexport function GridView({ items }: ViewProps) {\n  return <div className="grid">{items.join(" | ")}</div>;\n}\n\nexport function ListView({ items }: ViewProps) {\n  return (\n    <ul>\n      {items.map((item) => (\n        <li key={item}>{item}</li>\n      ))}\n    </ul>\n  );\n}\n\ninterface GalleryProps {\n  layout: "grid" | "list";\n  items: string[];\n}\n\nfunction Gallery(props: GalleryProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Gallery;\n`,
      solutionCode: `interface ViewProps {\n  items: string[];\n}\n\nexport function GridView({ items }: ViewProps) {\n  return <div className="grid">{items.join(" | ")}</div>;\n}\n\nexport function ListView({ items }: ViewProps) {\n  return (\n    <ul>\n      {items.map((item) => (\n        <li key={item}>{item}</li>\n      ))}\n    </ul>\n  );\n}\n\ninterface GalleryProps {\n  layout: "grid" | "list";\n  items: string[];\n}\n\nfunction Gallery({ layout, items }: GalleryProps) {\n  const View = layout === "grid" ? GridView : ListView;\n  return <View items={items} />;\n}\n\nexport default Gallery;\n`,
      explanation: "Choosing a component reference and rendering it once avoids duplicating its props in both branches of a ternary.",
      tests: [
        test("list layout", `renderComponent({ layout: "list", items: ["a", "b"] });\nassertEqual(screen.getAllByRole("listitem").length, 2);`),
        hidden("grid layout", `const { container } = renderComponent({ layout: "grid", items: ["a", "b"] });\nassertEqual(container.querySelector(".grid")?.textContent, "a | b");\nassert(!screen.queryByRole("list"), "Grid layout must not render the list");`),
      ],
    },
    {
      slug: "cond-grade",
      title: "Map a Score to a Grade",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering"],
      estimatedMinutes: 5,
      description: "Make `Grade` accept `score` (0–100) and render `<p>Grade: X</p>` where X is: 90+ → A, 80+ → B, 70+ → C, 60+ → D, else F.",
      requirements: ["Correct grade for every range, including boundaries"],
      hints: ["Check from the highest threshold down.", "Boundaries are inclusive: 90 is an A."],
      starterCode: `interface GradeProps {\n  score: number;\n}\n\nfunction Grade(props: GradeProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Grade;\n`,
      solutionCode: `interface GradeProps {\n  score: number;\n}\n\nfunction toLetter(score: number) {\n  if (score >= 90) return "A";\n  if (score >= 80) return "B";\n  if (score >= 70) return "C";\n  if (score >= 60) return "D";\n  return "F";\n}\n\nfunction Grade({ score }: GradeProps) {\n  return <p>Grade: {toLetter(score)}</p>;\n}\n\nexport default Grade;\n`,
      explanation: "Checking thresholds from high to low means each check only needs a lower bound.",
      tests: [
        test("an A", `renderComponent({ score: 95 });\nexpectText("Grade: A");`),
        hidden("boundaries", `const cases = [[90, "A"], [89, "B"], [80, "B"], [70, "C"], [60, "D"], [59, "F"], [0, "F"]];\nfor (const [score, letter] of cases) {\n  const { unmount } = renderComponent({ score });\n  expectText("Grade: " + letter);\n  unmount();\n}`),
      ],
      wrongSolutions: [`function Grade({ score }) {\n  const l = score > 90 ? "A" : score > 80 ? "B" : score > 70 ? "C" : score > 60 ? "D" : "F";\n  return <p>Grade: {l}</p>;\n}\n\nexport default Grade;\n`],
    },
    {
      slug: "cond-pluralize",
      title: "Pluralize a Cart Summary",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering", "strings"],
      estimatedMinutes: 5,
      description:
        "Make `CartSummary` accept `count`:\n\n- 0 → `<p>Your cart is empty</p>`\n- 1 → `<p>1 item in your cart</p>`\n- more → `<p>{count} items in your cart</p>`",
      requirements: ["Empty message for 0", "Singular 'item' for exactly 1", "Plural 'items' otherwise"],
      hints: ["Handle 0 with an early return.", "const word = count === 1 ? \"item\" : \"items\";"],
      starterCode: `interface CartSummaryProps {\n  count: number;\n}\n\nfunction CartSummary(props: CartSummaryProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default CartSummary;\n`,
      solutionCode: `interface CartSummaryProps {\n  count: number;\n}\n\nfunction CartSummary({ count }: CartSummaryProps) {\n  if (count === 0) return <p>Your cart is empty</p>;\n  const word = count === 1 ? "item" : "items";\n  return (\n    <p>\n      {count} {word} in your cart\n    </p>\n  );\n}\n\nexport default CartSummary;\n`,
      explanation: "Small details like '1 items' make a UI feel broken. Conditional text is cheap to get right.",
      tests: [
        test("plural", `renderComponent({ count: 3 });\nexpectText("3 items in your cart");`),
        hidden("singular and empty", `const { rerender } = renderComponent({ count: 1 });\nexpectText("1 item in your cart");\nrerender(<Component count={0} />);\nexpectText("Your cart is empty");`),
      ],
      wrongSolutions: [`function CartSummary({ count }) {\n  if (count === 0) return <p>Your cart is empty</p>;\n  return <p>{count} items in your cart</p>;\n}\n\nexport default CartSummary;\n`],
    },
    {
      slug: "cond-masked-value",
      title: "Show or Mask a Value",
      difficulty: "BEGINNER",
      tags: ["conditional-rendering", "strings"],
      estimatedMinutes: 5,
      description:
        "Make `SecretValue` accept `value` and `revealed`. When revealed, render `<code>{value}</code>`. Otherwise render `<code>` containing one `•` per character, so the length is preserved (`\"abc\"` → `•••`).",
      requirements: ["Shows the value when revealed", "Shows one bullet per character when hidden"],
      hints: ["Strings have a repeat method.", "\"•\".repeat(value.length)"],
      starterCode: `interface SecretValueProps {\n  value: string;\n  revealed: boolean;\n}\n\nfunction SecretValue(props: SecretValueProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default SecretValue;\n`,
      solutionCode: `interface SecretValueProps {\n  value: string;\n  revealed: boolean;\n}\n\nfunction SecretValue({ value, revealed }: SecretValueProps) {\n  return <code>{revealed ? value : "•".repeat(value.length)}</code>;\n}\n\nexport default SecretValue;\n`,
      explanation: "The ternary picks between the real value and a derived, masked version of it.",
      tests: [
        test("reveals the value", `renderComponent({ value: "hunter2", revealed: true });\nexpectText("hunter2");`),
        hidden("masks with the same length", `const { container } = renderComponent({ value: "hunter2", revealed: false });\nassertEqual(container.querySelector("code")?.textContent, "•••••••");\nexpectNoText("hunter2");`),
      ],
      wrongSolutions: [`function SecretValue({ value, revealed }) {\n  return <code>{revealed ? value : "••••••••"}</code>;\n}\n\nexport default SecretValue;\n`],
    },
  ],
};
