import { hidden, test, type CategoryBank } from "./types.js";

const items = (sel = "listitem") => `screen.getAllByRole("${sel}").map((el) => el.textContent)`;

export const lists: CategoryBank = {
  category: "Lists",
  level: 6,
  type: "COMPONENT",
  prerequisites: ["JSX", "Props"],
  problems: [
    {
      slug: "render-a-list",
      title: "Render a List of Names",
      difficulty: "BEGINNER",
      tags: ["lists", "map"],
      estimatedMinutes: 5,
      description:
        "Make `FruitList` accept `fruits` (an array of strings) and render a `<ul>` with one `<li>` per fruit.\n\nUse `fruits.map(...)` to turn the data into elements, and give each `<li>` a `key`.",
      requirements: ["One <li> per fruit, in order"],
      hints: ["map() turns an array of data into an array of JSX.", "{fruits.map((fruit) => <li key={fruit}>{fruit}</li>)}"],
      starterCode: `interface FruitListProps {\n  fruits: string[];\n}\n\nfunction FruitList(props: FruitListProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default FruitList;\n`,
      solutionCode: `interface FruitListProps {\n  fruits: string[];\n}\n\nfunction FruitList({ fruits }: FruitListProps) {\n  return (\n    <ul>\n      {fruits.map((fruit) => (\n        <li key={fruit}>{fruit}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default FruitList;\n`,
      explanation: "React renders arrays of elements. map() is the standard way to build one from data.",
      tests: [
        test("renders each fruit", `renderComponent({ fruits: ["Apple", "Banana"] });\nassertEqual(${items()}, ["Apple", "Banana"]);`),
        hidden("works with a longer list", `renderComponent({ fruits: ["Mango", "Kiwi", "Pear", "Fig"] });\nassertEqual(${items()}, ["Mango", "Kiwi", "Pear", "Fig"]);`),
      ],
      wrongSolutions: [`function FruitList() {\n  return (<ul><li>Apple</li><li>Banana</li></ul>);\n}\n\nexport default FruitList;\n`],
    },
    {
      slug: "list-with-keys",
      title: "Render a List With Keys",
      difficulty: "BEGINNER",
      tags: ["lists", "keys"],
      estimatedMinutes: 5,
      description:
        "Make `ItemList` accept `items`, an array of `{ id, name }`, and render each name as an `<li>`. Give each item a `key` from its `id`.",
      requirements: ["Renders each item's name", "Every item has a key (no React 'key' warning)"],
      hints: [
        "React needs a key on each element in a list so it can track items between renders.",
        "Prefer stable ids over the array index: key={item.id}",
      ],
      starterCode: `interface Item {\n  id: number;\n  name: string;\n}\n\ninterface ItemListProps {\n  items: Item[];\n}\n\nfunction ItemList(props: ItemListProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default ItemList;\n`,
      solutionCode: `interface Item {\n  id: number;\n  name: string;\n}\n\ninterface ItemListProps {\n  items: Item[];\n}\n\nfunction ItemList({ items }: ItemListProps) {\n  return (\n    <ul>\n      {items.map((item) => (\n        <li key={item.id}>{item.name}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default ItemList;\n`,
      explanation: "Keys let React match items across renders, so it updates, reorders, or removes the right DOM nodes. Index keys break when the list is reordered or filtered, even though React doesn't warn about them.",
      tests: [
        test("renders the names", `renderComponent({ items: [{ id: 1, name: "A" }, { id: 2, name: "B" }] });\nassertEqual(${items()}, ["A", "B"]);`),
        hidden("no missing-key warning", `renderComponent({ items: [{ id: 1, name: "A" }, { id: 2, name: "B" }, { id: 3, name: "C" }] });\nassert(!anyConsoleError("unique \\"key\\""), "React warned that list items need a unique 'key' prop");`),
      ],
      wrongSolutions: [`function ItemList({ items }) {\n  return <ul>{items.map((item) => <li>{item.name}</li>)}</ul>;\n}\n\nexport default ItemList;\n`],
    },
    {
      slug: "lists-transform",
      title: "Transform Items While Mapping",
      difficulty: "BEGINNER",
      tags: ["lists", "map"],
      estimatedMinutes: 5,
      description: "Make `DoubledNumbers` accept `numbers` and render a `<ul>` where each `<li>` shows the number **doubled**: `[1, 2, 3]` → `2`, `4`, `6`.",
      requirements: ["Each item shows number × 2"],
      hints: ["The map callback can compute anything before returning JSX.", "<li key={i}>{n * 2}</li>"],
      starterCode: `interface DoubledNumbersProps {\n  numbers: number[];\n}\n\nfunction DoubledNumbers(props: DoubledNumbersProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default DoubledNumbers;\n`,
      solutionCode: `interface DoubledNumbersProps {\n  numbers: number[];\n}\n\nfunction DoubledNumbers({ numbers }: DoubledNumbersProps) {\n  return (\n    <ul>\n      {numbers.map((n, i) => (\n        <li key={i}>{n * 2}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default DoubledNumbers;\n`,
      explanation: "map() can transform values, not just wrap them. An index key is acceptable here because the list is static and never reordered.",
      tests: [
        test("doubles each number", `renderComponent({ numbers: [1, 2, 3] });\nassertEqual(${items()}, ["2", "4", "6"]);`),
        hidden("works with other numbers", `renderComponent({ numbers: [10, -1, 0] });\nassertEqual(${items()}, ["20", "-2", "0"]);`),
      ],
    },
    {
      slug: "lists-objects",
      title: "Render a List of Users",
      difficulty: "BEGINNER",
      tags: ["lists", "objects"],
      estimatedMinutes: 5,
      description: "Make `UserList` accept `users` (`{ id, name, email }[]`) and render one `<li>` per user with the text `{name} — {email}`.",
      requirements: ["One item per user formatted 'name — email'", "Keyed by id"],
      hints: ["Destructure inside the callback if you like: users.map(({ id, name, email }) => ...)", "Use the em dash character —"],
      starterCode: `interface User {\n  id: number;\n  name: string;\n  email: string;\n}\n\ninterface UserListProps {\n  users: User[];\n}\n\nfunction UserList(props: UserListProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default UserList;\n`,
      solutionCode: `interface User {\n  id: number;\n  name: string;\n  email: string;\n}\n\ninterface UserListProps {\n  users: User[];\n}\n\nfunction UserList({ users }: UserListProps) {\n  return (\n    <ul>\n      {users.map((user) => (\n        <li key={user.id}>\n          {user.name} — {user.email}\n        </li>\n      ))}\n    </ul>\n  );\n}\n\nexport default UserList;\n`,
      explanation: "Most real lists are arrays of objects, and their database ids make ideal keys.",
      tests: [
        test("renders users", `renderComponent({ users: [{ id: 1, name: "Ana", email: "ana@x.io" }] });\nassertEqual(${items()}, ["Ana — ana@x.io"]);`),
        hidden("renders several users", `renderComponent({ users: [{ id: 7, name: "Bo", email: "bo@y.io" }, { id: 9, name: "Cy", email: "cy@z.io" }] });\nassertEqual(${items()}, ["Bo — bo@y.io", "Cy — cy@z.io"]);`),
      ],
    },
    {
      slug: "lists-ordered-index",
      title: "Number the Steps",
      difficulty: "BEGINNER",
      tags: ["lists", "map"],
      estimatedMinutes: 5,
      description: "Make `Recipe` accept `steps` (strings) and render an ordered list `<ol>` where each item reads `Step {n}: {text}`, starting from 1.",
      requirements: ["Uses <ol>", "Items read 'Step 1: ...', 'Step 2: ...'"],
      hints: ["map passes the index as its second argument.", "The index starts at 0, so add 1."],
      starterCode: `interface RecipeProps {\n  steps: string[];\n}\n\nfunction Recipe(props: RecipeProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default Recipe;\n`,
      solutionCode: `interface RecipeProps {\n  steps: string[];\n}\n\nfunction Recipe({ steps }: RecipeProps) {\n  return (\n    <ol>\n      {steps.map((step, index) => (\n        <li key={index}>\n          Step {index + 1}: {step}\n        </li>\n      ))}\n    </ol>\n  );\n}\n\nexport default Recipe;\n`,
      explanation: "The second map argument is the index — useful for numbering, and acceptable as a key for lists that never change order.",
      tests: [
        test("numbers the steps", `renderComponent({ steps: ["Boil water", "Add pasta"] });\nassertEqual(${items()}, ["Step 1: Boil water", "Step 2: Add pasta"]);`),
        hidden("uses an ordered list", `const { container } = renderComponent({ steps: ["A", "B", "C"] });\nassert(container.querySelector("ol"), "Use an <ol> for ordered steps");\nassertEqual(${items()}, ["Step 1: A", "Step 2: B", "Step 3: C"]);`),
      ],
    },
    {
      slug: "lists-item-component",
      title: "Extract a List Item Component",
      difficulty: "BEGINNER",
      tags: ["lists", "components"],
      estimatedMinutes: 8,
      description:
        "Create and export `ProductItem({ product })` that renders `<li>{name} - ${price}</li>`. Then make `ProductList({ products })` render a `<ul>` with one `ProductItem` per product.\n\nThe `key` goes on `<ProductItem key=... />` in the parent's map — not inside ProductItem.",
      requirements: ["ProductItem renders one product", "ProductList maps products to ProductItem with keys"],
      hints: ["products.map((p) => <ProductItem key={p.id} product={p} />)", "key is used by React and is not passed to the component as a prop."],
      starterCode: `interface Product {\n  id: number;\n  name: string;\n  price: number;\n}\n\nexport function ProductItem(props: { product: Product }) {\n  return null;\n}\n\nfunction ProductList(props: { products: Product[] }) {\n  // Write your solution here\n  return null;\n}\n\nexport default ProductList;\n`,
      solutionCode: `interface Product {\n  id: number;\n  name: string;\n  price: number;\n}\n\nexport function ProductItem({ product }: { product: Product }) {\n  return (\n    <li>\n      {product.name} - \${product.price}\n    </li>\n  );\n}\n\nfunction ProductList({ products }: { products: Product[] }) {\n  return (\n    <ul>\n      {products.map((product) => (\n        <ProductItem key={product.id} product={product} />\n      ))}\n    </ul>\n  );\n}\n\nexport default ProductList;\n`,
      explanation: "When list items get complex, give them their own component. The key belongs on the element returned from map, because that's where React compares siblings.",
      tests: [
        test("renders products", `renderComponent({ products: [{ id: 1, name: "Pen", price: 2 }, { id: 2, name: "Ink", price: 5 }] });\nassertEqual(${items()}, ["Pen - $2", "Ink - $5"]);`),
        hidden("ProductItem works alone and keys are set", `render(<ul><userExports.ProductItem product={{ id: 9, name: "Pad", price: 3 }} /></ul>);\nexpectText("Pad - $3");\nassert(!anyConsoleError("unique \\"key\\""), "Missing key on ProductItem");`),
      ],
    },
    {
      slug: "lists-empty",
      title: "Render an Empty List Message",
      difficulty: "BEGINNER",
      tags: ["lists", "conditional-rendering"],
      estimatedMinutes: 5,
      description: "Make `ResultList` accept `results` (strings). Render them as a `<ul>`, or `<p>No results found</p>` (and no list) when the array is empty.",
      requirements: ["Renders the list when there are results", "Renders only the message when empty"],
      hints: ["Check results.length === 0 first.", "Don't render an empty <ul>."],
      starterCode: `interface ResultListProps {\n  results: string[];\n}\n\nfunction ResultList(props: ResultListProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default ResultList;\n`,
      solutionCode: `interface ResultListProps {\n  results: string[];\n}\n\nfunction ResultList({ results }: ResultListProps) {\n  if (results.length === 0) {\n    return <p>No results found</p>;\n  }\n  return (\n    <ul>\n      {results.map((r) => (\n        <li key={r}>{r}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default ResultList;\n`,
      explanation: "An empty array still renders an empty <ul>, which shows nothing useful. Check the length and show a helpful message instead.",
      tests: [
        test("renders results", `renderComponent({ results: ["one", "two"] });\nassertEqual(${items()}, ["one", "two"]);`),
        hidden("empty state", `renderComponent({ results: [] });\nexpectText("No results found");\nassert(!screen.queryByRole("list"), "Don't render an empty list");`),
      ],
      wrongSolutions: [`function ResultList({ results }) {\n  return (<div>{results.length === 0 && <p>No results found</p>}<ul>{results.map((r) => <li key={r}>{r}</li>)}</ul></div>);\n}\n\nexport default ResultList;\n`],
    },
    {
      slug: "lists-filter",
      title: "Filter a List",
      difficulty: "BEGINNER",
      tags: ["lists", "filter"],
      estimatedMinutes: 8,
      description: "Make `PendingTodos` accept `todos` (`{ id, title, done }[]`) and render only the todos that are **not** done, as `<li>` items.",
      requirements: ["Only incomplete todos are rendered, in their original order"],
      hints: ["filter() first, then map().", "todos.filter((t) => !t.done).map(...)"],
      starterCode: `interface Todo {\n  id: number;\n  title: string;\n  done: boolean;\n}\n\nfunction PendingTodos(props: { todos: Todo[] }) {\n  // Write your solution here\n  return null;\n}\n\nexport default PendingTodos;\n`,
      solutionCode: `interface Todo {\n  id: number;\n  title: string;\n  done: boolean;\n}\n\nfunction PendingTodos({ todos }: { todos: Todo[] }) {\n  return (\n    <ul>\n      {todos\n        .filter((todo) => !todo.done)\n        .map((todo) => (\n          <li key={todo.id}>{todo.title}</li>\n        ))}\n    </ul>\n  );\n}\n\nexport default PendingTodos;\n`,
      explanation: "Chaining filter and map is the idiomatic way to render a subset of a list.",
      tests: [
        test("hides completed todos", `renderComponent({ todos: [{ id: 1, title: "Write", done: false }, { id: 2, title: "Read", done: true }] });\nassertEqual(${items()}, ["Write"]);`),
        hidden("keeps order", `renderComponent({ todos: [{ id: 1, title: "A", done: false }, { id: 2, title: "B", done: true }, { id: 3, title: "C", done: false }] });\nassertEqual(${items()}, ["A", "C"]);`),
      ],
    },
    {
      slug: "lists-sort-no-mutate",
      title: "Sort a List Without Mutating Props",
      difficulty: "EASY",
      tags: ["lists", "sort", "immutability"],
      estimatedMinutes: 10,
      description:
        "Make `CheapestFirst` accept `products` (`{ id, name, price }[]`) and render them sorted by price, lowest first, as `<li>{name}</li>`.\n\n`Array.prototype.sort` sorts **in place** — it would rearrange the parent's array. Sort a copy instead.",
      requirements: ["Sorted ascending by price", "The products prop is not modified"],
      hints: ["Copy first: [...products].sort(...)", "Numeric sort: (a, b) => a.price - b.price", "Modern JS also has products.toSorted(...)."],
      starterCode: `interface Product {\n  id: number;\n  name: string;\n  price: number;\n}\n\nfunction CheapestFirst(props: { products: Product[] }) {\n  // Write your solution here\n  return null;\n}\n\nexport default CheapestFirst;\n`,
      solutionCode: `interface Product {\n  id: number;\n  name: string;\n  price: number;\n}\n\nfunction CheapestFirst({ products }: { products: Product[] }) {\n  const sorted = [...products].sort((a, b) => a.price - b.price);\n  return (\n    <ul>\n      {sorted.map((p) => (\n        <li key={p.id}>{p.name}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default CheapestFirst;\n`,
      explanation: "Props must be treated as read-only. Sorting a copy gives the same output without changing data the parent owns.",
      commonMistakes: ["products.sort(...) mutates the prop.", "sort() without a comparator sorts numbers as strings (10 before 9)."],
      tests: [
        test("sorts by price", `renderComponent({ products: [{ id: 1, name: "B", price: 20 }, { id: 2, name: "A", price: 5 }, { id: 3, name: "C", price: 9 }] });\nassertEqual(${items()}, ["A", "C", "B"]);`),
        hidden("does not mutate the prop", `const products = [{ id: 1, name: "X", price: 100 }, { id: 2, name: "Y", price: 9 }, { id: 3, name: "Z", price: 10 }];\nrenderComponent({ products });\nassertEqual(${items()}, ["Y", "Z", "X"]);\nassertEqual(products.map((p) => p.name), ["X", "Y", "Z"], "The products prop was re-ordered");`),
      ],
      wrongSolutions: [`function CheapestFirst({ products }) {\n  products.sort((a, b) => a.price - b.price);\n  return <ul>{products.map((p) => <li key={p.id}>{p.name}</li>)}</ul>;\n}\n\nexport default CheapestFirst;\n`],
    },
    {
      slug: "lists-top-n",
      title: "Show the Top N Scores",
      difficulty: "EASY",
      tags: ["lists", "sort", "slice"],
      estimatedMinutes: 10,
      description: "Make `Leaderboard` accept `scores` (`{ id, player, points }[]`) and an optional `limit` (default 3). Render the top `limit` players by points, highest first, as `<li>{player}: {points}</li>`.",
      requirements: ["Sorted descending by points", "Only the first `limit` entries", "limit defaults to 3"],
      hints: ["Sort a copy descending: (a, b) => b.points - a.points", "Then .slice(0, limit)"],
      starterCode: `interface Score {\n  id: number;\n  player: string;\n  points: number;\n}\n\nfunction Leaderboard(props: { scores: Score[]; limit?: number }) {\n  // Write your solution here\n  return null;\n}\n\nexport default Leaderboard;\n`,
      solutionCode: `interface Score {\n  id: number;\n  player: string;\n  points: number;\n}\n\nfunction Leaderboard({ scores, limit = 3 }: { scores: Score[]; limit?: number }) {\n  const top = [...scores].sort((a, b) => b.points - a.points).slice(0, limit);\n  return (\n    <ol>\n      {top.map((s) => (\n        <li key={s.id}>\n          {s.player}: {s.points}\n        </li>\n      ))}\n    </ol>\n  );\n}\n\nexport default Leaderboard;\n`,
      explanation: "Sort, slice, map: three small array operations, each with one job, compose into the final list.",
      tests: [
        test("top 3 by default", `renderComponent({ scores: [{ id: 1, player: "a", points: 5 }, { id: 2, player: "b", points: 50 }, { id: 3, player: "c", points: 20 }, { id: 4, player: "d", points: 1 }] });\nassertEqual(${items()}, ["b: 50", "c: 20", "a: 5"]);`),
        hidden("respects limit", `renderComponent({ limit: 2, scores: [{ id: 1, player: "x", points: 1 }, { id: 2, player: "y", points: 3 }, { id: 3, player: "z", points: 2 }] });\nassertEqual(${items()}, ["y: 3", "z: 2"]);`),
      ],
    },
    {
      slug: "lists-search",
      title: "Search a List",
      difficulty: "EASY",
      tags: ["lists", "filter", "search"],
      estimatedMinutes: 10,
      description:
        "Make `CitySearch` accept `cities` (strings) and `query`. Render the cities that contain the query **case-insensitively**. If none match, render `<p>No matches</p>` instead of a list.",
      requirements: ["Case-insensitive substring match", "'No matches' when nothing matches", "An empty query shows everything"],
      hints: ["Lower-case both sides before comparing.", "city.toLowerCase().includes(query.toLowerCase())"],
      starterCode: `function CitySearch(props: { cities: string[]; query: string }) {\n  // Write your solution here\n  return null;\n}\n\nexport default CitySearch;\n`,
      solutionCode: `function CitySearch({ cities, query }: { cities: string[]; query: string }) {\n  const q = query.toLowerCase();\n  const matches = cities.filter((city) => city.toLowerCase().includes(q));\n\n  if (matches.length === 0) return <p>No matches</p>;\n\n  return (\n    <ul>\n      {matches.map((city) => (\n        <li key={city}>{city}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default CitySearch;\n`,
      explanation: "The filtered list is derived from props on every render — there's nothing to store or synchronize.",
      tests: [
        test("filters case-insensitively", `renderComponent({ cities: ["Paris", "Berlin", "Parma"], query: "PAR" });\nassertEqual(${items()}, ["Paris", "Parma"]);`),
        hidden("empty query and no matches", `const { rerender } = renderComponent({ cities: ["Oslo", "Rome"], query: "" });\nassertEqual(${items()}, ["Oslo", "Rome"]);\nrerender(<Component cities={["Oslo", "Rome"]} query="xyz" />);\nexpectText("No matches");`),
      ],
      wrongSolutions: [`function CitySearch({ cities, query }) {\n  const m = cities.filter((c) => c.includes(query));\n  if (!m.length) return <p>No matches</p>;\n  return <ul>{m.map((c) => <li key={c}>{c}</li>)}</ul>;\n}\n\nexport default CitySearch;\n`],
    },
    {
      slug: "lists-filter-category",
      title: "Filter by Category",
      difficulty: "EASY",
      tags: ["lists", "filter"],
      estimatedMinutes: 8,
      description: "Make `ProductGrid` accept `products` (`{ id, name, category }[]`) and `category`. Render the products in that category, or **all** products when `category` is `\"all\"`.",
      requirements: ["Filters by category", "'all' shows everything"],
      hints: ["Handle 'all' inside the filter callback.", "category === \"all\" || p.category === category"],
      starterCode: `interface Product {\n  id: number;\n  name: string;\n  category: string;\n}\n\nfunction ProductGrid(props: { products: Product[]; category: string }) {\n  // Write your solution here\n  return null;\n}\n\nexport default ProductGrid;\n`,
      solutionCode: `interface Product {\n  id: number;\n  name: string;\n  category: string;\n}\n\nfunction ProductGrid({ products, category }: { products: Product[]; category: string }) {\n  const visible = products.filter((p) => category === "all" || p.category === category);\n  return (\n    <ul>\n      {visible.map((p) => (\n        <li key={p.id}>{p.name}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default ProductGrid;\n`,
      explanation: "A special 'all' value is a common filter pattern; folding it into the predicate avoids a separate code path.",
      tests: [
        test("filters by category", `renderComponent({ category: "fruit", products: [{ id: 1, name: "Apple", category: "fruit" }, { id: 2, name: "Leek", category: "veg" }] });\nassertEqual(${items()}, ["Apple"]);`),
        hidden("all shows everything", `renderComponent({ category: "all", products: [{ id: 1, name: "Apple", category: "fruit" }, { id: 2, name: "Leek", category: "veg" }] });\nassertEqual(${items()}, ["Apple", "Leek"]);`),
      ],
    },
    {
      slug: "lists-nested",
      title: "Render Nested Lists",
      difficulty: "EASY",
      tags: ["lists", "nested-data"],
      estimatedMinutes: 10,
      description:
        "Make `Menu` accept `sections` (`{ id, title, dishes: string[] }[]`). For each section render an `<h3>` with the title and a `<ul>` of its dishes. Keys are needed at **both** levels.",
      requirements: ["A heading per section", "A list of dishes under each heading", "No key warnings"],
      hints: ["Nest one map inside another.", "Wrap each section in an element with key={section.id}."],
      starterCode: `interface Section {\n  id: number;\n  title: string;\n  dishes: string[];\n}\n\nfunction Menu(props: { sections: Section[] }) {\n  // Write your solution here\n  return null;\n}\n\nexport default Menu;\n`,
      solutionCode: `interface Section {\n  id: number;\n  title: string;\n  dishes: string[];\n}\n\nfunction Menu({ sections }: { sections: Section[] }) {\n  return (\n    <div>\n      {sections.map((section) => (\n        <section key={section.id}>\n          <h3>{section.title}</h3>\n          <ul>\n            {section.dishes.map((dish) => (\n              <li key={dish}>{dish}</li>\n            ))}\n          </ul>\n        </section>\n      ))}\n    </div>\n  );\n}\n\nexport default Menu;\n`,
      explanation: "Keys only need to be unique among siblings, so each inner list has its own key space.",
      tests: [
        test("renders sections and dishes", `renderComponent({ sections: [{ id: 1, title: "Starters", dishes: ["Soup", "Salad"] }, { id: 2, title: "Mains", dishes: ["Pasta"] }] });\nscreen.getByRole("heading", { name: "Starters" });\nscreen.getByRole("heading", { name: "Mains" });\nassertEqual(${items()}, ["Soup", "Salad", "Pasta"]);`),
        hidden("dishes are grouped under their section and keyed", `const { container } = renderComponent({ sections: [{ id: 1, title: "Desserts", dishes: ["Cake", "Pie"] }] });\nassertEqual(container.querySelectorAll("ul").length, 1);\nassert(!anyConsoleError("unique \\"key\\""), "Missing key warning");`),
      ],
    },
    {
      slug: "lists-table-rows",
      title: "Render Table Rows From Data",
      difficulty: "BEGINNER",
      tags: ["lists", "tables"],
      estimatedMinutes: 10,
      description: "Make `EmployeeTable` accept `employees` (`{ id, name, role }[]`) and render a table with headers `Name` and `Role` and one row per employee.",
      requirements: ["Header row with Name and Role", "One body row per employee"],
      hints: ["Map employees to <tr> elements inside <tbody>.", "Each <tr> needs a key."],
      starterCode: `interface Employee {\n  id: number;\n  name: string;\n  role: string;\n}\n\nfunction EmployeeTable(props: { employees: Employee[] }) {\n  // Write your solution here\n  return null;\n}\n\nexport default EmployeeTable;\n`,
      solutionCode: `interface Employee {\n  id: number;\n  name: string;\n  role: string;\n}\n\nfunction EmployeeTable({ employees }: { employees: Employee[] }) {\n  return (\n    <table>\n      <thead>\n        <tr>\n          <th>Name</th>\n          <th>Role</th>\n        </tr>\n      </thead>\n      <tbody>\n        {employees.map((e) => (\n          <tr key={e.id}>\n            <td>{e.name}</td>\n            <td>{e.role}</td>\n          </tr>\n        ))}\n      </tbody>\n    </table>\n  );\n}\n\nexport default EmployeeTable;\n`,
      explanation: "Tables are lists of rows; the same map + key pattern applies.",
      tests: [
        test("renders rows", `renderComponent({ employees: [{ id: 1, name: "Ann", role: "Dev" }] });\nscreen.getByRole("columnheader", { name: "Role" });\nscreen.getByRole("cell", { name: "Ann" });\nscreen.getByRole("cell", { name: "Dev" });`),
        hidden("one row per employee plus header", `renderComponent({ employees: [{ id: 1, name: "Ann", role: "Dev" }, { id: 2, name: "Raj", role: "PM" }, { id: 3, name: "Li", role: "QA" }] });\nassertEqual(screen.getAllByRole("row").length, 4);`),
      ],
    },
    {
      slug: "lists-object-entries",
      title: "Render an Object's Properties",
      difficulty: "EASY",
      tags: ["lists", "objects"],
      estimatedMinutes: 10,
      description:
        "Make `SpecList` accept `specs`, an object like `{ Weight: \"1.2kg\", Battery: \"10h\" }`. Render a description list `<dl>` with a `<dt>` (key) and `<dd>` (value) for every property, in the object's order.",
      requirements: ["One dt/dd pair per property", "Works for any object"],
      hints: ["Object.entries(specs) gives [key, value] pairs.", "Wrap each pair in a <div key={key}> inside the <dl>."],
      starterCode: `function SpecList(props: { specs: Record<string, string> }) {\n  // Write your solution here\n  return null;\n}\n\nexport default SpecList;\n`,
      solutionCode: `function SpecList({ specs }: { specs: Record<string, string> }) {\n  return (\n    <dl>\n      {Object.entries(specs).map(([key, value]) => (\n        <div key={key}>\n          <dt>{key}</dt>\n          <dd>{value}</dd>\n        </div>\n      ))}\n    </dl>\n  );\n}\n\nexport default SpecList;\n`,
      explanation: "Object.entries turns an object into an array, and then it's just another list.",
      tests: [
        test("renders terms and values", `const { container } = renderComponent({ specs: { Weight: "1.2kg", Battery: "10h" } });\nassertEqual(Array.from(container.querySelectorAll("dt")).map((d) => d.textContent), ["Weight", "Battery"]);\nassertEqual(Array.from(container.querySelectorAll("dd")).map((d) => d.textContent), ["1.2kg", "10h"]);`),
        hidden("works for any object", `const { container } = renderComponent({ specs: { Color: "Red", Size: "M", Fit: "Slim" } });\nassertEqual(container.querySelectorAll("dt").length, 3);\nassertEqual(container.querySelectorAll("dd")[2].textContent, "Slim");`),
      ],
    },
    {
      slug: "lists-breadcrumb",
      title: "Breadcrumbs With Separators",
      difficulty: "EASY",
      tags: ["lists", "accessibility", "navigation"],
      estimatedMinutes: 12,
      description:
        "Make `Breadcrumbs` accept `items` (`{ label, href }[]`). Render `<nav aria-label=\"Breadcrumb\">` with an `<ol>`. Every item except the last is a link; the **last** item is plain text marked with `aria-current=\"page\"`. Show ` / ` between items (not after the last).",
      requirements: ["All but the last item are links", "Last item has aria-current='page' and is not a link", "Separators only between items"],
      hints: ["map gives you the index; compare it with items.length - 1.", "Render the separator only when index < items.length - 1."],
      starterCode: `interface Crumb {\n  label: string;\n  href: string;\n}\n\nfunction Breadcrumbs(props: { items: Crumb[] }) {\n  // Write your solution here\n  return null;\n}\n\nexport default Breadcrumbs;\n`,
      solutionCode: `interface Crumb {\n  label: string;\n  href: string;\n}\n\nfunction Breadcrumbs({ items }: { items: Crumb[] }) {\n  return (\n    <nav aria-label="Breadcrumb">\n      <ol>\n        {items.map((item, index) => {\n          const isLast = index === items.length - 1;\n          return (\n            <li key={item.href}>\n              {isLast ? <span aria-current="page">{item.label}</span> : <a href={item.href}>{item.label}</a>}\n              {!isLast && " / "}\n            </li>\n          );\n        })}\n      </ol>\n    </nav>\n  );\n}\n\nexport default Breadcrumbs;\n`,
      explanation: "Using the index to treat the last item specially is a common list pattern. aria-current tells assistive tech which page you're on.",
      tests: [
        test("links all but the last", `renderComponent({ items: [{ label: "Home", href: "/" }, { label: "Shoes", href: "/shoes" }, { label: "Boots", href: "/shoes/boots" }] });\nconst nav = screen.getByRole("navigation", { name: "Breadcrumb" });\nassertEqual(within(nav).getAllByRole("link").map((a) => a.textContent), ["Home", "Shoes"]);`),
        hidden("marks the current page and has no trailing separator", `const { container } = renderComponent({ items: [{ label: "Home", href: "/" }, { label: "Docs", href: "/docs" }] });\nconst current = container.querySelector("[aria-current='page']");\nassertEqual(current?.textContent, "Docs");\nassertEqual(container.querySelector("ol").textContent, "Home / Docs");`),
      ],
    },
    {
      slug: "lists-cart-total",
      title: "Show a Total Below a List",
      difficulty: "EASY",
      tags: ["lists", "reduce"],
      estimatedMinutes: 10,
      description:
        "Make `CartLines` accept `items` (`{ id, name, price, quantity }[]`). Render one `<li>` per item as `{name} × {quantity}`, then `<p>Total: ${total}</p>` with two decimals, where total = Σ price × quantity.",
      requirements: ["One line per item", "Correct total with two decimals"],
      hints: ["Array.reduce adds up values: items.reduce((sum, i) => sum + i.price * i.quantity, 0)", "Format with toFixed(2)."],
      starterCode: `interface CartItem {\n  id: number;\n  name: string;\n  price: number;\n  quantity: number;\n}\n\nfunction CartLines(props: { items: CartItem[] }) {\n  // Write your solution here\n  return null;\n}\n\nexport default CartLines;\n`,
      solutionCode: `interface CartItem {\n  id: number;\n  name: string;\n  price: number;\n  quantity: number;\n}\n\nfunction CartLines({ items }: { items: CartItem[] }) {\n  const total = items.reduce((sum, item) => sum + item.price * item.quantity, 0);\n  return (\n    <div>\n      <ul>\n        {items.map((item) => (\n          <li key={item.id}>\n            {item.name} × {item.quantity}\n          </li>\n        ))}\n      </ul>\n      <p>Total: \${total.toFixed(2)}</p>\n    </div>\n  );\n}\n\nexport default CartLines;\n`,
      explanation: "The total is derived from the items each render, so it can never disagree with the list above it.",
      tests: [
        test("lines and total", `renderComponent({ items: [{ id: 1, name: "Tea", price: 3.5, quantity: 2 }, { id: 2, name: "Cake", price: 4, quantity: 1 }] });\nassertEqual(${items()}, ["Tea × 2", "Cake × 1"]);\nexpectText("Total: $11.00");`),
        hidden("empty cart totals zero", `renderComponent({ items: [] });\nexpectText("Total: $0.00");`),
      ],
    },
    {
      slug: "lists-group-by",
      title: "Group Contacts by Letter",
      difficulty: "MEDIUM",
      tags: ["lists", "reduce", "nested-data"],
      estimatedMinutes: 15,
      description:
        "Make `ContactDirectory` accept `contacts` (`{ id, name }[]`). Group them by the first letter of their name (upper-case). Render groups in alphabetical order; each group is an `<h3>` with the letter followed by a `<ul>` of names, also sorted alphabetically.",
      requirements: ["Groups by upper-case first letter", "Groups sorted A→Z", "Names sorted within each group"],
      hints: [
        "Build an object like { A: [...], B: [...] } with reduce or a for loop.",
        "Object.keys(groups).sort() gives the letters in order.",
        "localeCompare sorts strings: a.name.localeCompare(b.name)",
      ],
      starterCode: `interface Contact {\n  id: number;\n  name: string;\n}\n\nfunction ContactDirectory(props: { contacts: Contact[] }) {\n  // Write your solution here\n  return null;\n}\n\nexport default ContactDirectory;\n`,
      solutionCode: `interface Contact {\n  id: number;\n  name: string;\n}\n\nfunction ContactDirectory({ contacts }: { contacts: Contact[] }) {\n  const groups: Record<string, Contact[]> = {};\n  for (const contact of contacts) {\n    const letter = contact.name[0].toUpperCase();\n    (groups[letter] ??= []).push(contact);\n  }\n\n  return (\n    <div>\n      {Object.keys(groups)\n        .sort()\n        .map((letter) => (\n          <section key={letter}>\n            <h3>{letter}</h3>\n            <ul>\n              {[...groups[letter]]\n                .sort((a, b) => a.name.localeCompare(b.name))\n                .map((c) => (\n                  <li key={c.id}>{c.name}</li>\n                ))}\n            </ul>\n          </section>\n        ))}\n    </div>\n  );\n}\n\nexport default ContactDirectory;\n`,
      explanation: "Reshape the data first (group, sort), then render. Keeping data transformation separate from JSX makes both easier to read.",
      tests: [
        test("groups by letter", `renderComponent({ contacts: [{ id: 1, name: "Bea" }, { id: 2, name: "anna" }, { id: 3, name: "Ben" }] });\nassertEqual(screen.getAllByRole("heading").map((h) => h.textContent), ["A", "B"]);`),
        hidden("sorts names within groups", `const { container } = renderComponent({ contacts: [{ id: 1, name: "Zed" }, { id: 2, name: "Carl" }, { id: 3, name: "Cara" }, { id: 4, name: "Abe" }] });\nconst lists = Array.from(container.querySelectorAll("ul")).map((ul) => Array.from(ul.children).map((li) => li.textContent));\nassertEqual(lists, [["Abe"], ["Cara", "Carl"], ["Zed"]]);`),
      ],
    },
  ],
};
