import { hidden, test, type CategoryBank } from "./types.js";

export const events: CategoryBank = {
  category: "Events",
  level: 7,
  type: "COMPONENT",
  prerequisites: ["Props"],
  problems: [
    {
      slug: "events-log-click",
      title: "Handle a Button Click",
      difficulty: "BEGINNER",
      tags: ["events", "onClick"],
      estimatedMinutes: 5,
      description:
        "Make `LogButton` render a button `Click me`. When it's clicked, call `console.log(\"Button clicked!\")`.\n\nDefine a `handleClick` function inside the component and pass it to `onClick`.",
      requirements: ["Logs 'Button clicked!' once per click", "Does not log while rendering"],
      hints: ["function handleClick() { console.log(\"Button clicked!\"); }", "<button onClick={handleClick}> — no parentheses after handleClick."],
      starterCode: `function LogButton() {\n  // Write your solution here\n  return null;\n}\n\nexport default LogButton;\n`,
      solutionCode: `function LogButton() {\n  function handleClick() {\n    console.log("Button clicked!");\n  }\n\n  return <button onClick={handleClick}>Click me</button>;\n}\n\nexport default LogButton;\n`,
      explanation: "React calls the function you pass to onClick when the click happens. Passing handleClick() would call it immediately during render instead.",
      commonMistakes: ["onClick={handleClick()} — runs on render, not on click."],
      tests: [
        test("logs on click", `const logs = [];\nconst original = console.log;\nconsole.log = (...args) => logs.push(args.join(" "));\ntry {\n  renderComponent();\n  fireEvent.click(screen.getByRole("button", { name: "Click me" }));\n} finally {\n  console.log = original;\n}\nassertEqual(logs, ["Button clicked!"]);`),
        hidden("does not log on render and logs per click", `const logs = [];\nconst original = console.log;\nconsole.log = (...args) => logs.push(args.join(" "));\ntry {\n  renderComponent();\n  assertEqual(logs.length, 0, "Something was logged before any click");\n  fireEvent.click(screen.getByRole("button"));\n  fireEvent.click(screen.getByRole("button"));\n} finally {\n  console.log = original;\n}\nassertEqual(logs.length, 2);`),
      ],
      wrongSolutions: [`function LogButton() {\n  function handleClick() { console.log("Button clicked!"); }\n  return <button onClick={handleClick()}>Click me</button>;\n}\n\nexport default LogButton;\n`],
    },
    {
      slug: "events-handler-uses-props",
      title: "Event Handlers Can Read Props",
      difficulty: "BEGINNER",
      tags: ["events", "props"],
      estimatedMinutes: 5,
      description: "Make `SayHello` accept `name` and `onSay`. Render a button `Say hello`; clicking it calls `onSay` with the string `Hello, {name}!`.",
      requirements: ["Calls onSay with a greeting built from the name prop"],
      hints: ["Handlers defined inside the component can see its props.", "onSay(`Hello, ${name}!`)"],
      starterCode: `interface SayHelloProps {\n  name: string;\n  onSay: (message: string) => void;\n}\n\nfunction SayHello(props: SayHelloProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default SayHello;\n`,
      solutionCode: `interface SayHelloProps {\n  name: string;\n  onSay: (message: string) => void;\n}\n\nfunction SayHello({ name, onSay }: SayHelloProps) {\n  function handleClick() {\n    onSay(\`Hello, \${name}!\`);\n  }\n  return <button onClick={handleClick}>Say hello</button>;\n}\n\nexport default SayHello;\n`,
      explanation: "Handlers are closures: they can use any variable in scope when they were created, including props.",
      tests: [
        test("greets by name", `const onSay = mockFn();\nrenderComponent({ name: "Zoe", onSay });\nfireEvent.click(screen.getByRole("button", { name: "Say hello" }));\nassertEqual(onSay.calls, [["Hello, Zoe!"]]);`),
        hidden("uses the current name", `const onSay = mockFn();\nrenderComponent({ name: "Omar", onSay });\nfireEvent.click(screen.getByRole("button"));\nassertEqual(onSay.calls, [["Hello, Omar!"]]);`),
      ],
      wrongSolutions: [`function SayHello({ onSay }) {\n  return <button onClick={() => onSay("Hello, Zoe!")}>Say hello</button>;\n}\n\nexport default SayHello;\n`],
    },
    {
      slug: "events-read-target",
      title: "Read the Event Target",
      difficulty: "BEGINNER",
      tags: ["events", "onChange", "event-object"],
      estimatedMinutes: 5,
      description:
        "Make `NameInput` render an input with placeholder `Your name`. Every time it changes, call `onNameChange` with the input's current text.\n\nThe handler receives an **event object**; the text is at `event.target.value`.",
      requirements: ["Calls onNameChange with the current value on every change"],
      hints: ["onChange={(event) => ...}", "event.target.value holds the text."],
      starterCode: `import type { ChangeEvent } from "react";\n\nfunction NameInput(props: { onNameChange: (name: string) => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default NameInput;\n`,
      solutionCode: `import type { ChangeEvent } from "react";\n\nfunction NameInput({ onNameChange }: { onNameChange: (name: string) => void }) {\n  function handleChange(event: ChangeEvent<HTMLInputElement>) {\n    onNameChange(event.target.value);\n  }\n  return <input placeholder="Your name" onChange={handleChange} />;\n}\n\nexport default NameInput;\n`,
      explanation: "Every handler receives a synthetic event object describing what happened. For inputs, event.target is the input element itself.",
      tests: [
        test("reports the value", `const onNameChange = mockFn();\nrenderComponent({ onNameChange });\nfireEvent.change(screen.getByPlaceholderText("Your name"), { target: { value: "Rae" } });\nassertEqual(onNameChange.calls, [["Rae"]]);`),
        hidden("reports every keystroke", `const onNameChange = mockFn();\nrenderComponent({ onNameChange });\nawait userEvent.type(screen.getByPlaceholderText("Your name"), "Al");\nassertEqual(onNameChange.calls, [["A"], ["Al"]]);`),
      ],
    },
    {
      slug: "events-double-click",
      title: "Detect a Double Click",
      difficulty: "BEGINNER",
      tags: ["events", "onDoubleClick"],
      estimatedMinutes: 5,
      description: "Make `PhotoTile` render `<img alt=\"Photo\" src=\"/photo.jpg\" />`. Double-clicking the image calls `onLike()`. A single click must **not** call it.",
      requirements: ["onLike called on double click", "Not called on single click"],
      hints: ["React has an onDoubleClick event.", "<img onDoubleClick={onLike} ... />"],
      starterCode: `function PhotoTile(props: { onLike: () => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default PhotoTile;\n`,
      solutionCode: `function PhotoTile({ onLike }: { onLike: () => void }) {\n  return <img alt="Photo" src="/photo.jpg" onDoubleClick={onLike} />;\n}\n\nexport default PhotoTile;\n`,
      explanation: "React exposes most DOM events as camelCase props: onClick, onDoubleClick, onMouseEnter, onKeyDown...",
      tests: [
        test("likes on double click", `const onLike = mockFn();\nrenderComponent({ onLike });\nfireEvent.doubleClick(screen.getByRole("img", { name: "Photo" }));\nassertEqual(onLike.calls.length, 1);`),
        hidden("ignores single clicks", `const onLike = mockFn();\nrenderComponent({ onLike });\nfireEvent.click(screen.getByRole("img"));\nassertEqual(onLike.calls.length, 0);`),
      ],
      wrongSolutions: [`function PhotoTile({ onLike }) {\n  return <img alt="Photo" src="/photo.jpg" onClick={onLike} onDoubleClick={onLike} />;\n}\n\nexport default PhotoTile;\n`],
    },
    {
      slug: "events-hover",
      title: "Handle Mouse Enter and Leave",
      difficulty: "BEGINNER",
      tags: ["events", "mouse"],
      estimatedMinutes: 5,
      description: "Make `HoverCard` render `<div>Hover me</div>`. Call `onHoverChange(true)` when the mouse enters it and `onHoverChange(false)` when it leaves.",
      requirements: ["true on enter", "false on leave"],
      hints: ["Use onMouseEnter and onMouseLeave.", "Wrap each call in an arrow function to pass the boolean."],
      starterCode: `function HoverCard(props: { onHoverChange: (hovering: boolean) => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default HoverCard;\n`,
      solutionCode: `function HoverCard({ onHoverChange }: { onHoverChange: (hovering: boolean) => void }) {\n  return (\n    <div onMouseEnter={() => onHoverChange(true)} onMouseLeave={() => onHoverChange(false)}>\n      Hover me\n    </div>\n  );\n}\n\nexport default HoverCard;\n`,
      explanation: "onMouseEnter/onMouseLeave don't bubble from children the way mouseover/mouseout do, so they're the right choice for hover effects.",
      tests: [
        test("reports enter", `const onHoverChange = mockFn();\nrenderComponent({ onHoverChange });\nfireEvent.mouseEnter(expectText("Hover me"));\nassertEqual(onHoverChange.calls, [[true]]);`),
        hidden("reports leave", `const onHoverChange = mockFn();\nrenderComponent({ onHoverChange });\nfireEvent.mouseEnter(expectText("Hover me"));\nfireEvent.mouseLeave(expectText("Hover me"));\nassertEqual(onHoverChange.calls, [[true], [false]]);`),
      ],
    },
    {
      slug: "events-enter-key",
      title: "Detect the Enter Key",
      difficulty: "EASY",
      tags: ["events", "keyboard"],
      estimatedMinutes: 8,
      description:
        "Make `QuickSearch` render an input with placeholder `Search`. When the user presses **Enter**, call `onSearch` with the input's current value. Other keys do nothing.",
      requirements: ["Enter calls onSearch(value)", "Other keys don't"],
      hints: ["onKeyDown receives a KeyboardEvent with a `key` property.", "if (event.key === \"Enter\") onSearch(event.currentTarget.value);"],
      starterCode: `import type { KeyboardEvent } from "react";\n\nfunction QuickSearch(props: { onSearch: (query: string) => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default QuickSearch;\n`,
      solutionCode: `import type { KeyboardEvent } from "react";\n\nfunction QuickSearch({ onSearch }: { onSearch: (query: string) => void }) {\n  function handleKeyDown(event: KeyboardEvent<HTMLInputElement>) {\n    if (event.key === "Enter") {\n      onSearch(event.currentTarget.value);\n    }\n  }\n  return <input placeholder="Search" onKeyDown={handleKeyDown} />;\n}\n\nexport default QuickSearch;\n`,
      explanation: "event.key holds a readable key name ('Enter', 'Escape', 'a'). currentTarget is the element the handler is attached to.",
      tests: [
        test("searches on Enter", `const onSearch = mockFn();\nrenderComponent({ onSearch });\nconst input = screen.getByPlaceholderText("Search");\nawait userEvent.type(input, "lamps{Enter}");\nassertEqual(onSearch.calls, [["lamps"]]);`),
        hidden("ignores other keys", `const onSearch = mockFn();\nrenderComponent({ onSearch });\nawait userEvent.type(screen.getByPlaceholderText("Search"), "abc");\nassertEqual(onSearch.calls.length, 0);`),
      ],
      wrongSolutions: [`function QuickSearch({ onSearch }) {\n  return <input placeholder="Search" onKeyDown={(e) => onSearch(e.currentTarget.value)} />;\n}\n\nexport default QuickSearch;\n`],
    },
    {
      slug: "events-escape-key",
      title: "Cancel With the Escape Key",
      difficulty: "BEGINNER",
      tags: ["events", "keyboard"],
      estimatedMinutes: 5,
      description: "Make `EditField` render an input with `aria-label=\"Title\"`. Pressing **Escape** in the input calls `onCancel()`.",
      requirements: ["Escape calls onCancel", "Other keys don't"],
      hints: ["The key name is \"Escape\".", "onKeyDown={(e) => { if (e.key === \"Escape\") onCancel(); }}"],
      starterCode: `function EditField(props: { onCancel: () => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default EditField;\n`,
      solutionCode: `function EditField({ onCancel }: { onCancel: () => void }) {\n  return (\n    <input\n      aria-label="Title"\n      onKeyDown={(event) => {\n        if (event.key === "Escape") onCancel();\n      }}\n    />\n  );\n}\n\nexport default EditField;\n`,
      explanation: "Escape-to-cancel is an expected keyboard convention for edit fields, menus, and dialogs.",
      tests: [
        test("Escape cancels", `const onCancel = mockFn();\nrenderComponent({ onCancel });\nfireEvent.keyDown(screen.getByLabelText("Title"), { key: "Escape" });\nassertEqual(onCancel.calls.length, 1);`),
        hidden("other keys do nothing", `const onCancel = mockFn();\nrenderComponent({ onCancel });\nfireEvent.keyDown(screen.getByLabelText("Title"), { key: "Enter" });\nfireEvent.keyDown(screen.getByLabelText("Title"), { key: "a" });\nassertEqual(onCancel.calls.length, 0);`),
      ],
    },
    {
      slug: "events-prevent-default-form",
      title: "Prevent Default Form Submission",
      difficulty: "EASY",
      tags: ["events", "forms", "preventDefault"],
      estimatedMinutes: 10,
      description:
        "Make `NewsletterForm` render a `<form>` containing an input `name=\"email\"` labelled `Email`, and a submit button `Subscribe`.\n\nOn submit:\n1. call `event.preventDefault()` so the browser doesn't reload the page\n2. call `onSubscribe` with the email value\n\nRead the value from the form with `new FormData(event.currentTarget).get(\"email\")` — no state needed.",
      requirements: ["Handles onSubmit on the form", "Prevents the default page reload", "Calls onSubscribe with the typed email"],
      hints: ["Attach the handler to the <form>'s onSubmit, not to the button.", "FormData reads named inputs from a form element."],
      starterCode: `import type { FormEvent } from "react";\n\nfunction NewsletterForm(props: { onSubscribe: (email: string) => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default NewsletterForm;\n`,
      solutionCode: `import type { FormEvent } from "react";\n\nfunction NewsletterForm({ onSubscribe }: { onSubscribe: (email: string) => void }) {\n  function handleSubmit(event: FormEvent<HTMLFormElement>) {\n    event.preventDefault();\n    const data = new FormData(event.currentTarget);\n    onSubscribe(String(data.get("email")));\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <label htmlFor="email">Email</label>\n      <input id="email" name="email" type="email" />\n      <button type="submit">Subscribe</button>\n    </form>\n  );\n}\n\nexport default NewsletterForm;\n`,
      explanation: "Handling onSubmit covers both clicking the button and pressing Enter in a field. preventDefault stops the browser's default full-page form submission.",
      commonMistakes: ["Using onClick on the submit button misses Enter-key submissions."],
      tests: [
        test("calls onSubscribe with the email", `const onSubscribe = mockFn();\nrenderComponent({ onSubscribe });\nawait userEvent.type(screen.getByLabelText("Email"), "me@site.io");\nfireEvent.click(screen.getByRole("button", { name: "Subscribe" }));\nassertEqual(onSubscribe.calls, [["me@site.io"]]);`),
        hidden("prevents the default submission", `renderComponent({ onSubscribe: () => {} });\nconst form = screen.getByRole("button", { name: "Subscribe" }).closest("form");\nconst notPrevented = fireEvent.submit(form);\nassert(!notPrevented, "Call event.preventDefault() in the submit handler");`),
      ],
    },
    {
      slug: "events-prevent-default-link",
      title: "Intercept a Link Click",
      difficulty: "EASY",
      tags: ["events", "preventDefault", "navigation"],
      estimatedMinutes: 8,
      description:
        "Client-side routers intercept link clicks. Make `AppLink` accept `to`, `children`, and `onNavigate`. Render `<a href={to}>`. On click, prevent the browser's navigation and call `onNavigate(to)` instead.",
      requirements: ["Renders a real link with href", "Click is prevented", "onNavigate receives the target path"],
      hints: ["Keep the href so the link still works for 'open in new tab'.", "event.preventDefault(); onNavigate(to);"],
      starterCode: `import type { ReactNode } from "react";\n\ninterface AppLinkProps {\n  to: string;\n  children: ReactNode;\n  onNavigate: (to: string) => void;\n}\n\nfunction AppLink(props: AppLinkProps) {\n  // Write your solution here\n  return null;\n}\n\nexport default AppLink;\n`,
      solutionCode: `import type { MouseEvent, ReactNode } from "react";\n\ninterface AppLinkProps {\n  to: string;\n  children: ReactNode;\n  onNavigate: (to: string) => void;\n}\n\nfunction AppLink({ to, children, onNavigate }: AppLinkProps) {\n  function handleClick(event: MouseEvent<HTMLAnchorElement>) {\n    event.preventDefault();\n    onNavigate(to);\n  }\n  return (\n    <a href={to} onClick={handleClick}>\n      {children}\n    </a>\n  );\n}\n\nexport default AppLink;\n`,
      explanation: "This is the core of how React Router's <Link> works: a real anchor for accessibility, with the click intercepted to update the URL without a reload.",
      tests: [
        test("calls onNavigate", `const onNavigate = mockFn();\nrender(<Component to="/about" onNavigate={onNavigate}>About</Component>);\nfireEvent.click(screen.getByRole("link", { name: "About" }));\nassertEqual(onNavigate.calls, [["/about"]]);`),
        hidden("prevents default and keeps href", `render(<Component to="/pricing" onNavigate={() => {}}>Pricing</Component>);\nconst link = screen.getByRole("link", { name: "Pricing" });\nassertEqual(link.getAttribute("href"), "/pricing");\nassert(!fireEvent.click(link), "The click's default navigation should be prevented");`),
      ],
    },
    {
      slug: "events-stop-propagation",
      title: "Stop Event Propagation",
      difficulty: "EASY",
      tags: ["events", "propagation"],
      estimatedMinutes: 10,
      description:
        "Make `FileCard` render a `<div role=\"button\" tabIndex={0}>` containing the text `report.pdf` and a nested `<button>Delete</button>`.\n\n- Clicking the card calls `onOpen()`.\n- Clicking **Delete** calls `onDelete()` — and must **not** also open the file.\n\nEvents bubble from the button up to the card, so stop the propagation.",
      requirements: ["Card click opens", "Delete click deletes without opening"],
      hints: ["Clicks bubble up through every ancestor's onClick.", "In the Delete handler: event.stopPropagation();"],
      starterCode: `function FileCard(props: { onOpen: () => void; onDelete: () => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default FileCard;\n`,
      solutionCode: `import type { MouseEvent } from "react";\n\nfunction FileCard({ onOpen, onDelete }: { onOpen: () => void; onDelete: () => void }) {\n  function handleDelete(event: MouseEvent<HTMLButtonElement>) {\n    event.stopPropagation();\n    onDelete();\n  }\n\n  return (\n    <div role="button" tabIndex={0} onClick={onOpen}>\n      report.pdf\n      <button onClick={handleDelete}>Delete</button>\n    </div>\n  );\n}\n\nexport default FileCard;\n`,
      explanation: "Events bubble from the innermost element outward. stopPropagation ends that journey, so ancestor handlers don't run.",
      tests: [
        test("card click opens", `const onOpen = mockFn();\nconst onDelete = mockFn();\nrenderComponent({ onOpen, onDelete });\nfireEvent.click(screen.getByText("report.pdf", { exact: false }));\nassertEqual(onOpen.calls.length, 1);`),
        hidden("delete does not open", `const onOpen = mockFn();\nconst onDelete = mockFn();\nrenderComponent({ onOpen, onDelete });\nfireEvent.click(screen.getByRole("button", { name: "Delete" }));\nassertEqual(onDelete.calls.length, 1);\nassertEqual(onOpen.calls.length, 0, "Clicking Delete also triggered onOpen");`),
      ],
      wrongSolutions: [`function FileCard({ onOpen, onDelete }) {\n  return (<div role="button" tabIndex={0} onClick={onOpen}>report.pdf<button onClick={onDelete}>Delete</button></div>);\n}\n\nexport default FileCard;\n`],
    },
    {
      slug: "events-which-button",
      title: "One Handler for Many Buttons",
      difficulty: "EASY",
      tags: ["events", "event-object", "data-attributes"],
      estimatedMinutes: 10,
      description:
        "Make `FormatToolbar` render three buttons, `Bold`, `Italic`, and `Underline`, with `data-action` attributes `bold`, `italic`, and `underline`.\n\nUse **one** handler for all three. It reads `event.currentTarget.dataset.action` and calls `onAction` with it.",
      requirements: ["Each button reports its own action", "A single shared handler function"],
      hints: ["data-* attributes appear on element.dataset.", "currentTarget is the element the handler is attached to (the button)."],
      starterCode: `function FormatToolbar(props: { onAction: (action: string) => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default FormatToolbar;\n`,
      solutionCode: `import type { MouseEvent } from "react";\n\nfunction FormatToolbar({ onAction }: { onAction: (action: string) => void }) {\n  function handleClick(event: MouseEvent<HTMLButtonElement>) {\n    onAction(event.currentTarget.dataset.action ?? "");\n  }\n\n  return (\n    <div>\n      <button data-action="bold" onClick={handleClick}>Bold</button>\n      <button data-action="italic" onClick={handleClick}>Italic</button>\n      <button data-action="underline" onClick={handleClick}>Underline</button>\n    </div>\n  );\n}\n\nexport default FormatToolbar;\n`,
      explanation: "When many elements need the same handler, put the varying data on the element (data-* attributes) and read it from the event.",
      alternativeApproach: "Inline arrows like onClick={() => onAction(\"bold\")} are equally fine for a handful of buttons.",
      tests: [
        test("reports bold", `const onAction = mockFn();\nrenderComponent({ onAction });\nfireEvent.click(screen.getByRole("button", { name: "Bold" }));\nassertEqual(onAction.calls, [["bold"]]);`),
        hidden("reports each action", `const onAction = mockFn();\nrenderComponent({ onAction });\nfireEvent.click(screen.getByRole("button", { name: "Underline" }));\nfireEvent.click(screen.getByRole("button", { name: "Italic" }));\nassertEqual(onAction.calls, [["underline"], ["italic"]]);\nassertEqual(screen.getByRole("button", { name: "Italic" }).dataset.action, "italic");`),
      ],
    },
    {
      slug: "events-focus-blur",
      title: "Track Focus and Blur",
      difficulty: "BEGINNER",
      tags: ["events", "focus"],
      estimatedMinutes: 5,
      description: "Make `FocusInput` render an input with `aria-label=\"Username\"`. Call `onFocusChange(true)` when it gains focus and `onFocusChange(false)` when it loses focus.",
      requirements: ["true on focus", "false on blur"],
      hints: ["onFocus and onBlur.", "Wrap each in an arrow function to pass the boolean."],
      starterCode: `function FocusInput(props: { onFocusChange: (focused: boolean) => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default FocusInput;\n`,
      solutionCode: `function FocusInput({ onFocusChange }: { onFocusChange: (focused: boolean) => void }) {\n  return <input aria-label="Username" onFocus={() => onFocusChange(true)} onBlur={() => onFocusChange(false)} />;\n}\n\nexport default FocusInput;\n`,
      explanation: "Focus events power things like 'show help text while typing' and 'validate when the user leaves a field'.",
      tests: [
        test("focus", `const onFocusChange = mockFn();\nrenderComponent({ onFocusChange });\nscreen.getByLabelText("Username").focus();\nassertEqual(onFocusChange.calls, [[true]]);`),
        hidden("blur", `const onFocusChange = mockFn();\nrenderComponent({ onFocusChange });\nconst input = screen.getByLabelText("Username");\ninput.focus();\ninput.blur();\nassertEqual(onFocusChange.calls, [[true], [false]]);`),
      ],
    },
    {
      slug: "events-checkbox",
      title: "Read a Checkbox Change",
      difficulty: "BEGINNER",
      tags: ["events", "forms", "checkbox"],
      estimatedMinutes: 5,
      description: "Make `TermsCheckbox` render a checkbox labelled `I accept the terms`. When it changes, call `onToggle` with whether it is now checked.\n\nFor checkboxes the value is at `event.target.checked`, not `.value`.",
      requirements: ["Reports true when checked", "Reports false when unchecked"],
      hints: ["Wrap the input in a <label> to label it.", "onChange={(e) => onToggle(e.target.checked)}"],
      starterCode: `function TermsCheckbox(props: { onToggle: (checked: boolean) => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default TermsCheckbox;\n`,
      solutionCode: `function TermsCheckbox({ onToggle }: { onToggle: (checked: boolean) => void }) {\n  return (\n    <label>\n      <input type="checkbox" onChange={(event) => onToggle(event.target.checked)} />\n      I accept the terms\n    </label>\n  );\n}\n\nexport default TermsCheckbox;\n`,
      explanation: "Checkboxes and radios expose `checked`; text inputs and selects expose `value`.",
      commonMistakes: ["Reading event.target.value on a checkbox gives 'on' regardless of state."],
      tests: [
        test("reports checked", `const onToggle = mockFn();\nrenderComponent({ onToggle });\nfireEvent.click(screen.getByRole("checkbox", { name: "I accept the terms" }));\nassertEqual(onToggle.calls, [[true]]);`),
        hidden("reports unchecked", `const onToggle = mockFn();\nrenderComponent({ onToggle });\nconst box = screen.getByRole("checkbox");\nfireEvent.click(box);\nfireEvent.click(box);\nassertEqual(onToggle.calls, [[true], [false]]);`),
      ],
      wrongSolutions: [`function TermsCheckbox({ onToggle }) {\n  return (<label><input type="checkbox" onChange={(e) => onToggle(e.target.value)} />I accept the terms</label>);\n}\n\nexport default TermsCheckbox;\n`],
    },
    {
      slug: "events-select",
      title: "Read a Select Change",
      difficulty: "BEGINNER",
      tags: ["events", "forms", "select"],
      estimatedMinutes: 5,
      description:
        "Make `SizeSelect` render a `<select>` labelled `Size` with options `Small` (value `s`), `Medium` (`m`), and `Large` (`l`). When the selection changes, call `onSizeChange` with the option's **value**.",
      requirements: ["Three options with the right values", "Reports the selected value"],
      hints: ["<option value=\"s\">Small</option>", "onChange={(e) => onSizeChange(e.target.value)}"],
      starterCode: `function SizeSelect(props: { onSizeChange: (size: string) => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default SizeSelect;\n`,
      solutionCode: `function SizeSelect({ onSizeChange }: { onSizeChange: (size: string) => void }) {\n  return (\n    <label>\n      Size\n      <select onChange={(event) => onSizeChange(event.target.value)}>\n        <option value="s">Small</option>\n        <option value="m">Medium</option>\n        <option value="l">Large</option>\n      </select>\n    </label>\n  );\n}\n\nexport default SizeSelect;\n`,
      explanation: "A select's value is the value attribute of the chosen option, not its visible text.",
      tests: [
        test("reports the value", `const onSizeChange = mockFn();\nrenderComponent({ onSizeChange });\nawait userEvent.selectOptions(screen.getByLabelText("Size"), "Large");\nassertEqual(onSizeChange.calls, [["l"]]);`),
        hidden("has the three options", `renderComponent({ onSizeChange: () => {} });\nassertEqual(screen.getAllByRole("option").map((o) => o.value), ["s", "m", "l"]);`),
      ],
    },
    {
      slug: "events-arrow-keys",
      title: "Keyboard Navigation With Arrow Keys",
      difficulty: "EASY",
      tags: ["events", "keyboard", "accessibility"],
      estimatedMinutes: 10,
      description:
        "Make `VolumeKnob` render a focusable `<div tabIndex={0} aria-label=\"Volume\">`. On keydown:\n\n- `ArrowUp` or `ArrowRight` → `onStep(1)`\n- `ArrowDown` or `ArrowLeft` → `onStep(-1)`\n\nCall `event.preventDefault()` for these keys so the page doesn't scroll.",
      requirements: ["Up/Right step +1", "Down/Left step -1", "Default prevented for arrow keys"],
      hints: ["A switch on event.key keeps this tidy.", "tabIndex={0} makes a div reachable with Tab."],
      starterCode: `function VolumeKnob(props: { onStep: (delta: number) => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default VolumeKnob;\n`,
      solutionCode: `import type { KeyboardEvent } from "react";\n\nfunction VolumeKnob({ onStep }: { onStep: (delta: number) => void }) {\n  function handleKeyDown(event: KeyboardEvent<HTMLDivElement>) {\n    switch (event.key) {\n      case "ArrowUp":\n      case "ArrowRight":\n        event.preventDefault();\n        onStep(1);\n        break;\n      case "ArrowDown":\n      case "ArrowLeft":\n        event.preventDefault();\n        onStep(-1);\n        break;\n    }\n  }\n\n  return (\n    <div tabIndex={0} aria-label="Volume" onKeyDown={handleKeyDown}>\n      🔊\n    </div>\n  );\n}\n\nexport default VolumeKnob;\n`,
      explanation: "Custom widgets must support the keyboard. Arrow keys are the convention for adjusting values, and preventDefault stops them scrolling the page.",
      tests: [
        test("arrow up steps up", `const onStep = mockFn();\nrenderComponent({ onStep });\nfireEvent.keyDown(screen.getByLabelText("Volume"), { key: "ArrowUp" });\nassertEqual(onStep.calls, [[1]]);`),
        hidden("all four arrows and preventDefault", `const onStep = mockFn();\nrenderComponent({ onStep });\nconst knob = screen.getByLabelText("Volume");\nfireEvent.keyDown(knob, { key: "ArrowRight" });\nfireEvent.keyDown(knob, { key: "ArrowDown" });\nconst notPrevented = fireEvent.keyDown(knob, { key: "ArrowLeft" });\nfireEvent.keyDown(knob, { key: "Tab" });\nassertEqual(onStep.calls, [[1], [-1], [-1]]);\nassert(!notPrevented, "Arrow keys should call preventDefault");`),
      ],
    },
    {
      slug: "events-paste",
      title: "Handle a Paste Event",
      difficulty: "EASY",
      tags: ["events", "clipboard"],
      estimatedMinutes: 8,
      description:
        "Make `CodeInput` render a textarea labelled `Code`. When text is pasted into it, call `onPaste` with the pasted text, **trimmed**.\n\nPasted text is available via `event.clipboardData.getData(\"text\")`.",
      requirements: ["Calls onPaste with the trimmed pasted text"],
      hints: ["React has an onPaste event.", "event.clipboardData.getData(\"text\").trim()"],
      starterCode: `function CodeInput(props: { onPaste: (text: string) => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default CodeInput;\n`,
      solutionCode: `function CodeInput({ onPaste }: { onPaste: (text: string) => void }) {\n  return (\n    <label>\n      Code\n      <textarea onPaste={(event) => onPaste(event.clipboardData.getData("text").trim())} />\n    </label>\n  );\n}\n\nexport default CodeInput;\n`,
      explanation: "Clipboard events expose a clipboardData object. Handling paste lets you clean up or validate input as it arrives.",
      tests: [
        test("reports pasted text", `const onPaste = mockFn();\nrenderComponent({ onPaste });\nfireEvent.paste(screen.getByLabelText("Code"), { clipboardData: { getData: () => "ABC-123" } });\nassertEqual(onPaste.calls, [["ABC-123"]]);`),
        hidden("trims whitespace", `const onPaste = mockFn();\nrenderComponent({ onPaste });\nfireEvent.paste(screen.getByLabelText("Code"), { clipboardData: { getData: () => "  xyz \\n" } });\nassertEqual(onPaste.calls, [["xyz"]]);`),
      ],
    },
    {
      slug: "events-delegation",
      title: "Event Delegation on a List",
      difficulty: "MEDIUM",
      tags: ["events", "delegation", "lists"],
      estimatedMinutes: 12,
      description:
        "Make `ColorPicker` accept `colors` (strings) and `onSelect`. Render a `<ul>` with one `<li data-color={color}>` per color.\n\nAttach **one** `onClick` handler to the `<ul>` (not one per `<li>`). In it, find the clicked item with `(event.target as HTMLElement).closest(\"li\")` and call `onSelect` with its `data-color`. Clicks on the list's padding (not on an item) do nothing.",
      requirements: ["Single click handler on the <ul>", "Reports the clicked item's color", "Ignores clicks outside items"],
      hints: ["event.target is what was actually clicked; currentTarget is the <ul>.", "closest(\"li\") walks up from the target to the nearest <li>.", "If closest returns null, do nothing."],
      starterCode: `function ColorPicker(props: { colors: string[]; onSelect: (color: string) => void }) {\n  // Write your solution here\n  return null;\n}\n\nexport default ColorPicker;\n`,
      solutionCode: `import type { MouseEvent } from "react";\n\nfunction ColorPicker({ colors, onSelect }: { colors: string[]; onSelect: (color: string) => void }) {\n  function handleClick(event: MouseEvent<HTMLUListElement>) {\n    const item = (event.target as HTMLElement).closest("li");\n    if (item?.dataset.color) onSelect(item.dataset.color);\n  }\n\n  return (\n    <ul onClick={handleClick}>\n      {colors.map((color) => (\n        <li key={color} data-color={color}>\n          <span>{color}</span>\n        </li>\n      ))}\n    </ul>\n  );\n}\n\nexport default ColorPicker;\n`,
      explanation: "Delegation uses bubbling: one ancestor handler serves every child. React already delegates internally, so in React this is mostly about understanding target vs currentTarget.",
      tests: [
        test("reports clicked color", `const onSelect = mockFn();\nrenderComponent({ colors: ["red", "blue"], onSelect });\nfireEvent.click(expectText("blue"));\nassertEqual(onSelect.calls, [["blue"]]);`),
        hidden("ignores clicks on the list itself", `const onSelect = mockFn();\nrenderComponent({ colors: ["red"], onSelect });\nfireEvent.click(screen.getByRole("list"));\nassertEqual(onSelect.calls.length, 0);\nfireEvent.click(screen.getByRole("listitem"));\nassertEqual(onSelect.calls, [["red"]]);`),
      ],
    },
  ],
};
