import { hidden, stub, test, type CategoryBank } from "./types.js";

const useStateStub = (name: string, params = "") => stub(name, { imports: `import { useState } from "react";`, params });
const click = (name: string) => `fireEvent.click(screen.getByRole("button", { name: ${JSON.stringify(name)} }));`;
const items = `screen.getAllByRole("listitem").map((el) => el.textContent)`;

export const useStateBank: CategoryBank = {
  category: "useState",
  level: 8,
  type: "HOOK",
  prerequisites: ["Components", "Events"],
  problems: [
    {
      slug: "state-change-message",
      title: "Your First State Variable",
      difficulty: "BEGINNER",
      tags: ["useState", "state"],
      estimatedMinutes: 5,
      description:
        "Until now, components only showed what their props told them. **State** lets a component remember something and change it.\n\nMake `Message` show `<p>Hello</p>` and a button `Change`. Clicking the button changes the text to `Goodbye`.\n\n```\nconst [message, setMessage] = useState(\"Hello\");\n```",
      requirements: ["Starts with 'Hello'", "Shows 'Goodbye' after clicking Change"],
      hints: ["useState returns the current value and a function to change it.", "Call setMessage(\"Goodbye\") in the click handler.", "Calling the setter makes React re-render with the new value."],
      starterCode: useStateStub("Message"),
      solutionCode: `import { useState } from "react";\n\nfunction Message() {\n  const [message, setMessage] = useState("Hello");\n\n  return (\n    <div>\n      <p>{message}</p>\n      <button onClick={() => setMessage("Goodbye")}>Change</button>\n    </div>\n  );\n}\n\nexport default Message;\n`,
      explanation: "A normal variable resets on every render, and changing it doesn't trigger one. State survives between renders, and setting it tells React to render again.",
      commonMistakes: ["Using `let message = \"Hello\"` and reassigning it: the screen never updates."],
      tests: [
        test("starts with Hello", `renderComponent();\nexpectText("Hello");`),
        hidden("changes to Goodbye", `renderComponent();\n${click("Change")}\nexpectText("Goodbye");\nexpectNoText("Hello");`),
      ],
      wrongSolutions: [`function Message() {\n  let message = "Hello";\n  return (<div><p>{message}</p><button onClick={() => { message = "Goodbye"; }}>Change</button></div>);\n}\n\nexport default Message;\n`],
    },
    {
      slug: "build-a-counter",
      title: "Build a Counter",
      difficulty: "BEGINNER",
      tags: ["useState", "events"],
      estimatedMinutes: 10,
      description:
        "Create a counter that starts at 0. Render a `-` button, the current count, and a `+` button. Clicking `+` increments the count; clicking `-` decrements it (negative numbers are fine).",
      requirements: ["Initial value is 0", "'+' increments", "'-' decrements", "Multiple clicks accumulate"],
      hints: ["You need a state variable for the count.", "useState(0)", "Use the updater form: setCount((c) => c + 1)"],
      starterCode: useStateStub("Counter"),
      solutionCode: `import { useState } from "react";\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      <button onClick={() => setCount((c) => c - 1)}>-</button>\n      <span>{count}</span>\n      <button onClick={() => setCount((c) => c + 1)}>+</button>\n    </div>\n  );\n}\n\nexport default Counter;\n`,
      explanation: "useState(0) gives the component memory that survives re-renders. The updater form (c => c + 1) always starts from the latest value.",
      tests: [
        test("starts at 0", `renderComponent();\nexpectText("0");`),
        test("increments", `renderComponent();\n${click("+")}\nexpectText("1");`),
        hidden("decrements below zero", `renderComponent();\n${click("-")}\nexpectText("-1");`),
        hidden("handles many clicks", `renderComponent();\nfor (let i = 0; i < 5; i++) { ${click("+")} }\n${click("-")}\nexpectText("4");`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  return (<div><button>-</button><span>{count}</span><button onClick={() => setCount(count + 1)}>+</button></div>);\n}\nexport default Counter;\n`],
    },
    {
      slug: "state-counter-reset",
      title: "Counter With Reset",
      difficulty: "BEGINNER",
      tags: ["useState"],
      estimatedMinutes: 5,
      description: "Make `ResettableCounter` render `<p>Count: {count}</p>`, a button `Add`, and a button `Reset`. Add increments by 1; Reset sets the count back to 0.",
      requirements: ["Add increments", "Reset returns to 0"],
      hints: ["Reset is just setCount(0).", "Two buttons, two handlers, one piece of state."],
      starterCode: useStateStub("ResettableCounter"),
      solutionCode: `import { useState } from "react";\n\nfunction ResettableCounter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount((c) => c + 1)}>Add</button>\n      <button onClick={() => setCount(0)}>Reset</button>\n    </div>\n  );\n}\n\nexport default ResettableCounter;\n`,
      explanation: "Setting state to a fixed value is as simple as calling the setter with that value.",
      tests: [
        test("adds", `renderComponent();\n${click("Add")}\n${click("Add")}\nexpectText("Count: 2");`),
        hidden("resets", `renderComponent();\n${click("Add")}\n${click("Add")}\n${click("Reset")}\nexpectText("Count: 0");\n${click("Add")}\nexpectText("Count: 1");`),
      ],
    },
    {
      slug: "state-counter-bounds",
      title: "Counter With Limits",
      difficulty: "EASY",
      tags: ["useState", "derived-state"],
      estimatedMinutes: 10,
      description:
        "Make `BoundedCounter` count between **0 and 10**. Render `<p>{count}</p>` and buttons `Decrease` and `Increase`.\n\nDisable `Decrease` at 0 and `Increase` at 10, so the count never leaves the range.",
      requirements: ["Starts at 0", "Decrease is disabled at 0", "Increase is disabled at 10"],
      hints: ["Derive the disabled flags from the count: disabled={count === 0}", "Math.min/Math.max inside the updater add a second layer of safety."],
      starterCode: useStateStub("BoundedCounter"),
      solutionCode: `import { useState } from "react";\n\nconst MIN = 0;\nconst MAX = 10;\n\nfunction BoundedCounter() {\n  const [count, setCount] = useState(MIN);\n\n  return (\n    <div>\n      <p>{count}</p>\n      <button disabled={count === MIN} onClick={() => setCount((c) => Math.max(MIN, c - 1))}>\n        Decrease\n      </button>\n      <button disabled={count === MAX} onClick={() => setCount((c) => Math.min(MAX, c + 1))}>\n        Increase\n      </button>\n    </div>\n  );\n}\n\nexport default BoundedCounter;\n`,
      explanation: "The disabled state isn't stored anywhere — it's derived from the count on each render, so it can never get out of sync.",
      tests: [
        test("decrease disabled at start", `renderComponent();\nexpectText("0");\nassert(screen.getByRole("button", { name: "Decrease" }).disabled, "Decrease should be disabled at 0");`),
        hidden("stops at 10", `renderComponent();\nfor (let i = 0; i < 12; i++) fireEvent.click(screen.getByRole("button", { name: "Increase" }));\nexpectText("10");\nassert(screen.getByRole("button", { name: "Increase" }).disabled, "Increase should be disabled at 10");\nassert(!screen.getByRole("button", { name: "Decrease" }).disabled);`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction BoundedCounter() {\n  const [count, setCount] = useState(0);\n  return (<div><p>{count}</p><button disabled={count === 0} onClick={() => setCount(count - 1)}>Decrease</button><button onClick={() => setCount(count + 1)}>Increase</button></div>);\n}\nexport default BoundedCounter;\n`],
    },
    {
      slug: "state-counter-step",
      title: "Counter With a Step Size",
      difficulty: "EASY",
      tags: ["useState", "multiple-state", "forms"],
      estimatedMinutes: 10,
      description:
        "Make `StepCounter` keep two pieces of state: the `count` (starts at 0) and the `step` (starts at 1).\n\n- A `<select aria-label=\"Step\">` with options 1, 5, 10 sets the step.\n- A button `Add step` adds the current step to the count.\n- Show `<p>Count: {count}</p>`.",
      requirements: ["Default step is 1", "Changing the select changes the step", "Add step adds the current step"],
      hints: ["Two independent useState calls.", "select values are strings: Number(event.target.value)"],
      starterCode: useStateStub("StepCounter"),
      solutionCode: `import { useState } from "react";\n\nfunction StepCounter() {\n  const [count, setCount] = useState(0);\n  const [step, setStep] = useState(1);\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <select aria-label="Step" value={step} onChange={(e) => setStep(Number(e.target.value))}>\n        <option value={1}>1</option>\n        <option value={5}>5</option>\n        <option value={10}>10</option>\n      </select>\n      <button onClick={() => setCount((c) => c + step)}>Add step</button>\n    </div>\n  );\n}\n\nexport default StepCounter;\n`,
      explanation: "Each useState call is independent. One holds the count, the other a setting that changes how the count updates.",
      commonMistakes: ["Forgetting Number(): '0' + '5' concatenates strings to '05'."],
      tests: [
        test("default step of 1", `renderComponent();\n${click("Add step")}\nexpectText("Count: 1");`),
        hidden("uses the selected step", `renderComponent();\nawait userEvent.selectOptions(screen.getByLabelText("Step"), "5");\n${click("Add step")}\n${click("Add step")}\nexpectText("Count: 10");\nawait userEvent.selectOptions(screen.getByLabelText("Step"), "1");\n${click("Add step")}\nexpectText("Count: 11");`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction StepCounter() {\n  const [count, setCount] = useState(0);\n  const [step, setStep] = useState(1);\n  return (<div><p>Count: {count}</p><select aria-label="Step" value={step} onChange={(e) => setStep(e.target.value)}><option value={1}>1</option><option value={5}>5</option><option value={10}>10</option></select><button onClick={() => setCount(count + step)}>Add step</button></div>);\n}\nexport default StepCounter;\n`],
    },
    {
      slug: "state-two-counters",
      title: "Multiple State Variables",
      difficulty: "BEGINNER",
      tags: ["useState", "multiple-state", "derived-state"],
      estimatedMinutes: 8,
      description:
        "Make `FruitBasket` track apples and oranges separately. Render `<p>Apples: {a}</p>`, `<p>Oranges: {o}</p>`, and `<p>Total: {a + o}</p>`, plus buttons `Add apple` and `Add orange`.",
      requirements: ["Separate counts", "Total is the sum"],
      hints: ["Call useState twice.", "Don't store the total — calculate it."],
      starterCode: useStateStub("FruitBasket"),
      solutionCode: `import { useState } from "react";\n\nfunction FruitBasket() {\n  const [apples, setApples] = useState(0);\n  const [oranges, setOranges] = useState(0);\n\n  return (\n    <div>\n      <p>Apples: {apples}</p>\n      <p>Oranges: {oranges}</p>\n      <p>Total: {apples + oranges}</p>\n      <button onClick={() => setApples((a) => a + 1)}>Add apple</button>\n      <button onClick={() => setOranges((o) => o + 1)}>Add orange</button>\n    </div>\n  );\n}\n\nexport default FruitBasket;\n`,
      explanation: "Values that can be computed from existing state (the total) shouldn't be stored in state — storing them invites bugs where they disagree.",
      tests: [
        test("counts apples", `renderComponent();\n${click("Add apple")}\nexpectText("Apples: 1");\nexpectText("Oranges: 0");`),
        hidden("total is the sum", `renderComponent();\n${click("Add apple")}\n${click("Add orange")}\n${click("Add orange")}\nexpectText("Apples: 1");\nexpectText("Oranges: 2");\nexpectText("Total: 3");`),
      ],
    },
    {
      slug: "toggle-visibility",
      title: "Toggle Visibility",
      difficulty: "BEGINNER",
      tags: ["useState", "conditional-rendering"],
      estimatedMinutes: 8,
      description:
        "Make `Toggle` render a button `Show`. Clicking it reveals `<p>This is the content.</p>` and changes the button's text to `Hide`. Clicking again hides the content and restores `Show`.",
      requirements: ["Hidden initially", "Show reveals and relabels to Hide", "Hide hides again"],
      hints: ["One boolean state drives both the label and the content.", "setVisible((v) => !v) flips it."],
      starterCode: useStateStub("Toggle"),
      solutionCode: `import { useState } from "react";\n\nfunction Toggle() {\n  const [visible, setVisible] = useState(false);\n\n  return (\n    <div>\n      <button onClick={() => setVisible((v) => !v)}>{visible ? "Hide" : "Show"}</button>\n      {visible && <p>This is the content.</p>}\n    </div>\n  );\n}\n\nexport default Toggle;\n`,
      explanation: "A single boolean state value can drive several pieces of UI at once.",
      tests: [
        test("reveals content", `renderComponent();\nexpectNoText("This is the content.");\n${click("Show")}\nexpectText("This is the content.");`),
        hidden("hides again", `renderComponent();\n${click("Show")}\n${click("Hide")}\nexpectNoText("This is the content.");\nscreen.getByRole("button", { name: "Show" });`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction Toggle() {\n  const [v, setV] = useState(false);\n  return (<div><button onClick={() => setV(true)}>{v ? "Hide" : "Show"}</button>{v && <p>This is the content.</p>}</div>);\n}\nexport default Toggle;\n`],
    },
    {
      slug: "like-button",
      title: "Like Button",
      difficulty: "BEGINNER",
      tags: ["useState", "toggle"],
      estimatedMinutes: 5,
      description: "Make `LikeButton` render a button that starts as `Like`. Each click toggles it between `Like` and `Liked`. Also set `aria-pressed` to whether it's liked.",
      requirements: ["Starts as 'Like'", "Toggles between 'Like' and 'Liked'", "aria-pressed reflects the state"],
      hints: ["A boolean state: const [liked, setLiked] = useState(false);", "aria-pressed={liked} makes it a toggle button for screen readers."],
      starterCode: useStateStub("LikeButton"),
      solutionCode: `import { useState } from "react";\n\nfunction LikeButton() {\n  const [liked, setLiked] = useState(false);\n\n  return (\n    <button aria-pressed={liked} onClick={() => setLiked((l) => !l)}>\n      {liked ? "Liked" : "Like"}\n    </button>\n  );\n}\n\nexport default LikeButton;\n`,
      explanation: "aria-pressed turns a button into an accessible toggle, announced as 'pressed' or 'not pressed'.",
      tests: [
        test("toggles to Liked", `renderComponent();\n${click("Like")}\nassertEqual(screen.getByRole("button", { name: "Liked" }).getAttribute("aria-pressed"), "true");`),
        hidden("toggles back", `renderComponent();\nassertEqual(screen.getByRole("button").getAttribute("aria-pressed"), "false");\n${click("Like")}\n${click("Liked")}\nscreen.getByRole("button", { name: "Like" });`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction LikeButton() {\n  const [liked, setLiked] = useState(false);\n  return <button aria-pressed={liked} onClick={() => setLiked(true)}>{liked ? "Liked" : "Like"}</button>;\n}\nexport default LikeButton;\n`],
    },
    {
      slug: "state-cycle-colors",
      title: "Cycle Through Values",
      difficulty: "BEGINNER",
      tags: ["useState", "arrays"],
      estimatedMinutes: 8,
      description:
        "Make `ColorCycler` render `<p>Color: {color}</p>` (with `style={{ color }}`) and a button `Next color`. Colors cycle `red → green → blue → red → ...`.\n\nStore the **index** in state and look the color up in an array.",
      requirements: ["Starts at red", "Cycles through the three colors and wraps around"],
      hints: ["const COLORS = [\"red\", \"green\", \"blue\"];", "Wrap with modulo: (i + 1) % COLORS.length"],
      starterCode: useStateStub("ColorCycler"),
      solutionCode: `import { useState } from "react";\n\nconst COLORS = ["red", "green", "blue"];\n\nfunction ColorCycler() {\n  const [index, setIndex] = useState(0);\n  const color = COLORS[index];\n\n  return (\n    <div>\n      <p style={{ color }}>Color: {color}</p>\n      <button onClick={() => setIndex((i) => (i + 1) % COLORS.length)}>Next color</button>\n    </div>\n  );\n}\n\nexport default ColorCycler;\n`,
      explanation: "Storing the minimal state (an index) and deriving the rest (the color) keeps state small and consistent.",
      tests: [
        test("starts red then green", `renderComponent();\nexpectText("Color: red");\n${click("Next color")}\nassertEqual(expectText("Color: green").style.color, "green");`),
        hidden("wraps around", `renderComponent();\nfor (let i = 0; i < 3; i++) { ${click("Next color")} }\nexpectText("Color: red");`),
      ],
    },
    {
      slug: "state-password-visibility",
      title: "Toggle Password Visibility",
      difficulty: "BEGINNER",
      tags: ["useState", "forms"],
      estimatedMinutes: 8,
      description:
        "Make `PasswordField` render an input labelled `Password` and a button. While hidden, the input is `type=\"password\"` and the button says `Show`; while visible, the input is `type=\"text\"` and the button says `Hide`.",
      requirements: ["Starts hidden (type=password)", "Toggles the input type and button label"],
      hints: ["type={visible ? \"text\" : \"password\"}", "Use type=\"button\" on the toggle so it never submits a form."],
      starterCode: useStateStub("PasswordField"),
      solutionCode: `import { useState } from "react";\n\nfunction PasswordField() {\n  const [visible, setVisible] = useState(false);\n\n  return (\n    <div>\n      <label htmlFor="password">Password</label>\n      <input id="password" type={visible ? "text" : "password"} />\n      <button type="button" onClick={() => setVisible((v) => !v)}>\n        {visible ? "Hide" : "Show"}\n      </button>\n    </div>\n  );\n}\n\nexport default PasswordField;\n`,
      explanation: "Changing the type attribute keeps whatever the user typed — it's the same input element, just rendered differently.",
      tests: [
        test("starts hidden", `renderComponent();\nassertEqual(screen.getByLabelText("Password").getAttribute("type"), "password");`),
        hidden("toggles both ways and keeps the value", `renderComponent();\nconst input = screen.getByLabelText("Password");\nawait userEvent.type(input, "s3cret");\n${click("Show")}\nassertEqual(screen.getByLabelText("Password").getAttribute("type"), "text");\nassertEqual(screen.getByLabelText("Password").value, "s3cret");\n${click("Hide")}\nassertEqual(screen.getByLabelText("Password").getAttribute("type"), "password");`),
      ],
    },
    {
      slug: "state-theme-toggle",
      title: "Toggle a Theme",
      difficulty: "BEGINNER",
      tags: ["useState", "styling"],
      estimatedMinutes: 8,
      description:
        "Make `ThemedPage` render a `<div>` with `className=\"app light\"` and a button `Switch to dark mode`. Clicking it switches the class to `app dark` and the button to `Switch to light mode`, and back again.",
      requirements: ["Starts light", "Toggles class and label"],
      hints: ["Store the theme as a string: useState<\"light\" | \"dark\">(\"light\")", "Derive the next theme from the current one."],
      starterCode: useStateStub("ThemedPage"),
      solutionCode: `import { useState } from "react";\n\nfunction ThemedPage() {\n  const [theme, setTheme] = useState<"light" | "dark">("light");\n  const next = theme === "light" ? "dark" : "light";\n\n  return (\n    <div className={\`app \${theme}\`}>\n      <button onClick={() => setTheme(next)}>Switch to {next} mode</button>\n    </div>\n  );\n}\n\nexport default ThemedPage;\n`,
      explanation: "Storing the theme name (instead of an isDark boolean) scales to more themes and maps straight onto a class name.",
      tests: [
        test("switches to dark", `const { container } = renderComponent();\nassertEqual(container.firstChild.className, "app light");\n${click("Switch to dark mode")}\nassertEqual(container.firstChild.className, "app dark");`),
        hidden("switches back", `const { container } = renderComponent();\n${click("Switch to dark mode")}\n${click("Switch to light mode")}\nassertEqual(container.firstChild.className, "app light");`),
      ],
    },
    {
      slug: "state-switch-views",
      title: "Switch Between Views",
      difficulty: "EASY",
      tags: ["useState", "tabs", "accessibility"],
      estimatedMinutes: 10,
      description:
        "Make `AccountPanel` render two buttons, `Profile` and `Settings`, and below them the content for the selected one:\n\n- Profile → `<p>Your profile details</p>`\n- Settings → `<p>Your account settings</p>`\n\nProfile is selected initially. The selected button has `aria-pressed=\"true\"`, the other `\"false\"`.",
      requirements: ["Profile selected by default", "Clicking switches content", "aria-pressed marks the selected view"],
      hints: ["Store which view is active: useState<\"profile\" | \"settings\">(\"profile\")", "Compare the state with each button's view."],
      starterCode: useStateStub("AccountPanel"),
      solutionCode: `import { useState } from "react";\n\ntype View = "profile" | "settings";\n\nfunction AccountPanel() {\n  const [view, setView] = useState<View>("profile");\n\n  return (\n    <div>\n      <button aria-pressed={view === "profile"} onClick={() => setView("profile")}>Profile</button>\n      <button aria-pressed={view === "settings"} onClick={() => setView("settings")}>Settings</button>\n      {view === "profile" ? <p>Your profile details</p> : <p>Your account settings</p>}\n    </div>\n  );\n}\n\nexport default AccountPanel;\n`,
      explanation: "This is the core of every tab component: one piece of state saying which panel is active.",
      tests: [
        test("shows profile by default", `renderComponent();\nexpectText("Your profile details");\nassertEqual(screen.getByRole("button", { name: "Profile" }).getAttribute("aria-pressed"), "true");`),
        hidden("switches to settings", `renderComponent();\n${click("Settings")}\nexpectText("Your account settings");\nexpectNoText("Your profile details");\nassertEqual(screen.getByRole("button", { name: "Settings" }).getAttribute("aria-pressed"), "true");\nassertEqual(screen.getByRole("button", { name: "Profile" }).getAttribute("aria-pressed"), "false");`),
      ],
    },
    {
      slug: "character-counter",
      title: "Character Counter",
      difficulty: "BEGINNER",
      tags: ["useState", "forms"],
      estimatedMinutes: 8,
      description: "Make `CharacterCounter` render an input (placeholder `Type something...`) and, below it, `<p>{n} characters</p>` updating live as the user types.",
      requirements: ["Shows '0 characters' initially", "Updates on every keystroke"],
      hints: ["Store the input's text in state.", "Render text.length — don't store the count separately."],
      starterCode: useStateStub("CharacterCounter"),
      solutionCode: `import { useState } from "react";\n\nfunction CharacterCounter() {\n  const [text, setText] = useState("");\n\n  return (\n    <div>\n      <input placeholder="Type something..." value={text} onChange={(e) => setText(e.target.value)} />\n      <p>{text.length} characters</p>\n    </div>\n  );\n}\n\nexport default CharacterCounter;\n`,
      explanation: "The count is derived from the text, so there's a single source of truth.",
      tests: [
        test("starts at 0", `renderComponent();\nexpectText("0 characters");`),
        test("counts typed characters", `renderComponent();\nawait userEvent.type(screen.getByPlaceholderText("Type something..."), "Hello");\nexpectText("5 characters");`),
        hidden("counts spaces and deletions", `renderComponent();\nconst input = screen.getByPlaceholderText("Type something...");\nawait userEvent.type(input, "Hi there");\nexpectText("8 characters");\nawait userEvent.type(input, "{backspace}{backspace}");\nexpectText("6 characters");`),
      ],
    },
    {
      slug: "state-functional-update",
      title: "Fix: Add Three With One Click",
      difficulty: "EASY",
      tags: ["useState", "functional-updates", "debugging"],
      problemType: "DEBUG",
      estimatedMinutes: 10,
      description:
        "The `+3` button is supposed to add 3, but it only adds 1. The handler calls `setCount(count + 1)` three times.\n\nFind out why, and fix it **while keeping three separate setCount calls**.",
      requirements: ["One click adds 3", "Keep three setCount calls in the handler"],
      hints: [
        "Inside one click handler, `count` is a snapshot from the current render — it doesn't change between the three calls.",
        "So all three calls ask React to set count to 0 + 1.",
        "Pass a function instead: setCount((c) => c + 1) queues an update based on the latest value.",
      ],
      starterCode: `import { useState } from "react";\n\nfunction TripleCounter() {\n  const [count, setCount] = useState(0);\n\n  function addThree() {\n    setCount(count + 1);\n    setCount(count + 1);\n    setCount(count + 1);\n  }\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={addThree}>+3</button>\n    </div>\n  );\n}\n\nexport default TripleCounter;\n`,
      solutionCode: `import { useState } from "react";\n\nfunction TripleCounter() {\n  const [count, setCount] = useState(0);\n\n  function addThree() {\n    setCount((c) => c + 1);\n    setCount((c) => c + 1);\n    setCount((c) => c + 1);\n  }\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={addThree}>+3</button>\n    </div>\n  );\n}\n\nexport default TripleCounter;\n`,
      explanation:
        "State is a snapshot: `count` stays the same for the whole event handler. setCount(count + 1) three times means 'set to 1' three times. An updater function is queued and receives the result of the previous update, so the three calls chain to 3.",
      commonMistakes: ["Assuming setCount changes `count` immediately — it schedules a re-render instead."],
      tests: [
        test("one click adds 3", `renderComponent();\n${click("+3")}\nexpectText("Count: 3");`),
        hidden("two clicks add 6", `renderComponent();\n${click("+3")}\n${click("+3")}\nexpectText("Count: 6");`),
      ],
    },
    {
      slug: "state-object-update",
      title: "Update One Property of an Object",
      difficulty: "EASY",
      tags: ["useState", "objects", "immutability"],
      estimatedMinutes: 10,
      description:
        "`Profile` keeps a `user` object in state: `{ name: \"Kim\", email: \"kim@old.com\" }`. Render `<p>{name}</p>`, `<p>{email}</p>`, and a button `Use work email`.\n\nClicking the button changes **only** the email to `kim@work.com` — the name must stay. Create a new object; don't mutate the existing one.",
      requirements: ["Email updates", "Name is preserved"],
      hints: ["Spread the old object, then override one field.", "setUser((u) => ({ ...u, email: \"kim@work.com\" }))"],
      starterCode: useStateStub("Profile"),
      solutionCode: `import { useState } from "react";\n\nfunction Profile() {\n  const [user, setUser] = useState({ name: "Kim", email: "kim@old.com" });\n\n  return (\n    <div>\n      <p>{user.name}</p>\n      <p>{user.email}</p>\n      <button onClick={() => setUser((u) => ({ ...u, email: "kim@work.com" }))}>Use work email</button>\n    </div>\n  );\n}\n\nexport default Profile;\n`,
      explanation: "useState replaces the whole value, unlike the old class component setState which merged objects. Spreading copies the fields you aren't changing.",
      commonMistakes: ["setUser({ email: \"...\" }) drops the name.", "user.email = \"...\"; setUser(user) mutates and React may skip the re-render."],
      tests: [
        test("updates email", `renderComponent();\nexpectText("kim@old.com");\n${click("Use work email")}\nexpectText("kim@work.com");`),
        hidden("keeps the name", `renderComponent();\n${click("Use work email")}\nexpectText("Kim");`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction Profile() {\n  const [user, setUser] = useState({ name: "Kim", email: "kim@old.com" });\n  return (<div><p>{user.name}</p><p>{user.email}</p><button onClick={() => setUser({ email: "kim@work.com" })}>Use work email</button></div>);\n}\nexport default Profile;\n`],
    },
    {
      slug: "state-nested-object",
      title: "Update Nested State",
      difficulty: "MEDIUM",
      tags: ["useState", "objects", "immutability"],
      estimatedMinutes: 15,
      description:
        "`NotificationSettings` keeps this state:\n\n```\n{ theme: \"light\", notifications: { email: true, sms: false } }\n```\n\nRender two checkboxes, labelled `Email` and `SMS`, bound to `notifications.email` and `notifications.sms`, plus `<p>Theme: {theme}</p>`. Toggling one checkbox must keep the other checkbox **and** the theme unchanged.",
      requirements: ["Checkboxes reflect state", "Toggling one leaves the other untouched", "theme is preserved"],
      hints: [
        "You need to copy every level you change: the outer object and the notifications object.",
        "setSettings((s) => ({ ...s, notifications: { ...s.notifications, sms: !s.notifications.sms } }))",
        "A helper toggle(key) avoids repeating that for each checkbox.",
      ],
      starterCode: useStateStub("NotificationSettings"),
      solutionCode: `import { useState } from "react";\n\ntype Channel = "email" | "sms";\n\nfunction NotificationSettings() {\n  const [settings, setSettings] = useState({\n    theme: "light",\n    notifications: { email: true, sms: false },\n  });\n\n  function toggle(channel: Channel) {\n    setSettings((s) => ({\n      ...s,\n      notifications: { ...s.notifications, [channel]: !s.notifications[channel] },\n    }));\n  }\n\n  return (\n    <div>\n      <p>Theme: {settings.theme}</p>\n      <label>\n        <input type="checkbox" checked={settings.notifications.email} onChange={() => toggle("email")} /> Email\n      </label>\n      <label>\n        <input type="checkbox" checked={settings.notifications.sms} onChange={() => toggle("sms")} /> SMS\n      </label>\n    </div>\n  );\n}\n\nexport default NotificationSettings;\n`,
      explanation: "Immutable updates copy the path from the root to the changed value. Everything else is shared by reference, which is cheap and lets React detect what changed.",
      tests: [
        test("reflects initial state", `renderComponent();\nassert(screen.getByRole("checkbox", { name: "Email" }).checked);\nassert(!screen.getByRole("checkbox", { name: "SMS" }).checked);`),
        hidden("toggling one keeps the rest", `renderComponent();\nfireEvent.click(screen.getByRole("checkbox", { name: "SMS" }));\nassert(screen.getByRole("checkbox", { name: "SMS" }).checked, "SMS should now be on");\nassert(screen.getByRole("checkbox", { name: "Email" }).checked, "Email should still be on");\nexpectText("Theme: light");\nfireEvent.click(screen.getByRole("checkbox", { name: "Email" }));\nassert(!screen.getByRole("checkbox", { name: "Email" }).checked);\nassert(screen.getByRole("checkbox", { name: "SMS" }).checked, "SMS should still be on");`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction NotificationSettings() {\n  const [s, setS] = useState({ theme: "light", notifications: { email: true, sms: false } });\n  return (<div><p>Theme: {s.theme}</p><label><input type="checkbox" checked={s.notifications.email} onChange={() => setS({ ...s, notifications: { email: !s.notifications.email } })} /> Email</label><label><input type="checkbox" checked={s.notifications.sms} onChange={() => setS({ ...s, notifications: { sms: !s.notifications.sms } })} /> SMS</label></div>);\n}\nexport default NotificationSettings;\n`],
    },
    {
      slug: "state-array-add",
      title: "Add an Item to an Array",
      difficulty: "BEGINNER",
      tags: ["useState", "arrays", "immutability"],
      estimatedMinutes: 8,
      description: "Make `ItemAdder` start with an empty list. Each click on `Add item` appends `Item {n}` (where n = new length) to a `<ul>`.",
      requirements: ["Appends 'Item 1', 'Item 2', ...", "Creates a new array (no push)"],
      hints: ["Create a new array with spread: [...items, newItem]", "Use the updater form so n is based on the latest list."],
      starterCode: useStateStub("ItemAdder"),
      solutionCode: `import { useState } from "react";\n\nfunction ItemAdder() {\n  const [items, setItems] = useState<string[]>([]);\n\n  return (\n    <div>\n      <button onClick={() => setItems((prev) => [...prev, \`Item \${prev.length + 1}\`])}>Add item</button>\n      <ul>\n        {items.map((item) => (\n          <li key={item}>{item}</li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nexport default ItemAdder;\n`,
      explanation: "React compares state by reference. push() changes the same array, so React thinks nothing changed; spreading creates a new array it can detect.",
      commonMistakes: ["items.push(x); setItems(items) — same array reference, so no re-render."],
      tests: [
        test("adds items", `renderComponent();\n${click("Add item")}\n${click("Add item")}\nassertEqual(${items}, ["Item 1", "Item 2"]);`),
        hidden("keeps adding", `renderComponent();\nfor (let i = 0; i < 4; i++) { ${click("Add item")} }\nassertEqual(screen.getAllByRole("listitem").length, 4);`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction ItemAdder() {\n  const [items, setItems] = useState([]);\n  return (<div><button onClick={() => { items.push("Item " + (items.length + 1)); setItems(items); }}>Add item</button><ul>{items.map((i) => <li key={i}>{i}</li>)}</ul></div>);\n}\nexport default ItemAdder;\n`],
    },
    {
      slug: "add-and-remove-items",
      title: "Add and Remove Items",
      difficulty: "EASY",
      tags: ["useState", "arrays", "lists", "forms"],
      type: "STATE",
      estimatedMinutes: 15,
      description:
        "Make `TodoApp` render an input (placeholder `Add a todo`) and an `Add` button. Each added todo appears in a list with its own `Remove` button that deletes **only** that item. Clear the input after adding, and ignore empty input.",
      requirements: ["Adds non-empty todos", "Clears the input after adding", "Remove deletes only that item"],
      hints: [
        "Keep todos as objects with an id, e.g. { id: Date.now(), text }.",
        "Remove with filter: setTodos((prev) => prev.filter((t) => t.id !== id))",
      ],
      starterCode: useStateStub("TodoApp"),
      solutionCode: `import { useState } from "react";\n\ninterface Todo {\n  id: number;\n  text: string;\n}\n\nlet nextId = 1;\n\nfunction TodoApp() {\n  const [text, setText] = useState("");\n  const [todos, setTodos] = useState<Todo[]>([]);\n\n  function addTodo() {\n    if (!text.trim()) return;\n    setTodos((prev) => [...prev, { id: nextId++, text: text.trim() }]);\n    setText("");\n  }\n\n  function removeTodo(id: number) {\n    setTodos((prev) => prev.filter((t) => t.id !== id));\n  }\n\n  return (\n    <div>\n      <input placeholder="Add a todo" value={text} onChange={(e) => setText(e.target.value)} />\n      <button onClick={addTodo}>Add</button>\n      <ul>\n        {todos.map((todo) => (\n          <li key={todo.id}>\n            <span>{todo.text}</span>\n            <button onClick={() => removeTodo(todo.id)}>Remove</button>\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nexport default TodoApp;\n`,
      explanation: "Adding is spread, removing is filter — both create new arrays. Ids (not text) identify todos, so two todos with the same text are still removable individually.",
      tests: [
        test("adds a todo and clears the input", `renderComponent();\nconst input = screen.getByPlaceholderText("Add a todo");\nawait userEvent.type(input, "Buy milk");\n${click("Add")}\nexpectText("Buy milk");\nassertEqual(input.value, "", "The input should be cleared after adding");`),
        hidden("removes only the clicked item", `renderComponent();\nconst input = screen.getByPlaceholderText("Add a todo");\nfor (const t of ["A", "B", "C"]) { await userEvent.type(input, t); ${click("Add")} }\nconst b = screen.getByText("B").closest("li");\nfireEvent.click(within(b).getByRole("button", { name: "Remove" }));\nassertEqual(screen.getAllByRole("listitem").map((li) => li.querySelector("span")?.textContent ?? li.firstChild.textContent), ["A", "C"]);`),
        hidden("ignores empty input", `renderComponent();\n${click("Add")}\nassertEqual(screen.queryAllByRole("listitem").length, 0);`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction TodoApp() {\n  const [text, setText] = useState("");\n  const [todos, setTodos] = useState([]);\n  return (<div><input placeholder="Add a todo" value={text} onChange={(e) => setText(e.target.value)} /><button onClick={() => { setTodos([...todos, text]); setText(""); }}>Add</button><ul>{todos.map((t, i) => <li key={i}><span>{t}</span><button onClick={() => setTodos([])}>Remove</button></li>)}</ul></div>);\n}\nexport default TodoApp;\n`],
    },
    {
      slug: "state-array-update",
      title: "Update One Item in an Array",
      difficulty: "EASY",
      tags: ["useState", "arrays", "immutability"],
      estimatedMinutes: 12,
      description:
        "`PostList` starts with these posts in state:\n\n```\n[{ id: 1, title: \"Hello\", likes: 0 }, { id: 2, title: \"World\", likes: 0 }]\n```\n\nRender each post as an `<li>` showing `{title}: {likes} likes` and a `Like` button. Clicking `Like` increments only that post's likes.",
      requirements: ["Each post has its own Like button", "Only the clicked post changes"],
      hints: ["map over the array and replace just the matching item.", "posts.map((p) => (p.id === id ? { ...p, likes: p.likes + 1 } : p))"],
      starterCode: useStateStub("PostList"),
      solutionCode: `import { useState } from "react";\n\nfunction PostList() {\n  const [posts, setPosts] = useState([\n    { id: 1, title: "Hello", likes: 0 },\n    { id: 2, title: "World", likes: 0 },\n  ]);\n\n  function like(id: number) {\n    setPosts((prev) => prev.map((p) => (p.id === id ? { ...p, likes: p.likes + 1 } : p)));\n  }\n\n  return (\n    <ul>\n      {posts.map((post) => (\n        <li key={post.id}>\n          <span>\n            {post.title}: {post.likes} likes\n          </span>\n          <button onClick={() => like(post.id)}>Like</button>\n        </li>\n      ))}\n    </ul>\n  );\n}\n\nexport default PostList;\n`,
      explanation: "map + spread is the standard immutable 'update one item' pattern: new array, new object for the changed item, same objects for the rest.",
      tests: [
        test("likes a post", `renderComponent();\nconst first = screen.getByText("Hello: 0 likes").closest("li");\nfireEvent.click(within(first).getByRole("button", { name: "Like" }));\nexpectText("Hello: 1 likes");`),
        hidden("only the clicked post changes", `renderComponent();\nconst second = screen.getByText("World: 0 likes").closest("li");\nfireEvent.click(within(second).getByRole("button"));\nfireEvent.click(within(second).getByRole("button"));\nexpectText("World: 2 likes");\nexpectText("Hello: 0 likes");`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction PostList() {\n  const [posts, setPosts] = useState([{ id: 1, title: "Hello", likes: 0 }, { id: 2, title: "World", likes: 0 }]);\n  return (<ul>{posts.map((p) => <li key={p.id}><span>{p.title}: {p.likes} likes</span><button onClick={() => setPosts(posts.map((q) => ({ ...q, likes: q.likes + 1 })))}>Like</button></li>)}</ul>);\n}\nexport default PostList;\n`],
    },
    {
      slug: "state-array-toggle",
      title: "Toggle Items in a Checklist",
      difficulty: "EASY",
      tags: ["useState", "arrays", "derived-state"],
      estimatedMinutes: 12,
      description:
        "`Checklist` starts with three tasks: `Pack`, `Book hotel`, `Buy tickets` (all not done). Render each as a checkbox labelled with its title. Above the list show `<p>{done} of 3 done</p>`, derived from the tasks.",
      requirements: ["Checkboxes toggle their task", "Summary counts completed tasks"],
      hints: ["Toggle with map, flipping `done` on the matching id.", "const doneCount = tasks.filter((t) => t.done).length;"],
      starterCode: useStateStub("Checklist"),
      solutionCode: `import { useState } from "react";\n\nconst INITIAL = [\n  { id: 1, title: "Pack", done: false },\n  { id: 2, title: "Book hotel", done: false },\n  { id: 3, title: "Buy tickets", done: false },\n];\n\nfunction Checklist() {\n  const [tasks, setTasks] = useState(INITIAL);\n  const doneCount = tasks.filter((t) => t.done).length;\n\n  function toggle(id: number) {\n    setTasks((prev) => prev.map((t) => (t.id === id ? { ...t, done: !t.done } : t)));\n  }\n\n  return (\n    <div>\n      <p>\n        {doneCount} of {tasks.length} done\n      </p>\n      <ul>\n        {tasks.map((task) => (\n          <li key={task.id}>\n            <label>\n              <input type="checkbox" checked={task.done} onChange={() => toggle(task.id)} /> {task.title}\n            </label>\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nexport default Checklist;\n`,
      explanation: "The summary is derived from the array, so it's always correct no matter how tasks change.",
      tests: [
        test("checks a task", `renderComponent();\nexpectText("0 of 3 done");\nfireEvent.click(screen.getByRole("checkbox", { name: "Pack" }));\nexpectText("1 of 3 done");`),
        hidden("unchecks and counts correctly", `renderComponent();\nfireEvent.click(screen.getByRole("checkbox", { name: "Pack" }));\nfireEvent.click(screen.getByRole("checkbox", { name: "Buy tickets" }));\nfireEvent.click(screen.getByRole("checkbox", { name: "Pack" }));\nexpectText("1 of 3 done");\nassert(screen.getByRole("checkbox", { name: "Buy tickets" }).checked);`),
      ],
    },
    {
      slug: "state-init-from-props",
      title: "Initialize State From a Prop",
      difficulty: "BEGINNER",
      tags: ["useState", "props"],
      estimatedMinutes: 8,
      description:
        "Make `Counter` accept `initialCount` and use it as the **starting** value of its state. Render `<p>{count}</p>` and a button `+1`.\n\nThe prop is named `initial...` on purpose: it only seeds the state. Later changes to the prop are intentionally ignored.",
      requirements: ["Starts at initialCount", "+1 increments from there"],
      hints: ["Pass the prop to useState: useState(initialCount)", "useState only uses its argument on the first render."],
      starterCode: useStateStub("Counter", "{ initialCount }: { initialCount: number }"),
      solutionCode: `import { useState } from "react";\n\nfunction Counter({ initialCount }: { initialCount: number }) {\n  const [count, setCount] = useState(initialCount);\n\n  return (\n    <div>\n      <p>{count}</p>\n      <button onClick={() => setCount((c) => c + 1)}>+1</button>\n    </div>\n  );\n}\n\nexport default Counter;\n`,
      explanation: "useState's argument is only the initial value. Naming the prop `initialX` (or `defaultX`) signals to callers that changing it later won't reset the state.",
      tests: [
        test("starts from the prop", `renderComponent({ initialCount: 10 });\nexpectText("10");\n${click("+1")}\nexpectText("11");`),
        hidden("other starting value", `renderComponent({ initialCount: -3 });\n${click("+1")}\nexpectText("-2");`),
      ],
    },
    {
      slug: "state-lazy-init",
      title: "Lazy State Initialization",
      difficulty: "EASY",
      tags: ["useState", "performance"],
      problemType: "OPTIMIZE",
      estimatedMinutes: 10,
      description:
        "`Notes` works, but `createInitialNotes()` (imagine it's expensive) runs on **every render**, even though useState only needs its result the first time.\n\nChange the code so `createInitialNotes` runs only once. Don't change what's rendered. The exported `initCalls` counter is what the tests check.",
      requirements: ["Rendering and adding notes works as before", "createInitialNotes runs exactly once"],
      hints: [
        "useState(createInitialNotes()) calls the function first, then passes the result — every render.",
        "useState also accepts a function, which React only calls on the first render.",
        "useState(createInitialNotes) — pass the function itself, without ().",
      ],
      starterCode: `import { useState } from "react";\n\nexport let initCalls = 0;\n\nfunction createInitialNotes() {\n  initCalls++;\n  return ["Note 1", "Note 2", "Note 3"];\n}\n\nfunction Notes() {\n  const [notes, setNotes] = useState(createInitialNotes());\n\n  return (\n    <div>\n      <ul>\n        {notes.map((note) => (\n          <li key={note}>{note}</li>\n        ))}\n      </ul>\n      <button onClick={() => setNotes((prev) => [...prev, \`Note \${prev.length + 1}\`])}>Add note</button>\n    </div>\n  );\n}\n\nexport default Notes;\n`,
      solutionCode: `import { useState } from "react";\n\nexport let initCalls = 0;\n\nfunction createInitialNotes() {\n  initCalls++;\n  return ["Note 1", "Note 2", "Note 3"];\n}\n\nfunction Notes() {\n  const [notes, setNotes] = useState(createInitialNotes);\n\n  return (\n    <div>\n      <ul>\n        {notes.map((note) => (\n          <li key={note}>{note}</li>\n        ))}\n      </ul>\n      <button onClick={() => setNotes((prev) => [...prev, \`Note \${prev.length + 1}\`])}>Add note</button>\n    </div>\n  );\n}\n\nexport default Notes;\n`,
      explanation: "Passing an initializer function (not its result) lets React skip the work on re-renders. It matters when the initial value comes from parsing, localStorage, or heavy computation.",
      tests: [
        test("renders and adds notes", `renderComponent();\n${click("Add note")}\nassertEqual(screen.getAllByRole("listitem").length, 4);`),
        hidden("initializer runs once", `const before = userExports.initCalls;\nrenderComponent();\n${click("Add note")}\n${click("Add note")}\nassertEqual(userExports.initCalls - before, 1, "createInitialNotes should run only on the first render");`),
      ],
    },
    {
      slug: "state-quantity-total",
      title: "Quantity Picker With Total",
      difficulty: "EASY",
      tags: ["useState", "derived-state"],
      estimatedMinutes: 10,
      description:
        "Make `QuantityPicker` accept `unitPrice`. Keep a quantity starting at **1** with buttons `-` and `+` (minimum 1; `-` is disabled at 1). Show `<p>Quantity: {q}</p>` and `<p>Total: ${total}</p>` with two decimals.",
      requirements: ["Starts at 1", "Can't go below 1", "Total = quantity × unitPrice"],
      hints: ["Total is derived, not stored.", "disabled={quantity === 1}"],
      starterCode: useStateStub("QuantityPicker", "{ unitPrice }: { unitPrice: number }"),
      solutionCode: `import { useState } from "react";\n\nfunction QuantityPicker({ unitPrice }: { unitPrice: number }) {\n  const [quantity, setQuantity] = useState(1);\n  const total = quantity * unitPrice;\n\n  return (\n    <div>\n      <button disabled={quantity === 1} onClick={() => setQuantity((q) => Math.max(1, q - 1))}>-</button>\n      <button onClick={() => setQuantity((q) => q + 1)}>+</button>\n      <p>Quantity: {quantity}</p>\n      <p>Total: \${total.toFixed(2)}</p>\n    </div>\n  );\n}\n\nexport default QuantityPicker;\n`,
      explanation: "State holds what the user chose; everything else (total, disabled) is computed from it plus props.",
      tests: [
        test("increments and totals", `renderComponent({ unitPrice: 2.5 });\n${click("+")}\nexpectText("Quantity: 2");\nexpectText("Total: $5.00");`),
        hidden("minimum of 1", `renderComponent({ unitPrice: 4 });\nassert(screen.getByRole("button", { name: "-" }).disabled);\n${click("+")}\n${click("-")}\n${click("-")}\nexpectText("Quantity: 1");\nexpectText("Total: $4.00");`),
      ],
    },
    {
      slug: "state-select-multiple",
      title: "Select Multiple Items",
      difficulty: "MEDIUM",
      tags: ["useState", "arrays", "selection"],
      estimatedMinutes: 15,
      description:
        "Make `FileSelector` accept `files` (strings). Render a checkbox per file (labelled with the filename), a `<p>{n} selected</p>` summary, and a `Clear selection` button that unchecks everything (disabled when nothing is selected).\n\nStore the **selected filenames** in state, not a boolean per file.",
      requirements: ["Checkboxes toggle selection", "Summary shows the count", "Clear selection empties it and is disabled when empty"],
      hints: [
        "const [selected, setSelected] = useState<string[]>([]);",
        "checked={selected.includes(file)}",
        "Toggle: include ? filter it out : append it.",
      ],
      starterCode: useStateStub("FileSelector", "{ files }: { files: string[] }"),
      solutionCode: `import { useState } from "react";\n\nfunction FileSelector({ files }: { files: string[] }) {\n  const [selected, setSelected] = useState<string[]>([]);\n\n  function toggle(file: string) {\n    setSelected((prev) => (prev.includes(file) ? prev.filter((f) => f !== file) : [...prev, file]));\n  }\n\n  return (\n    <div>\n      <p>{selected.length} selected</p>\n      <button disabled={selected.length === 0} onClick={() => setSelected([])}>\n        Clear selection\n      </button>\n      <ul>\n        {files.map((file) => (\n          <li key={file}>\n            <label>\n              <input type="checkbox" checked={selected.includes(file)} onChange={() => toggle(file)} /> {file}\n            </label>\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nexport default FileSelector;\n`,
      explanation: "Storing the selection separately from the data means the files can come from props or an API and change without losing which ones are selected.",
      tests: [
        test("selects files", `renderComponent({ files: ["a.txt", "b.txt", "c.txt"] });\nfireEvent.click(screen.getByRole("checkbox", { name: "a.txt" }));\nfireEvent.click(screen.getByRole("checkbox", { name: "c.txt" }));\nexpectText("2 selected");`),
        hidden("deselects and clears", `renderComponent({ files: ["a.txt", "b.txt"] });\nassert(screen.getByRole("button", { name: "Clear selection" }).disabled);\nfireEvent.click(screen.getByRole("checkbox", { name: "a.txt" }));\nfireEvent.click(screen.getByRole("checkbox", { name: "b.txt" }));\nfireEvent.click(screen.getByRole("checkbox", { name: "a.txt" }));\nexpectText("1 selected");\n${click("Clear selection")}\nexpectText("0 selected");\nassert(!screen.getByRole("checkbox", { name: "b.txt" }).checked);`),
      ],
    },
    {
      slug: "state-temperature-converter",
      title: "Temperature Converter",
      difficulty: "EASY",
      tags: ["useState", "forms", "derived-state"],
      estimatedMinutes: 10,
      description:
        "Make `TemperatureConverter` render an input labelled `Celsius`. Below it show `<p>{f}°F</p>` where f = c × 9/5 + 32, rounded to one decimal (`20` → `68.0°F`). When the input is empty or not a number, show `<p>Enter a number</p>` instead.",
      requirements: ["Converts as the user types", "One decimal place", "Handles empty / invalid input"],
      hints: ["Store the raw text; convert during render.", "const c = parseFloat(text); Number.isNaN(c) tells you it's invalid."],
      starterCode: useStateStub("TemperatureConverter"),
      solutionCode: `import { useState } from "react";\n\nfunction TemperatureConverter() {\n  const [celsius, setCelsius] = useState("");\n  const c = parseFloat(celsius);\n\n  return (\n    <div>\n      <label>\n        Celsius\n        <input value={celsius} onChange={(e) => setCelsius(e.target.value)} />\n      </label>\n      {Number.isNaN(c) ? <p>Enter a number</p> : <p>{(c * 9 / 5 + 32).toFixed(1)}°F</p>}\n    </div>\n  );\n}\n\nexport default TemperatureConverter;\n`,
      explanation: "Keep exactly what the user typed in state. Parsing and formatting happen at render time, so half-typed input like '-' doesn't get mangled.",
      tests: [
        test("converts 20°C", `renderComponent();\nawait userEvent.type(screen.getByLabelText("Celsius"), "20");\nexpectText("68.0°F");`),
        hidden("handles invalid and negative input", `renderComponent();\nexpectText("Enter a number");\nconst input = screen.getByLabelText("Celsius");\nawait userEvent.type(input, "abc");\nexpectText("Enter a number");\nawait userEvent.clear(input);\nawait userEvent.type(input, "-40");\nexpectText("-40.0°F");`),
      ],
    },
  ],
};
