import { hidden, stub, test, type CategoryBank } from "./types.js";

const formStub = (name: string, params = "") => stub(name, { imports: `import { useState } from "react";`, params });
const click = (name: string) => `fireEvent.click(screen.getByRole("button", { name: ${JSON.stringify(name)} }));`;
const type = (label: string, text: string) => `await userEvent.type(screen.getByLabelText(${JSON.stringify(label)}), ${JSON.stringify(text)});`;

export const forms: CategoryBank = {
  category: "Forms",
  level: 9,
  type: "STATE",
  prerequisites: ["useState", "Events"],
  problems: [
    {
      slug: "controlled-input",
      title: "Controlled Input",
      difficulty: "BEGINNER",
      tags: ["forms", "controlled-components", "useState"],
      estimatedMinutes: 8,
      description:
        "Make `NameInput` render a text input (placeholder `Enter your name`) and below it `<p>Hello, {name}!</p>`, updating as the user types. With an empty input, show `Hello, !`.\n\nMake it **controlled**: the input's `value` comes from state, and `onChange` updates that state.",
      requirements: ["value is bound to state", "Greeting updates on every keystroke"],
      hints: ["const [name, setName] = useState(\"\");", "<input value={name} onChange={(e) => setName(e.target.value)} />"],
      starterCode: formStub("NameInput"),
      solutionCode: `import { useState } from "react";\n\nfunction NameInput() {\n  const [name, setName] = useState("");\n\n  return (\n    <div>\n      <input placeholder="Enter your name" value={name} onChange={(e) => setName(e.target.value)} />\n      <p>Hello, {name}!</p>\n    </div>\n  );\n}\n\nexport default NameInput;\n`,
      explanation: "In a controlled component React state is the single source of truth: the input displays the state, and every keystroke updates it.",
      commonMistakes: ["value={name} without onChange makes the input read-only (and React warns)."],
      tests: [
        test("greets as you type", `renderComponent();\nawait userEvent.type(screen.getByPlaceholderText("Enter your name"), "Alice");\nexpectText("Hello, Alice!");`),
        hidden("starts empty and keeps updating", `renderComponent();\nexpectText("Hello, !");\nconst input = screen.getByPlaceholderText("Enter your name");\nawait userEvent.type(input, "Bob");\nawait userEvent.type(input, " Smith");\nexpectText("Hello, Bob Smith!");\nassertEqual(input.value, "Bob Smith");`),
      ],
    },
    {
      slug: "forms-controlled-checkbox",
      title: "Controlled Checkbox",
      difficulty: "BEGINNER",
      tags: ["forms", "checkbox", "useState"],
      estimatedMinutes: 8,
      description: "Make `AgreeAndContinue` render a checkbox labelled `I agree to the terms` and a button `Continue`. The button is disabled until the box is checked.",
      requirements: ["Checkbox is controlled by state", "Continue is enabled only when checked"],
      hints: ["Checkboxes use `checked`, not `value`.", "checked={agreed} onChange={(e) => setAgreed(e.target.checked)}"],
      starterCode: formStub("AgreeAndContinue"),
      solutionCode: `import { useState } from "react";\n\nfunction AgreeAndContinue() {\n  const [agreed, setAgreed] = useState(false);\n\n  return (\n    <div>\n      <label>\n        <input type="checkbox" checked={agreed} onChange={(e) => setAgreed(e.target.checked)} /> I agree to the terms\n      </label>\n      <button disabled={!agreed}>Continue</button>\n    </div>\n  );\n}\n\nexport default AgreeAndContinue;\n`,
      explanation: "A controlled checkbox mirrors a boolean in state; other UI (the button) derives from the same boolean.",
      tests: [
        test("enables Continue when checked", `renderComponent();\nassert(screen.getByRole("button", { name: "Continue" }).disabled);\nfireEvent.click(screen.getByRole("checkbox", { name: "I agree to the terms" }));\nassert(!screen.getByRole("button", { name: "Continue" }).disabled);`),
        hidden("disables again when unchecked", `renderComponent();\nconst box = screen.getByRole("checkbox");\nfireEvent.click(box);\nfireEvent.click(box);\nassert(screen.getByRole("button", { name: "Continue" }).disabled);\nassert(!box.checked);`),
      ],
    },
    {
      slug: "forms-radio-group",
      title: "Radio Buttons",
      difficulty: "BEGINNER",
      tags: ["forms", "radio", "useState"],
      estimatedMinutes: 10,
      description:
        "Make `SizePicker` render three radio buttons named `size`, labelled `Small`, `Medium`, `Large` (values `S`, `M`, `L`). Below them show `<p>Selected: {label}</p>`, or `<p>Choose a size</p>` before anything is picked.",
      requirements: ["Radios share a name", "Only one can be selected", "Summary shows the selected size label"],
      hints: ["Store the selected value: useState<string | null>(null)", "checked={size === option.value}", "Map over an array of { value, label } options."],
      starterCode: formStub("SizePicker"),
      solutionCode: `import { useState } from "react";\n\nconst OPTIONS = [\n  { value: "S", label: "Small" },\n  { value: "M", label: "Medium" },\n  { value: "L", label: "Large" },\n];\n\nfunction SizePicker() {\n  const [size, setSize] = useState<string | null>(null);\n  const selected = OPTIONS.find((o) => o.value === size);\n\n  return (\n    <div>\n      {OPTIONS.map((option) => (\n        <label key={option.value}>\n          <input\n            type="radio"\n            name="size"\n            value={option.value}\n            checked={size === option.value}\n            onChange={(e) => setSize(e.target.value)}\n          />\n          {option.label}\n        </label>\n      ))}\n      <p>{selected ? \`Selected: \${selected.label}\` : "Choose a size"}</p>\n    </div>\n  );\n}\n\nexport default SizePicker;\n`,
      explanation: "A radio group is one piece of state (the chosen value); each radio is checked when its value matches.",
      tests: [
        test("selects a size", `renderComponent();\nexpectText("Choose a size");\nfireEvent.click(screen.getByRole("radio", { name: "Medium" }));\nexpectText("Selected: Medium");`),
        hidden("only one selected at a time", `renderComponent();\nfireEvent.click(screen.getByRole("radio", { name: "Small" }));\nfireEvent.click(screen.getByRole("radio", { name: "Large" }));\nassert(!screen.getByRole("radio", { name: "Small" }).checked);\nassert(screen.getByRole("radio", { name: "Large" }).checked);\nexpectText("Selected: Large");\nassertEqual(screen.getByRole("radio", { name: "Large" }).value, "L");`),
      ],
    },
    {
      slug: "forms-controlled-select",
      title: "Controlled Select Dropdown",
      difficulty: "BEGINNER",
      tags: ["forms", "select", "useState"],
      estimatedMinutes: 8,
      description:
        "Make `CountrySelect` render a `<select>` labelled `Country` with options `Canada` (`ca`), `Mexico` (`mx`), and `United States` (`us`), defaulting to `us`. Show `<p>Shipping to: {country name}</p>`.",
      requirements: ["Defaults to United States", "Summary updates when the selection changes"],
      hints: ["The state holds the code; look up the name for display.", "<select value={country} onChange={...}>"],
      starterCode: formStub("CountrySelect"),
      solutionCode: `import { useState } from "react";\n\nconst COUNTRIES: Record<string, string> = { ca: "Canada", mx: "Mexico", us: "United States" };\n\nfunction CountrySelect() {\n  const [country, setCountry] = useState("us");\n\n  return (\n    <div>\n      <label>\n        Country\n        <select value={country} onChange={(e) => setCountry(e.target.value)}>\n          {Object.entries(COUNTRIES).map(([code, name]) => (\n            <option key={code} value={code}>\n              {name}\n            </option>\n          ))}\n        </select>\n      </label>\n      <p>Shipping to: {COUNTRIES[country]}</p>\n    </div>\n  );\n}\n\nexport default CountrySelect;\n`,
      explanation: "In React, a select's selected option is set with value on the <select>, not selected on an <option>.",
      tests: [
        test("defaults to US", `renderComponent();\nexpectText("Shipping to: United States");\nassertEqual(screen.getByLabelText("Country").value, "us");`),
        hidden("changes country", `renderComponent();\nawait userEvent.selectOptions(screen.getByLabelText("Country"), "mx");\nexpectText("Shipping to: Mexico");`),
      ],
    },
    {
      slug: "forms-textarea-limit",
      title: "Textarea With a Character Limit",
      difficulty: "EASY",
      tags: ["forms", "textarea", "useState"],
      estimatedMinutes: 10,
      description:
        "Make `BioField` render a textarea labelled `Bio` that holds at most **20 characters**. Extra characters are cut off. Below it show `<p>{remaining} characters left</p>`.",
      requirements: ["Never holds more than 20 characters", "Shows remaining characters"],
      hints: ["Truncate in onChange: setBio(e.target.value.slice(0, 20))", "remaining = 20 - bio.length"],
      starterCode: formStub("BioField"),
      solutionCode: `import { useState } from "react";\n\nconst LIMIT = 20;\n\nfunction BioField() {\n  const [bio, setBio] = useState("");\n\n  return (\n    <div>\n      <label>\n        Bio\n        <textarea value={bio} onChange={(e) => setBio(e.target.value.slice(0, LIMIT))} />\n      </label>\n      <p>{LIMIT - bio.length} characters left</p>\n    </div>\n  );\n}\n\nexport default BioField;\n`,
      explanation: "Controlled inputs let you transform input before it's stored — truncating, upper-casing, stripping characters.",
      alternativeApproach: "The native maxLength attribute also blocks typing, but controlling the value works for any rule.",
      tests: [
        test("counts down", `renderComponent();\n${type("Bio", "Hello")}\nexpectText("15 characters left");`),
        hidden("caps at 20", `renderComponent();\n${type("Bio", "abcdefghijklmnopqrstuvwxyz")}\nassertEqual(screen.getByLabelText("Bio").value, "abcdefghijklmnopqrst");\nexpectText("0 characters left");`),
      ],
    },
    {
      slug: "forms-object-state",
      title: "Multiple Inputs With One State Object",
      difficulty: "EASY",
      tags: ["forms", "objects", "useState"],
      estimatedMinutes: 12,
      description:
        "Make `ContactCard` render three inputs labelled `First name`, `Last name`, `Email` with `name` attributes `firstName`, `lastName`, `email`. Keep **one** state object and **one** `handleChange` that uses `event.target.name`. Show a preview: `<p>{firstName} {lastName} &lt;{email}&gt;</p>`.",
      requirements: ["One state object", "One shared change handler", "Preview updates live"],
      hints: ["const { name, value } = event.target;", "setForm((f) => ({ ...f, [name]: value }))"],
      starterCode: formStub("ContactCard"),
      solutionCode: `import { useState, type ChangeEvent } from "react";\n\nfunction ContactCard() {\n  const [form, setForm] = useState({ firstName: "", lastName: "", email: "" });\n\n  function handleChange(event: ChangeEvent<HTMLInputElement>) {\n    const { name, value } = event.target;\n    setForm((f) => ({ ...f, [name]: value }));\n  }\n\n  return (\n    <div>\n      <label>\n        First name <input name="firstName" value={form.firstName} onChange={handleChange} />\n      </label>\n      <label>\n        Last name <input name="lastName" value={form.lastName} onChange={handleChange} />\n      </label>\n      <label>\n        Email <input name="email" value={form.email} onChange={handleChange} />\n      </label>\n      <p>\n        {form.firstName} {form.lastName} &lt;{form.email}&gt;\n      </p>\n    </div>\n  );\n}\n\nexport default ContactCard;\n`,
      explanation: "Computed property names ([name]: value) let one handler update whichever field changed, which scales to forms with many fields.",
      tests: [
        test("previews the contact", `renderComponent();\n${type("First name", "Ada")}\n${type("Last name", "King")}\n${type("Email", "ada@k.io")}\nexpectText("Ada King <ada@k.io>");`),
        hidden("uses name attributes", `renderComponent();\nassertEqual(screen.getByLabelText("Email").getAttribute("name"), "email");\n${type("Last name", "Ng")}\nassertEqual(screen.getByLabelText("First name").value, "");\nassertEqual(screen.getByLabelText("Last name").value, "Ng");`),
      ],
    },
    {
      slug: "forms-submit-and-reset",
      title: "Submit Form Values and Reset",
      difficulty: "EASY",
      tags: ["forms", "onSubmit", "useState"],
      estimatedMinutes: 12,
      description:
        "Make `FeedbackForm` accept `onSubmit`. Render inputs labelled `Name` and `Message` and a submit button `Send`. On submit: prevent the default, call `onSubmit({ name, message })`, then clear both fields.",
      requirements: ["Calls onSubmit with both values", "Clears the form afterwards", "Prevents page reload"],
      hints: ["Handle onSubmit on the <form>.", "Reset by setting both pieces of state back to \"\"."],
      starterCode: formStub("FeedbackForm", "{ onSubmit }: { onSubmit: (data: { name: string; message: string }) => void }"),
      solutionCode: `import { useState, type FormEvent } from "react";\n\nfunction FeedbackForm({ onSubmit }: { onSubmit: (data: { name: string; message: string }) => void }) {\n  const [name, setName] = useState("");\n  const [message, setMessage] = useState("");\n\n  function handleSubmit(event: FormEvent) {\n    event.preventDefault();\n    onSubmit({ name, message });\n    setName("");\n    setMessage("");\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <label>\n        Name <input value={name} onChange={(e) => setName(e.target.value)} />\n      </label>\n      <label>\n        Message <textarea value={message} onChange={(e) => setMessage(e.target.value)} />\n      </label>\n      <button type="submit">Send</button>\n    </form>\n  );\n}\n\nexport default FeedbackForm;\n`,
      explanation: "With controlled inputs, resetting the form is just resetting state.",
      tests: [
        test("submits values", `const onSubmit = mockFn();\nrenderComponent({ onSubmit });\n${type("Name", "Jo")}\n${type("Message", "Great app")}\n${click("Send")}\nassertEqual(onSubmit.calls, [[{ name: "Jo", message: "Great app" }]]);`),
        hidden("clears after submit", `renderComponent({ onSubmit: () => {} });\n${type("Name", "Jo")}\n${type("Message", "Hi")}\n${click("Send")}\nassertEqual(screen.getByLabelText("Name").value, "");\nassertEqual(screen.getByLabelText("Message").value, "");`),
      ],
    },
    {
      slug: "forms-required-field",
      title: "Required Field Validation",
      difficulty: "EASY",
      tags: ["forms", "validation"],
      estimatedMinutes: 12,
      description:
        "Make `UsernameForm` accept `onSubmit`. It has an input labelled `Username` and a submit button `Create`. On submit:\n\n- empty (or only spaces) → show `<p role=\"alert\">Username is required</p>` and do **not** call onSubmit\n- otherwise → hide any error and call `onSubmit(trimmedUsername)`",
      requirements: ["Blocks empty submissions with an error", "Submits the trimmed value", "Clears the error after a valid submit"],
      hints: ["Keep the error message in state: useState<string | null>(null)", "Validate inside the submit handler before calling onSubmit."],
      starterCode: formStub("UsernameForm", "{ onSubmit }: { onSubmit: (username: string) => void }"),
      solutionCode: `import { useState, type FormEvent } from "react";\n\nfunction UsernameForm({ onSubmit }: { onSubmit: (username: string) => void }) {\n  const [username, setUsername] = useState("");\n  const [error, setError] = useState<string | null>(null);\n\n  function handleSubmit(event: FormEvent) {\n    event.preventDefault();\n    const value = username.trim();\n    if (!value) {\n      setError("Username is required");\n      return;\n    }\n    setError(null);\n    onSubmit(value);\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <label>\n        Username <input value={username} onChange={(e) => setUsername(e.target.value)} />\n      </label>\n      {error && <p role="alert">{error}</p>}\n      <button type="submit">Create</button>\n    </form>\n  );\n}\n\nexport default UsernameForm;\n`,
      explanation: "Validation on submit: check, set an error and stop, or clear errors and proceed. role='alert' makes the error audible to screen-reader users.",
      tests: [
        test("shows an error when empty", `const onSubmit = mockFn();\nrenderComponent({ onSubmit });\n${click("Create")}\nassertEqual(screen.getByRole("alert").textContent, "Username is required");\nassertEqual(onSubmit.calls.length, 0);`),
        hidden("submits trimmed value and clears error", `const onSubmit = mockFn();\nrenderComponent({ onSubmit });\n${type("Username", "   ")}\n${click("Create")}\nscreen.getByRole("alert");\n${type("Username", "neo ")}\n${click("Create")}\nassertEqual(onSubmit.calls, [["neo"]]);\nassert(!screen.queryByRole("alert"), "The error should disappear after a valid submit");`),
      ],
    },
    {
      slug: "forms-email-validation",
      title: "Email Validation",
      difficulty: "EASY",
      tags: ["forms", "validation", "regex"],
      estimatedMinutes: 12,
      description:
        "Make `EmailForm` accept `onSubmit`, with an input labelled `Email` and a button `Join`. On submit, if the email doesn't match `/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/`, show `<p role=\"alert\">Please enter a valid email</p>`. Otherwise call `onSubmit(email)`.",
      requirements: ["Rejects malformed emails", "Accepts valid ones"],
      hints: ["const EMAIL_RE = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;", "EMAIL_RE.test(email)"],
      starterCode: formStub("EmailForm", "{ onSubmit }: { onSubmit: (email: string) => void }"),
      solutionCode: `import { useState, type FormEvent } from "react";\n\nconst EMAIL_RE = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\n\nfunction EmailForm({ onSubmit }: { onSubmit: (email: string) => void }) {\n  const [email, setEmail] = useState("");\n  const [error, setError] = useState("");\n\n  function handleSubmit(event: FormEvent) {\n    event.preventDefault();\n    if (!EMAIL_RE.test(email)) {\n      setError("Please enter a valid email");\n      return;\n    }\n    setError("");\n    onSubmit(email);\n  }\n\n  return (\n    <form onSubmit={handleSubmit} noValidate>\n      <label>\n        Email <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} />\n      </label>\n      {error && <p role="alert">{error}</p>}\n      <button type="submit">Join</button>\n    </form>\n  );\n}\n\nexport default EmailForm;\n`,
      explanation: "noValidate turns off the browser's own popup so your error UI is the only one. Client-side checks improve UX; the server must still validate.",
      tests: [
        test("rejects a bad email", `const onSubmit = mockFn();\nrenderComponent({ onSubmit });\n${type("Email", "not-an-email")}\n${click("Join")}\nexpectText("Please enter a valid email");\nassertEqual(onSubmit.calls.length, 0);`),
        hidden("accepts a good email and rejects edge cases", `const onSubmit = mockFn();\nrenderComponent({ onSubmit });\nconst input = screen.getByLabelText("Email");\nawait userEvent.type(input, "a@b");\n${click("Join")}\nassertEqual(onSubmit.calls.length, 0);\nawait userEvent.clear(input);\nawait userEvent.type(input, "a@b.co");\n${click("Join")}\nassertEqual(onSubmit.calls, [["a@b.co"]]);`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction EmailForm({ onSubmit }) {\n  const [email, setEmail] = useState("");\n  const [error, setError] = useState("");\n  return (<form noValidate onSubmit={(e) => { e.preventDefault(); if (!email.includes("@")) { setError("Please enter a valid email"); return; } onSubmit(email); }}><label>Email <input value={email} onChange={(e) => setEmail(e.target.value)} /></label>{error && <p role="alert">{error}</p>}<button type="submit">Join</button></form>);\n}\nexport default EmailForm;\n`],
    },
    {
      slug: "forms-password-rules",
      title: "Live Password Rules",
      difficulty: "MEDIUM",
      tags: ["forms", "validation", "derived-state"],
      estimatedMinutes: 15,
      description:
        "Make `PasswordRules` render an input labelled `Password` and a `<ul>` of rules that update as the user types. Each `<li>` starts with `✓ ` when met or `✗ ` when not:\n\n- `At least 8 characters`\n- `Contains a number`\n- `Contains an uppercase letter`\n\ne.g. `✗ Contains a number`.",
      requirements: ["Three rules, in order", "Each rule updates live"],
      hints: ["Describe rules as data: [{ label, test: (pw) => boolean }]", "/\\d/.test(pw) and /[A-Z]/.test(pw)"],
      starterCode: formStub("PasswordRules"),
      solutionCode: `import { useState } from "react";\n\nconst RULES = [\n  { label: "At least 8 characters", test: (pw: string) => pw.length >= 8 },\n  { label: "Contains a number", test: (pw: string) => /\\d/.test(pw) },\n  { label: "Contains an uppercase letter", test: (pw: string) => /[A-Z]/.test(pw) },\n];\n\nfunction PasswordRules() {\n  const [password, setPassword] = useState("");\n\n  return (\n    <div>\n      <label>\n        Password <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />\n      </label>\n      <ul>\n        {RULES.map((rule) => (\n          <li key={rule.label}>\n            {rule.test(password) ? "✓" : "✗"} {rule.label}\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nexport default PasswordRules;\n`,
      explanation: "Modelling rules as data means adding a rule is one line, and the rendering code never changes.",
      tests: [
        test("all unmet initially", `renderComponent();\nassertEqual(screen.getAllByRole("listitem").map((li) => li.textContent), ["✗ At least 8 characters", "✗ Contains a number", "✗ Contains an uppercase letter"]);`),
        hidden("updates per rule", `renderComponent();\n${type("Password", "abc1")}\nassertEqual(screen.getAllByRole("listitem").map((li) => li.textContent), ["✗ At least 8 characters", "✓ Contains a number", "✗ Contains an uppercase letter"]);\n${type("Password", "defgH")}\nassert(screen.getAllByRole("listitem").every((li) => li.textContent.startsWith("✓")), "All rules should be met for abc1defgH");`),
      ],
    },
    {
      slug: "forms-confirm-password",
      title: "Confirm Password",
      difficulty: "EASY",
      tags: ["forms", "validation"],
      estimatedMinutes: 12,
      description:
        "Make `ChangePassword` render inputs labelled `New password` and `Confirm password` and a button `Save`.\n\n- When confirm is non-empty and differs, show `<p role=\"alert\">Passwords do not match</p>`.\n- `Save` is disabled until both are non-empty and equal.",
      requirements: ["Mismatch error appears only when confirm has text", "Save enabled only when they match"],
      hints: ["Derive: const mismatch = confirm !== \"\" && confirm !== password;", "const canSave = password !== \"\" && password === confirm;"],
      starterCode: formStub("ChangePassword"),
      solutionCode: `import { useState } from "react";\n\nfunction ChangePassword() {\n  const [password, setPassword] = useState("");\n  const [confirm, setConfirm] = useState("");\n  const mismatch = confirm !== "" && confirm !== password;\n  const canSave = password !== "" && password === confirm;\n\n  return (\n    <div>\n      <label>\n        New password <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />\n      </label>\n      <label>\n        Confirm password <input type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} />\n      </label>\n      {mismatch && <p role="alert">Passwords do not match</p>}\n      <button disabled={!canSave}>Save</button>\n    </div>\n  );\n}\n\nexport default ChangePassword;\n`,
      explanation: "Both the error and the button state are derived from the two inputs, so they update together on every keystroke.",
      tests: [
        test("shows mismatch", `renderComponent();\n${type("New password", "abc123")}\n${type("Confirm password", "abc")}\nexpectText("Passwords do not match");\nassert(screen.getByRole("button", { name: "Save" }).disabled);`),
        hidden("enables save on match and no error before typing", `renderComponent();\n${type("New password", "abc123")}\nassert(!screen.queryByRole("alert"), "No error before confirm is typed");\n${type("Confirm password", "abc123")}\nassert(!screen.queryByRole("alert"));\nassert(!screen.getByRole("button", { name: "Save" }).disabled);`),
      ],
    },
    {
      slug: "forms-disable-submit",
      title: "Disable Submit Until Valid",
      difficulty: "EASY",
      tags: ["forms", "validation", "derived-state"],
      estimatedMinutes: 12,
      description:
        "Make `AgeGate` render inputs labelled `Name` and `Age` (type number), and a `Submit` button that is enabled only when the name is non-empty (after trimming) **and** the age is a whole number from 18 to 120.",
      requirements: ["Disabled until both fields are valid", "Age must be 18–120"],
      hints: ["Store raw strings; parse when validating.", "Number.isInteger(Number(age))"],
      starterCode: formStub("AgeGate"),
      solutionCode: `import { useState } from "react";\n\nfunction AgeGate() {\n  const [name, setName] = useState("");\n  const [age, setAge] = useState("");\n  const ageNumber = Number(age);\n  const isValid = name.trim() !== "" && age !== "" && Number.isInteger(ageNumber) && ageNumber >= 18 && ageNumber <= 120;\n\n  return (\n    <form onSubmit={(e) => e.preventDefault()}>\n      <label>\n        Name <input value={name} onChange={(e) => setName(e.target.value)} />\n      </label>\n      <label>\n        Age <input type="number" value={age} onChange={(e) => setAge(e.target.value)} />\n      </label>\n      <button type="submit" disabled={!isValid}>\n        Submit\n      </button>\n    </form>\n  );\n}\n\nexport default AgeGate;\n`,
      explanation: "A single derived `isValid` combines all the rules; the button just reads it.",
      tests: [
        test("enabled when valid", `renderComponent();\n${type("Name", "Sam")}\n${type("Age", "30")}\nassert(!screen.getByRole("button", { name: "Submit" }).disabled);`),
        hidden("rejects bad ages and blank names", `renderComponent();\nconst btn = () => screen.getByRole("button", { name: "Submit" });\n${type("Age", "17")}\n${type("Name", "  ")}\nassert(btn().disabled, "Blank name / age 17 must be invalid");\nawait userEvent.clear(screen.getByLabelText("Age"));\n${type("Age", "121")}\n${type("Name", "Al")}\nassert(btn().disabled, "121 must be invalid");\nawait userEvent.clear(screen.getByLabelText("Age"));\n${type("Age", "18")}\nassert(!btn().disabled, "18 should be valid");`),
      ],
    },
    {
      slug: "forms-validate-on-blur",
      title: "Validate on Blur",
      difficulty: "MEDIUM",
      tags: ["forms", "validation", "focus"],
      estimatedMinutes: 15,
      description:
        "Showing an error while someone is still typing is annoying. Make `EmailField` show `<p role=\"alert\">Email must contain @</p>` only **after the field has been blurred once** (\"touched\") and the value has no `@`.\n\nOnce touched, the error updates live as they keep typing.",
      requirements: ["No error before the first blur", "Error after blur if invalid", "Error disappears live once fixed"],
      hints: ["Track a separate `touched` boolean in state.", "onBlur={() => setTouched(true)}", "Show the error when touched && !value.includes(\"@\")"],
      starterCode: formStub("EmailField"),
      solutionCode: `import { useState } from "react";\n\nfunction EmailField() {\n  const [value, setValue] = useState("");\n  const [touched, setTouched] = useState(false);\n  const error = touched && !value.includes("@") ? "Email must contain @" : null;\n\n  return (\n    <div>\n      <label>\n        Email\n        <input\n          value={value}\n          aria-invalid={error ? true : undefined}\n          onChange={(e) => setValue(e.target.value)}\n          onBlur={() => setTouched(true)}\n        />\n      </label>\n      {error && <p role="alert">{error}</p>}\n    </div>\n  );\n}\n\nexport default EmailField;\n`,
      explanation: "'Touched' state separates 'the user hasn't finished yet' from 'the user left the field invalid'. Form libraries track exactly this per field.",
      tests: [
        test("no error while typing first time", `renderComponent();\n${type("Email", "abc")}\nassert(!screen.queryByRole("alert"), "Don't show the error before the field is blurred");`),
        hidden("error after blur, cleared live", `renderComponent();\nconst input = screen.getByLabelText("Email");\nawait userEvent.type(input, "abc");\nfireEvent.blur(input);\nexpectText("Email must contain @");\nawait userEvent.type(input, "@x.io");\nassert(!screen.queryByRole("alert"), "The error should clear as soon as the value is valid");`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction EmailField() {\n  const [value, setValue] = useState("");\n  return (<div><label>Email<input value={value} onChange={(e) => setValue(e.target.value)} /></label>{value && !value.includes("@") && <p role="alert">Email must contain @</p>}</div>);\n}\nexport default EmailField;\n`],
    },
    {
      slug: "forms-number-input",
      title: "Number Input",
      difficulty: "EASY",
      tags: ["forms", "number-input", "validation"],
      estimatedMinutes: 10,
      description:
        "Make `TicketOrder` accept `price`. Render a number input labelled `Tickets` (starting at `1`). If the value is below 1 or not a whole number, show `<p role=\"alert\">Enter at least 1 ticket</p>`; otherwise show `<p>Total: ${total}</p>` with two decimals.",
      requirements: ["Starts at 1", "Shows total for valid input", "Error for 0, negatives, empty or fractions"],
      hints: ["Keep the raw string in state (\"1\") so the user can clear the field.", "const n = Number(value); Number.isInteger(n) && n >= 1"],
      starterCode: formStub("TicketOrder", "{ price }: { price: number }"),
      solutionCode: `import { useState } from "react";\n\nfunction TicketOrder({ price }: { price: number }) {\n  const [value, setValue] = useState("1");\n  const n = Number(value);\n  const valid = value !== "" && Number.isInteger(n) && n >= 1;\n\n  return (\n    <div>\n      <label>\n        Tickets <input type="number" min={1} value={value} onChange={(e) => setValue(e.target.value)} />\n      </label>\n      {valid ? <p>Total: \${(n * price).toFixed(2)}</p> : <p role="alert">Enter at least 1 ticket</p>}\n    </div>\n  );\n}\n\nexport default TicketOrder;\n`,
      explanation: "Even type='number' inputs give you strings. Storing the string avoids fighting the user while they edit (e.g. clearing the field to type a new number).",
      tests: [
        test("totals valid input", `renderComponent({ price: 12.5 });\nexpectText("Total: $12.50");\nconst input = screen.getByLabelText("Tickets");\nawait userEvent.clear(input);\nawait userEvent.type(input, "3");\nexpectText("Total: $37.50");`),
        hidden("errors for invalid input", `renderComponent({ price: 10 });\nconst input = screen.getByLabelText("Tickets");\nfor (const bad of ["", "0", "-2", "2.5"]) {\n  fireEvent.change(input, { target: { value: bad } });\n  expectText("Enter at least 1 ticket");\n}\nfireEvent.change(input, { target: { value: "4" } });\nexpectText("Total: $40.00");`),
      ],
    },
    {
      slug: "forms-dynamic-fields",
      title: "Add and Remove Form Fields",
      difficulty: "MEDIUM",
      tags: ["forms", "arrays", "dynamic-forms"],
      estimatedMinutes: 20,
      description:
        "Make `PhoneNumbers` accept `onSubmit`. It starts with **one** empty phone input. Requirements:\n\n- Each input is labelled `Phone 1`, `Phone 2`, ...\n- `Add phone` appends an empty input.\n- Each input has a `Remove` button (`aria-label=\"Remove phone N\"`), except when only one input remains.\n- Submitting (button `Save`) calls `onSubmit` with the non-empty numbers, trimmed.",
      requirements: ["Starts with one field", "Add/remove fields", "Can't remove the last field", "Submits non-empty values"],
      hints: [
        "Store an array of { id, value } so React can keep inputs stable when one is removed.",
        "Update one field with map, remove with filter.",
        "fields.length > 1 && <button ...>Remove</button>",
      ],
      starterCode: formStub("PhoneNumbers", "{ onSubmit }: { onSubmit: (phones: string[]) => void }"),
      solutionCode: `import { useState, type FormEvent } from "react";\n\ninterface Field {\n  id: number;\n  value: string;\n}\n\nlet nextId = 1;\nconst newField = (): Field => ({ id: nextId++, value: "" });\n\nfunction PhoneNumbers({ onSubmit }: { onSubmit: (phones: string[]) => void }) {\n  const [fields, setFields] = useState<Field[]>(() => [newField()]);\n\n  function update(id: number, value: string) {\n    setFields((prev) => prev.map((f) => (f.id === id ? { ...f, value } : f)));\n  }\n\n  function remove(id: number) {\n    setFields((prev) => prev.filter((f) => f.id !== id));\n  }\n\n  function handleSubmit(event: FormEvent) {\n    event.preventDefault();\n    onSubmit(fields.map((f) => f.value.trim()).filter(Boolean));\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      {fields.map((field, index) => (\n        <div key={field.id}>\n          <label>\n            Phone {index + 1}\n            <input value={field.value} onChange={(e) => update(field.id, e.target.value)} />\n          </label>\n          {fields.length > 1 && (\n            <button type="button" aria-label={\`Remove phone \${index + 1}\`} onClick={() => remove(field.id)}>\n              Remove\n            </button>\n          )}\n        </div>\n      ))}\n      <button type="button" onClick={() => setFields((prev) => [...prev, newField()])}>\n        Add phone\n      </button>\n      <button type="submit">Save</button>\n    </form>\n  );\n}\n\nexport default PhoneNumbers;\n`,
      explanation: "Giving each field a stable id (rather than using the index as key) keeps React from mixing up input values when a field in the middle is removed.",
      commonMistakes: ["key={index}: removing field 1 makes field 2's input show field 1's DOM state in some cases."],
      tests: [
        test("adds fields and submits", `const onSubmit = mockFn();\nrenderComponent({ onSubmit });\n${type("Phone 1", "111")}\n${click("Add phone")}\n${type("Phone 2", " 222 ")}\n${click("Save")}\nassertEqual(onSubmit.calls, [[["111", "222"]]]);`),
        hidden("removes the right field and keeps one", `const onSubmit = mockFn();\nrenderComponent({ onSubmit });\nassert(!screen.queryByRole("button", { name: "Remove phone 1" }), "Can't remove the only field");\n${click("Add phone")}\n${click("Add phone")}\n${type("Phone 1", "a")}\n${type("Phone 2", "b")}\n${type("Phone 3", "c")}\nfireEvent.click(screen.getByRole("button", { name: "Remove phone 2" }));\nassertEqual(screen.getByLabelText("Phone 2").value, "c");\n${click("Save")}\nassertEqual(onSubmit.calls, [[["a", "c"]]]);`),
      ],
    },
    {
      slug: "forms-accessible-login",
      title: "Login Form With Accessible Errors",
      difficulty: "MEDIUM",
      tags: ["forms", "validation", "accessibility"],
      estimatedMinutes: 20,
      description:
        "Make `LoginForm` accept `onLogin`, with inputs labelled `Email` and `Password` and a submit button `Sign in`. On submit, validate both fields:\n\n- empty email → `Email is required`\n- empty password → `Password is required`\n\nShow each error in a `<p id=\"email-error\">` / `<p id=\"password-error\">` under its field, and link it to the input with `aria-describedby` and `aria-invalid=\"true\"`. If both are filled, call `onLogin({ email, password })`.",
      requirements: ["Per-field errors", "aria-invalid and aria-describedby on invalid fields", "Calls onLogin only when valid"],
      hints: [
        "Store errors as an object: { email?: string; password?: string }",
        "aria-describedby={errors.email ? \"email-error\" : undefined}",
        "Compute the errors in the submit handler; only call onLogin when the object is empty.",
      ],
      starterCode: formStub("LoginForm", "{ onLogin }: { onLogin: (creds: { email: string; password: string }) => void }"),
      solutionCode: `import { useState, type FormEvent } from "react";\n\ninterface Errors {\n  email?: string;\n  password?: string;\n}\n\nfunction LoginForm({ onLogin }: { onLogin: (creds: { email: string; password: string }) => void }) {\n  const [email, setEmail] = useState("");\n  const [password, setPassword] = useState("");\n  const [errors, setErrors] = useState<Errors>({});\n\n  function handleSubmit(event: FormEvent) {\n    event.preventDefault();\n    const next: Errors = {};\n    if (!email.trim()) next.email = "Email is required";\n    if (!password) next.password = "Password is required";\n    setErrors(next);\n    if (Object.keys(next).length === 0) onLogin({ email, password });\n  }\n\n  return (\n    <form onSubmit={handleSubmit} noValidate>\n      <label htmlFor="email">Email</label>\n      <input\n        id="email"\n        type="email"\n        value={email}\n        onChange={(e) => setEmail(e.target.value)}\n        aria-invalid={errors.email ? true : undefined}\n        aria-describedby={errors.email ? "email-error" : undefined}\n      />\n      {errors.email && <p id="email-error">{errors.email}</p>}\n\n      <label htmlFor="password">Password</label>\n      <input\n        id="password"\n        type="password"\n        value={password}\n        onChange={(e) => setPassword(e.target.value)}\n        aria-invalid={errors.password ? true : undefined}\n        aria-describedby={errors.password ? "password-error" : undefined}\n      />\n      {errors.password && <p id="password-error">{errors.password}</p>}\n\n      <button type="submit">Sign in</button>\n    </form>\n  );\n}\n\nexport default LoginForm;\n`,
      explanation: "aria-describedby makes screen readers read the error when the field is focused, and aria-invalid announces the field as invalid. Visual-only errors are invisible to many users.",
      tests: [
        test("shows both errors", `const onLogin = mockFn();\nrenderComponent({ onLogin });\n${click("Sign in")}\nexpectText("Email is required");\nexpectText("Password is required");\nassertEqual(onLogin.calls.length, 0);`),
        hidden("errors are linked to inputs", `renderComponent({ onLogin: () => {} });\n${type("Email", "a@b.co")}\n${click("Sign in")}\nconst pw = screen.getByLabelText("Password");\nassertEqual(pw.getAttribute("aria-invalid"), "true");\nassertEqual(pw.getAttribute("aria-describedby"), "password-error");\nassert(!screen.getByLabelText("Email").hasAttribute("aria-invalid"), "Email is valid now");\nexpectNoText("Email is required");`),
        hidden("logs in when valid", `const onLogin = mockFn();\nrenderComponent({ onLogin });\n${type("Email", "a@b.co")}\n${type("Password", "pw")}\n${click("Sign in")}\nassertEqual(onLogin.calls, [[{ email: "a@b.co", password: "pw" }]]);`),
      ],
    },
    {
      slug: "forms-multi-step",
      title: "Multi-Step Form",
      difficulty: "HARD",
      tags: ["forms", "multi-step", "useState"],
      estimatedMinutes: 30,
      description:
        "Make `SignupWizard` accept `onSubmit` and guide the user through three steps. Show `<p>Step {n} of 3</p>` on every step.\n\n1. Input labelled `Name`, button `Next` (disabled while the name is blank).\n2. Input labelled `Email`, buttons `Back` and `Next` (Next disabled while email is blank).\n3. Review: `<p>Name: {name}</p>`, `<p>Email: {email}</p>`, buttons `Back` and `Submit`. Submit calls `onSubmit({ name, email })`.\n\nGoing **Back** must keep what was typed.",
      requirements: ["Three steps with progress text", "Next disabled until the step is valid", "Back preserves values", "Submit sends both values"],
      hints: [
        "Keep the step number and all form values in the wizard (not in each step), so values survive going back.",
        "Render the current step with conditionals on `step`.",
        "Each step can be its own small component that receives values and setters as props.",
      ],
      starterCode: formStub("SignupWizard", "{ onSubmit }: { onSubmit: (data: { name: string; email: string }) => void }"),
      solutionCode: `import { useState } from "react";\n\nfunction SignupWizard({ onSubmit }: { onSubmit: (data: { name: string; email: string }) => void }) {\n  const [step, setStep] = useState(1);\n  const [name, setName] = useState("");\n  const [email, setEmail] = useState("");\n\n  const next = () => setStep((s) => s + 1);\n  const back = () => setStep((s) => s - 1);\n\n  return (\n    <div>\n      <p>Step {step} of 3</p>\n\n      {step === 1 && (\n        <div>\n          <label>\n            Name <input value={name} onChange={(e) => setName(e.target.value)} />\n          </label>\n          <button disabled={!name.trim()} onClick={next}>Next</button>\n        </div>\n      )}\n\n      {step === 2 && (\n        <div>\n          <label>\n            Email <input value={email} onChange={(e) => setEmail(e.target.value)} />\n          </label>\n          <button onClick={back}>Back</button>\n          <button disabled={!email.trim()} onClick={next}>Next</button>\n        </div>\n      )}\n\n      {step === 3 && (\n        <div>\n          <p>Name: {name}</p>\n          <p>Email: {email}</p>\n          <button onClick={back}>Back</button>\n          <button onClick={() => onSubmit({ name, email })}>Submit</button>\n        </div>\n      )}\n    </div>\n  );\n}\n\nexport default SignupWizard;\n`,
      explanation: "State that must outlive a step belongs to the component that outlives the steps. If each step owned its own state, it would be lost when the step unmounts.",
      commonMistakes: ["Keeping each step's input state inside the step component — it resets when you navigate away and back."],
      tests: [
        test("walks through the steps", `const onSubmit = mockFn();\nrenderComponent({ onSubmit });\nexpectText("Step 1 of 3");\nassert(screen.getByRole("button", { name: "Next" }).disabled);\n${type("Name", "Rin")}\n${click("Next")}\nexpectText("Step 2 of 3");\n${type("Email", "rin@x.io")}\n${click("Next")}\nexpectText("Name: Rin");\nexpectText("Email: rin@x.io");\n${click("Submit")}\nassertEqual(onSubmit.calls, [[{ name: "Rin", email: "rin@x.io" }]]);`),
        hidden("back keeps values", `renderComponent({ onSubmit: () => {} });\n${type("Name", "Rin")}\n${click("Next")}\n${type("Email", "r@x.io")}\n${click("Next")}\n${click("Back")}\nassertEqual(screen.getByLabelText("Email").value, "r@x.io");\n${click("Back")}\nassertEqual(screen.getByLabelText("Name").value, "Rin");\nexpectText("Step 1 of 3");`),
        hidden("step 2 requires an email", `renderComponent({ onSubmit: () => {} });\n${type("Name", "Rin")}\n${click("Next")}\nassert(screen.getByRole("button", { name: "Next" }).disabled, "Next should be disabled with an empty email");`),
      ],
    },
  ],
};
