import { hidden, test, type CategoryBank } from "./types.js";

const click = (name: string) => `fireEvent.click(screen.getByRole("button", { name: ${JSON.stringify(name)} }));`;

export const communication: CategoryBank = {
  category: "Component Communication",
  level: 10,
  type: "COMPONENT",
  prerequisites: ["Props", "useState", "Events"],
  problems: [
    {
      slug: "parent-to-child",
      title: "Parent to Child Communication",
      difficulty: "BEGINNER",
      tags: ["props", "composition"],
      estimatedMinutes: 8,
      description:
        "Complete `Child({ user })` so it renders `<p>{user.name}</p>`, and make `Parent` (the default export) create `const user = { name: \"Jordan\" }` and render `<Child user={user} />`. Export `Child`.",
      requirements: ["Parent owns the data", "Child renders what it receives"],
      hints: ["Data flows down through props.", "<Child user={user} />"],
      starterCode: `export function Child(props: { user: { name: string } }) {\n  // render the passed-down user's name\n  return null;\n}\n\nfunction Parent() {\n  // Write your solution here — render <Child /> with a user prop\n  return null;\n}\n\nexport default Parent;\n`,
      solutionCode: `export function Child({ user }: { user: { name: string } }) {\n  return <p>{user.name}</p>;\n}\n\nfunction Parent() {\n  const user = { name: "Jordan" };\n  return <Child user={user} />;\n}\n\nexport default Parent;\n`,
      explanation: "The parent owns the data and hands it to whichever child needs it.",
      tests: [
        test("renders the name via the child", `renderComponent();\nexpectText("Jordan");`),
        hidden("Child renders any user", `render(<userExports.Child user={{ name: "Mo" }} />);\nexpectText("Mo");`),
      ],
      wrongSolutions: [`export function Child() {\n  return <p>Jordan</p>;\n}\n\nfunction Parent() {\n  return <Child />;\n}\n\nexport default Parent;\n`],
    },
    {
      slug: "child-to-parent",
      title: "Send Data From Child to Parent",
      difficulty: "EASY",
      tags: ["props", "callbacks", "lifting-state-up"],
      estimatedMinutes: 10,
      description:
        "`Child` renders a `Send Message` button. When it's clicked, `Parent` should display `Hello from child`.\n\nA child can't change its parent's state directly — the parent passes down a callback, and the child calls it with the message. Export `Child`, which takes an `onSend(message: string)` prop.",
      requirements: ["Child calls onSend('Hello from child')", "Parent stores and shows the message", "Nothing shows before the click"],
      hints: ["Parent: const [message, setMessage] = useState(\"\");", "<Child onSend={setMessage} />", "Child: <button onClick={() => onSend(\"Hello from child\")}>"],
      starterCode: `import { useState } from "react";\n\nexport function Child(props: { onSend: (message: string) => void }) {\n  return null;\n}\n\nfunction Parent() {\n  // Write your solution here\n  return null;\n}\n\nexport default Parent;\n`,
      solutionCode: `import { useState } from "react";\n\nexport function Child({ onSend }: { onSend: (message: string) => void }) {\n  return <button onClick={() => onSend("Hello from child")}>Send Message</button>;\n}\n\nfunction Parent() {\n  const [message, setMessage] = useState("");\n\n  return (\n    <div>\n      <Child onSend={setMessage} />\n      {message && <p>{message}</p>}\n    </div>\n  );\n}\n\nexport default Parent;\n`,
      explanation: "Data goes down as props; events come back up as callback calls. The parent owns the state, the child just reports what happened.",
      tests: [
        test("shows the message after clicking", `renderComponent();\nexpectNoText("Hello from child");\n${click("Send Message")}\nexpectText("Hello from child");`),
        hidden("Child reports through its callback", `const onSend = mockFn();\nrender(<userExports.Child onSend={onSend} />);\n${click("Send Message")}\nassertEqual(onSend.calls, [["Hello from child"]]);`),
      ],
    },
    {
      slug: "comm-controlled-switch",
      title: "A Controlled Child Component",
      difficulty: "EASY",
      tags: ["controlled-components", "accessibility", "callbacks"],
      estimatedMinutes: 12,
      description:
        "Build an exported, **stateless** `Switch({ label, checked, onChange })` that renders `<button role=\"switch\" aria-checked={checked}>{label}</button>` and calls `onChange(!checked)` when clicked.\n\nThen make `App` keep a `wifi` boolean (starting `false`), render `<Switch label=\"Wi-Fi\" ... />`, and show `<p>Wi-Fi is on</p>` / `<p>Wi-Fi is off</p>`.",
      requirements: ["Switch has no state of its own", "App controls it", "aria-checked reflects the value"],
      hints: ["A controlled component gets its value from props and reports changes up.", "In App: <Switch checked={wifi} onChange={setWifi} label=\"Wi-Fi\" />"],
      starterCode: `import { useState } from "react";\n\ninterface SwitchProps {\n  label: string;\n  checked: boolean;\n  onChange: (checked: boolean) => void;\n}\n\nexport function Switch(props: SwitchProps) {\n  return null;\n}\n\nfunction App() {\n  return null;\n}\n\nexport default App;\n`,
      solutionCode: `import { useState } from "react";\n\ninterface SwitchProps {\n  label: string;\n  checked: boolean;\n  onChange: (checked: boolean) => void;\n}\n\nexport function Switch({ label, checked, onChange }: SwitchProps) {\n  return (\n    <button role="switch" aria-checked={checked} onClick={() => onChange(!checked)}>\n      {label}\n    </button>\n  );\n}\n\nfunction App() {\n  const [wifi, setWifi] = useState(false);\n\n  return (\n    <div>\n      <Switch label="Wi-Fi" checked={wifi} onChange={setWifi} />\n      <p>Wi-Fi is {wifi ? "on" : "off"}</p>\n    </div>\n  );\n}\n\nexport default App;\n`,
      explanation: "Controlled components are predictable: the parent always knows the value, can reset or validate it, and can share it with other components.",
      tests: [
        test("toggles Wi-Fi", `renderComponent();\nexpectText("Wi-Fi is off");\nfireEvent.click(screen.getByRole("switch", { name: "Wi-Fi" }));\nexpectText("Wi-Fi is on");\nassertEqual(screen.getByRole("switch").getAttribute("aria-checked"), "true");`),
        hidden("Switch is fully controlled", `const onChange = mockFn();\nrender(<userExports.Switch label="Dark mode" checked={true} onChange={onChange} />);\nconst sw = screen.getByRole("switch", { name: "Dark mode" });\nfireEvent.click(sw);\nassertEqual(onChange.calls, [[false]]);\nassertEqual(sw.getAttribute("aria-checked"), "true", "Switch must not change itself — the parent decides");`),
      ],
      wrongSolutions: [`import { useState } from "react";\nexport function Switch({ label, checked, onChange }) {\n  const [on, setOn] = useState(checked);\n  return <button role="switch" aria-checked={on} onClick={() => { setOn(!on); onChange(!on); }}>{label}</button>;\n}\nfunction App() {\n  const [wifi, setWifi] = useState(false);\n  return (<div><Switch label="Wi-Fi" checked={wifi} onChange={setWifi} /><p>Wi-Fi is {wifi ? "on" : "off"}</p></div>);\n}\nexport default App;\n`],
    },
    {
      slug: "comm-siblings",
      title: "Sibling Communication Through a Parent",
      difficulty: "EASY",
      tags: ["lifting-state-up", "composition"],
      estimatedMinutes: 15,
      description:
        "`App` receives `items` (strings). Build two exported siblings:\n\n- `SearchBox({ query, onQueryChange })` → input labelled `Search`\n- `Results({ items })` → `<p>{n} results</p>` plus a `<ul>` of the items\n\nSiblings can't talk directly, so `App` owns the `query` state, passes it to SearchBox, and passes the **filtered** items (case-insensitive) to Results.",
      requirements: ["Query lives in App", "SearchBox is controlled", "Results shows the filtered items and count"],
      hints: ["Lift state to the closest common parent.", "const filtered = items.filter((i) => i.toLowerCase().includes(query.toLowerCase()));"],
      starterCode: `import { useState } from "react";\n\nexport function SearchBox(props: { query: string; onQueryChange: (q: string) => void }) {\n  return null;\n}\n\nexport function Results(props: { items: string[] }) {\n  return null;\n}\n\nfunction App({ items }: { items: string[] }) {\n  return null;\n}\n\nexport default App;\n`,
      solutionCode: `import { useState } from "react";\n\nexport function SearchBox({ query, onQueryChange }: { query: string; onQueryChange: (q: string) => void }) {\n  return (\n    <label>\n      Search <input value={query} onChange={(e) => onQueryChange(e.target.value)} />\n    </label>\n  );\n}\n\nexport function Results({ items }: { items: string[] }) {\n  return (\n    <div>\n      <p>{items.length} results</p>\n      <ul>\n        {items.map((item) => (\n          <li key={item}>{item}</li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nfunction App({ items }: { items: string[] }) {\n  const [query, setQuery] = useState("");\n  const filtered = items.filter((item) => item.toLowerCase().includes(query.toLowerCase()));\n\n  return (\n    <div>\n      <SearchBox query={query} onQueryChange={setQuery} />\n      <Results items={filtered} />\n    </div>\n  );\n}\n\nexport default App;\n`,
      explanation: "When two components need the same state, move it up to their closest common parent, then pass it down (and pass setters or callbacks down to change it).",
      tests: [
        test("filters results", `renderComponent({ items: ["React", "Redux", "Vue"] });\nexpectText("3 results");\nawait userEvent.type(screen.getByLabelText("Search"), "re");\nexpectText("2 results");`),
        hidden("children are reusable on their own", `const onQueryChange = mockFn();\nrender(<userExports.SearchBox query="ab" onQueryChange={onQueryChange} />);\nassertEqual(screen.getByLabelText("Search").value, "ab");\nfireEvent.change(screen.getByLabelText("Search"), { target: { value: "abc" } });\nassertEqual(onQueryChange.calls, [["abc"]]);`),
        hidden("Results renders what it's given", `render(<userExports.Results items={["x", "y"]} />);\nexpectText("2 results");\nassertEqual(screen.getAllByRole("listitem").length, 2);`),
      ],
    },
    {
      slug: "comm-multiple-callbacks",
      title: "A Child With Several Callbacks",
      difficulty: "MEDIUM",
      tags: ["callbacks", "lists", "lifting-state-up"],
      estimatedMinutes: 20,
      description:
        "Build an exported `TodoItem({ todo, onToggle, onDelete })` that renders an `<li>` with a checkbox labelled with `todo.title` (checked = `todo.done`) and a `Delete` button. It calls `onToggle(todo.id)` / `onDelete(todo.id)`.\n\nThen make `TodoList` (default) own this state:\n\n```\n[{ id: 1, title: \"Write\", done: false }, { id: 2, title: \"Test\", done: false }]\n```\n\nand render a `TodoItem` for each one, wiring both callbacks to update its state.",
      requirements: ["TodoItem is stateless and reports via callbacks", "TodoList owns the todos", "Toggle and delete work per item"],
      hints: ["The child only knows its own todo; the parent knows how to change the list.", "Pass functions that take an id: onToggle={toggle} where toggle = (id) => ..."],
      starterCode: `import { useState } from "react";\n\ninterface Todo {\n  id: number;\n  title: string;\n  done: boolean;\n}\n\nexport function TodoItem(props: { todo: Todo; onToggle: (id: number) => void; onDelete: (id: number) => void }) {\n  return null;\n}\n\nfunction TodoList() {\n  return null;\n}\n\nexport default TodoList;\n`,
      solutionCode: `import { useState } from "react";\n\ninterface Todo {\n  id: number;\n  title: string;\n  done: boolean;\n}\n\nexport function TodoItem({ todo, onToggle, onDelete }: { todo: Todo; onToggle: (id: number) => void; onDelete: (id: number) => void }) {\n  return (\n    <li>\n      <label>\n        <input type="checkbox" checked={todo.done} onChange={() => onToggle(todo.id)} /> {todo.title}\n      </label>\n      <button onClick={() => onDelete(todo.id)}>Delete</button>\n    </li>\n  );\n}\n\nfunction TodoList() {\n  const [todos, setTodos] = useState<Todo[]>([\n    { id: 1, title: "Write", done: false },\n    { id: 2, title: "Test", done: false },\n  ]);\n\n  const toggle = (id: number) => setTodos((prev) => prev.map((t) => (t.id === id ? { ...t, done: !t.done } : t)));\n  const remove = (id: number) => setTodos((prev) => prev.filter((t) => t.id !== id));\n\n  return (\n    <ul>\n      {todos.map((todo) => (\n        <TodoItem key={todo.id} todo={todo} onToggle={toggle} onDelete={remove} />\n      ))}\n    </ul>\n  );\n}\n\nexport default TodoList;\n`,
      explanation: "Keeping list items stateless means there's exactly one copy of the data (in the parent). Items describe events; the parent decides what they mean.",
      tests: [
        test("toggles and deletes", `renderComponent();\nfireEvent.click(screen.getByRole("checkbox", { name: "Write" }));\nassert(screen.getByRole("checkbox", { name: "Write" }).checked);\nconst test = screen.getByRole("checkbox", { name: "Test" }).closest("li");\nfireEvent.click(within(test).getByRole("button", { name: "Delete" }));\nassertEqual(screen.getAllByRole("listitem").length, 1);`),
        hidden("TodoItem only reports", `const onToggle = mockFn();\nconst onDelete = mockFn();\nrender(<ul><userExports.TodoItem todo={{ id: 7, title: "Ship", done: false }} onToggle={onToggle} onDelete={onDelete} /></ul>);\nfireEvent.click(screen.getByRole("checkbox", { name: "Ship" }));\nfireEvent.click(screen.getByRole("button", { name: "Delete" }));\nassertEqual(onToggle.calls, [[7]]);\nassertEqual(onDelete.calls, [[7]]);\nassert(!screen.getByRole("checkbox", { name: "Ship" }).checked, "TodoItem must not keep its own state");`),
      ],
    },
    {
      slug: "comm-reusable-modal",
      title: "Reusable Modal With Close Controls",
      difficulty: "MEDIUM",
      tags: ["children", "callbacks", "accessibility", "keyboard"],
      estimatedMinutes: 20,
      description:
        "Build an exported `Modal({ isOpen, onClose, title, children })`:\n\n- renders nothing when closed\n- when open, renders `<div role=\"dialog\" aria-modal=\"true\" aria-label={title}>` with an `<h2>`, the children, and a `Close` button\n- clicking `Close` **or** pressing `Escape` inside the dialog calls `onClose()`\n\nThen make `App` render an `Open settings` button that opens a modal titled `Settings` containing `<p>Settings go here</p>`, and close it via `onClose`.",
      requirements: ["Modal is controlled by isOpen", "Close button and Escape both call onClose", "App wires it up"],
      hints: ["onKeyDown on the dialog element: if (e.key === \"Escape\") onClose();", "App: const [open, setOpen] = useState(false);"],
      starterCode: `import { useState, type ReactNode } from "react";\n\ninterface ModalProps {\n  isOpen: boolean;\n  onClose: () => void;\n  title: string;\n  children: ReactNode;\n}\n\nexport function Modal(props: ModalProps) {\n  return null;\n}\n\nfunction App() {\n  return null;\n}\n\nexport default App;\n`,
      solutionCode: `import { useState, type ReactNode } from "react";\n\ninterface ModalProps {\n  isOpen: boolean;\n  onClose: () => void;\n  title: string;\n  children: ReactNode;\n}\n\nexport function Modal({ isOpen, onClose, title, children }: ModalProps) {\n  if (!isOpen) return null;\n\n  return (\n    <div\n      role="dialog"\n      aria-modal="true"\n      aria-label={title}\n      onKeyDown={(e) => {\n        if (e.key === "Escape") onClose();\n      }}\n    >\n      <h2>{title}</h2>\n      {children}\n      <button onClick={onClose}>Close</button>\n    </div>\n  );\n}\n\nfunction App() {\n  const [open, setOpen] = useState(false);\n\n  return (\n    <div>\n      <button onClick={() => setOpen(true)}>Open settings</button>\n      <Modal isOpen={open} onClose={() => setOpen(false)} title="Settings">\n        <p>Settings go here</p>\n      </Modal>\n    </div>\n  );\n}\n\nexport default App;\n`,
      explanation: "The modal doesn't decide when it's open — the parent does. That makes it reusable: any component can open it, and closing is just a request (onClose) the parent can honour.",
      tests: [
        test("opens and closes", `renderComponent();\nassert(!screen.queryByRole("dialog"));\n${click("Open settings")}\nwithin(screen.getByRole("dialog", { name: "Settings" })).getByText("Settings go here");\n${click("Close")}\nassert(!screen.queryByRole("dialog"), "The dialog should close");`),
        hidden("Escape closes", `const onClose = mockFn();\nrender(<userExports.Modal isOpen onClose={onClose} title="Info"><p>Body</p></userExports.Modal>);\nfireEvent.keyDown(screen.getByRole("dialog", { name: "Info" }), { key: "Escape" });\nassertEqual(onClose.calls.length, 1);\nassertEqual(screen.getByRole("dialog").getAttribute("aria-modal"), "true");`),
      ],
    },
    {
      slug: "comm-lift-state-temperature",
      title: "Lift State Up: Synced Temperature Inputs",
      difficulty: "HARD",
      tags: ["lifting-state-up", "controlled-components", "derived-state"],
      estimatedMinutes: 25,
      description:
        "Build an exported, stateless `TemperatureInput({ scale, value, onChange })` that renders an input labelled `Celsius` (scale `\"c\"`) or `Fahrenheit` (scale `\"f\"`).\n\nThen make `Converter` (default) render **both** inputs, kept in sync: typing in either one updates the other, rounded to one decimal (`100` °C ↔ `212.0` °F). Clearing one clears the other.\n\nStore only **one** source of truth: the last edited value and which scale it was typed in. Derive the other.",
      requirements: ["Both inputs stay in sync", "The input being typed in shows exactly what was typed", "Single source of truth"],
      hints: [
        "State: { scale: \"c\" | \"f\", value: string }.",
        "If the user typed in Celsius, Celsius shows value and Fahrenheit shows the converted value — and vice versa.",
        "Write helpers toCelsius(f) and toFahrenheit(c), and a tryConvert(value, fn) that returns \"\" for invalid input.",
      ],
      starterCode: `import { useState } from "react";\n\ntype Scale = "c" | "f";\n\nexport function TemperatureInput(props: { scale: Scale; value: string; onChange: (value: string) => void }) {\n  return null;\n}\n\nfunction Converter() {\n  return null;\n}\n\nexport default Converter;\n`,
      solutionCode: `import { useState } from "react";\n\ntype Scale = "c" | "f";\n\nconst NAMES: Record<Scale, string> = { c: "Celsius", f: "Fahrenheit" };\n\nconst toCelsius = (f: number) => ((f - 32) * 5) / 9;\nconst toFahrenheit = (c: number) => (c * 9) / 5 + 32;\n\nfunction tryConvert(value: string, convert: (n: number) => number) {\n  const n = parseFloat(value);\n  if (Number.isNaN(n)) return "";\n  return convert(n).toFixed(1);\n}\n\nexport function TemperatureInput({ scale, value, onChange }: { scale: Scale; value: string; onChange: (value: string) => void }) {\n  return (\n    <label>\n      {NAMES[scale]}\n      <input value={value} onChange={(e) => onChange(e.target.value)} />\n    </label>\n  );\n}\n\nfunction Converter() {\n  const [state, setState] = useState<{ scale: Scale; value: string }>({ scale: "c", value: "" });\n\n  const celsius = state.scale === "c" ? state.value : tryConvert(state.value, toCelsius);\n  const fahrenheit = state.scale === "f" ? state.value : tryConvert(state.value, toFahrenheit);\n\n  return (\n    <div>\n      <TemperatureInput scale="c" value={celsius} onChange={(value) => setState({ scale: "c", value })} />\n      <TemperatureInput scale="f" value={fahrenheit} onChange={(value) => setState({ scale: "f", value })} />\n    </div>\n  );\n}\n\nexport default Converter;\n`,
      explanation: "Storing both temperatures would let them drift apart. Storing one value plus its scale, and deriving the other, guarantees they always agree — this is the classic 'lifting state up' example from the React docs.",
      tests: [
        test("Celsius updates Fahrenheit", `renderComponent();\nawait userEvent.type(screen.getByLabelText("Celsius"), "100");\nassertEqual(screen.getByLabelText("Fahrenheit").value, "212.0");`),
        hidden("Fahrenheit updates Celsius and keeps raw input", `renderComponent();\nawait userEvent.type(screen.getByLabelText("Fahrenheit"), "32");\nassertEqual(screen.getByLabelText("Celsius").value, "0.0");\nassertEqual(screen.getByLabelText("Fahrenheit").value, "32");\nawait userEvent.clear(screen.getByLabelText("Fahrenheit"));\nassertEqual(screen.getByLabelText("Celsius").value, "");`),
        hidden("TemperatureInput is controlled", `const onChange = mockFn();\nrender(<userExports.TemperatureInput scale="f" value="50" onChange={onChange} />);\nassertEqual(screen.getByLabelText("Fahrenheit").value, "50");\nfireEvent.change(screen.getByLabelText("Fahrenheit"), { target: { value: "51" } });\nassertEqual(onChange.calls, [["51"]]);`),
      ],
    },
    {
      slug: "comm-reset-with-key",
      title: "Reset a Child's State With a Key",
      difficulty: "MEDIUM",
      tags: ["keys", "state-preservation"],
      estimatedMinutes: 15,
      description:
        "The exported `Counter` keeps its own count (starts at 0, button `+1`, shows `<p>Count: {n}</p>`). Don't change Counter.\n\nMake `Scoreboard` render a `Counter` and a `Reset` button that resets the counter to 0 **without adding props to Counter**.\n\nReact keeps a component's state while it's rendered at the same position with the same key, and throws it away when the key changes.",
      requirements: ["Counter is unchanged", "Reset sets the count back to 0", "Counter works again after reset"],
      hints: ["Keep a number in Scoreboard's state and use it as Counter's key.", "<Counter key={resetCount} />, then increment resetCount on Reset."],
      starterCode: `import { useState } from "react";\n\nexport function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount((c) => c + 1)}>+1</button>\n    </div>\n  );\n}\n\nfunction Scoreboard() {\n  // Write your solution here\n  return null;\n}\n\nexport default Scoreboard;\n`,
      solutionCode: `import { useState } from "react";\n\nexport function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount((c) => c + 1)}>+1</button>\n    </div>\n  );\n}\n\nfunction Scoreboard() {\n  const [version, setVersion] = useState(0);\n\n  return (\n    <div>\n      <Counter key={version} />\n      <button onClick={() => setVersion((v) => v + 1)}>Reset</button>\n    </div>\n  );\n}\n\nexport default Scoreboard;\n`,
      explanation: "A new key tells React this is a different component instance, so it unmounts the old one (discarding its state) and mounts a fresh one. It's the idiomatic way to reset a whole subtree, e.g. a form when switching which record is being edited.",
      tests: [
        test("counts", `renderComponent();\n${click("+1")}\n${click("+1")}\nexpectText("Count: 2");`),
        hidden("reset returns to 0 and still works", `renderComponent();\n${click("+1")}\n${click("+1")}\n${click("Reset")}\nexpectText("Count: 0");\n${click("+1")}\nexpectText("Count: 1");`),
      ],
      wrongSolutions: [`import { useState } from "react";\nexport function Counter() {\n  const [count, setCount] = useState(0);\n  return (<div><p>Count: {count}</p><button onClick={() => setCount((c) => c + 1)}>+1</button></div>);\n}\nfunction Scoreboard() {\n  const [v, setV] = useState(0);\n  return (<div><Counter /><button onClick={() => setV(v + 1)}>Reset</button></div>);\n}\nexport default Scoreboard;\n`],
    },
    {
      slug: "comm-accordion-single-open",
      title: "Accordion: Only One Panel Open",
      difficulty: "MEDIUM",
      tags: ["lifting-state-up", "accessibility", "accordion"],
      estimatedMinutes: 20,
      description:
        "Build an exported, stateless `AccordionItem({ title, isOpen, onToggle, children })`: a `<button aria-expanded={isOpen}>{title}</button>` followed by the children **only when open**.\n\nMake `Accordion({ items })` (default, items are `{ id, title, content }`) render one AccordionItem per item, with **at most one open at a time**. Clicking the open item's button closes it. All start closed.",
      requirements: ["All closed initially", "Opening one closes the others", "Clicking the open one closes it", "aria-expanded is correct"],
      hints: ["Lift 'which one is open' into Accordion: useState<number | null>(null)", "isOpen={openId === item.id}", "onToggle={() => setOpenId(openId === item.id ? null : item.id)}"],
      starterCode: `import { useState, type ReactNode } from "react";\n\nexport function AccordionItem(props: { title: string; isOpen: boolean; onToggle: () => void; children: ReactNode }) {\n  return null;\n}\n\ninterface Item {\n  id: number;\n  title: string;\n  content: string;\n}\n\nfunction Accordion({ items }: { items: Item[] }) {\n  return null;\n}\n\nexport default Accordion;\n`,
      solutionCode: `import { useState, type ReactNode } from "react";\n\nexport function AccordionItem({ title, isOpen, onToggle, children }: { title: string; isOpen: boolean; onToggle: () => void; children: ReactNode }) {\n  return (\n    <div>\n      <button aria-expanded={isOpen} onClick={onToggle}>\n        {title}\n      </button>\n      {isOpen && <div>{children}</div>}\n    </div>\n  );\n}\n\ninterface Item {\n  id: number;\n  title: string;\n  content: string;\n}\n\nfunction Accordion({ items }: { items: Item[] }) {\n  const [openId, setOpenId] = useState<number | null>(null);\n\n  return (\n    <div>\n      {items.map((item) => (\n        <AccordionItem\n          key={item.id}\n          title={item.title}\n          isOpen={openId === item.id}\n          onToggle={() => setOpenId((current) => (current === item.id ? null : item.id))}\n        >\n          <p>{item.content}</p>\n        </AccordionItem>\n      ))}\n    </div>\n  );\n}\n\nexport default Accordion;\n`,
      explanation: "If each item owned an `isOpen` boolean, they couldn't coordinate. Moving the state up to the parent lets it enforce the 'only one open' rule.",
      tests: [
        test("opens one panel", `renderComponent({ items: [{ id: 1, title: "Shipping", content: "3-5 days" }, { id: 2, title: "Returns", content: "30 days" }] });\nexpectNoText("3-5 days");\n${click("Shipping")}\nexpectText("3-5 days");\nassertEqual(screen.getByRole("button", { name: "Shipping" }).getAttribute("aria-expanded"), "true");`),
        hidden("only one open at a time and toggles closed", `renderComponent({ items: [{ id: 1, title: "Shipping", content: "3-5 days" }, { id: 2, title: "Returns", content: "30 days" }] });\n${click("Shipping")}\n${click("Returns")}\nexpectText("30 days");\nexpectNoText("3-5 days");\nassertEqual(screen.getByRole("button", { name: "Shipping" }).getAttribute("aria-expanded"), "false");\n${click("Returns")}\nexpectNoText("30 days");`),
      ],
      wrongSolutions: [`import { useState } from "react";\nexport function AccordionItem({ title, children }) {\n  const [open, setOpen] = useState(false);\n  return (<div><button aria-expanded={open} onClick={() => setOpen(!open)}>{title}</button>{open && <div>{children}</div>}</div>);\n}\nfunction Accordion({ items }) {\n  return <div>{items.map((i) => <AccordionItem key={i.id} title={i.title}><p>{i.content}</p></AccordionItem>)}</div>;\n}\nexport default Accordion;\n`],
    },
  ],
};
