import { hidden, test, type CategoryBank } from "./types.js";

const click = (name: string) => `fireEvent.click(screen.getByRole("button", { name: ${JSON.stringify(name)} }));`;
const items = `screen.getAllByRole("listitem").map((el) => el.textContent)`;
const imports = `import { useEffect, useState } from "react";`;
const stubFn = (name: string, params = "") => `${imports}\n\nfunction ${name}(${params}) {\n  // Write your solution here\n  return null;\n}\n\nexport default ${name};\n`;

const USERS = [
  { id: 1, name: "Alice" },
  { id: 2, name: "Bob" },
];

export const api: CategoryBank = {
  category: "API",
  level: 12,
  type: "API",
  prerequisites: ["useState", "useEffect", "Lists"],
  problems: [
    {
      slug: "fetch-users",
      title: "Fetch Users",
      difficulty: "EASY",
      tags: ["api", "fetch", "useEffect", "async"],
      estimatedMinutes: 15,
      description:
        "Make `Users` fetch `GET /api/users` when it mounts. The response is a JSON array of `{ id, name }`.\n\n- While loading, show `<p>Loading...</p>`.\n- Then render a `<ul>` with each user's name, and hide the loading message.\n\nThe platform provides this endpoint as a mock, so the data is predictable.",
      requirements: ["Fetches /api/users on mount", "Shows 'Loading...' first", "Renders the users from the response"],
      hints: [
        "An effect can't be async itself, but it can call an async function you define inside it.",
        "const res = await fetch(\"/api/users\"); const data = await res.json();",
        "Keep `users` and `loading` in state; flip loading to false after setting users.",
      ],
      starterCode: stubFn("Users"),
      solutionCode: `${imports}\n\ninterface User {\n  id: number;\n  name: string;\n}\n\nfunction Users() {\n  const [users, setUsers] = useState<User[]>([]);\n  const [loading, setLoading] = useState(true);\n\n  useEffect(() => {\n    async function load() {\n      const res = await fetch("/api/users");\n      const data: User[] = await res.json();\n      setUsers(data);\n      setLoading(false);\n    }\n    load();\n  }, []);\n\n  if (loading) return <p>Loading...</p>;\n\n  return (\n    <ul>\n      {users.map((user) => (\n        <li key={user.id}>{user.name}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default Users;\n`,
      explanation: "The component renders once with loading=true, the effect starts the request, and when the response arrives, setting state triggers a re-render with the data.",
      commonMistakes: ["useEffect(async () => ...) — an async function returns a Promise, which React would treat as the cleanup function.", "Forgetting the [] dependency array, which refetches after every render (an infinite loop once you set state)."],
      mockApi: [{ url: "/api/users", response: USERS }],
      tests: [
        test("shows loading then users", `renderComponent();\nexpectText("Loading...");\nawait waitFor(() => expectText("Alice"));\nassertEqual(${items}, ["Alice", "Bob"]);\nexpectNoText("Loading...");`),
        hidden("renders whatever the API returns", `mockApi.setRoutes([{ url: "/api/users", response: [{ id: 9, name: "Zara" }, { id: 8, name: "Yuki" }, { id: 7, name: "Xi" }] }]);\nrenderComponent();\nawait waitFor(() => expectText("Zara"));\nassertEqual(${items}, ["Zara", "Yuki", "Xi"]);\nassertEqual(mockApi.calls.length, 1, "Fetch exactly once on mount");`),
      ],
      wrongSolutions: [`function Users() {\n  return (<ul><li>Alice</li><li>Bob</li></ul>);\n}\nexport default Users;\n`],
    },
    {
      slug: "fetch-users-error-state",
      title: "Handle a Failed Request",
      difficulty: "EASY",
      tags: ["api", "fetch", "error-handling"],
      estimatedMinutes: 15,
      description:
        "Make `UsersWithErrors` fetch `GET /api/users` on mount. Show `<p>Loading...</p>` while waiting. This endpoint is configured to **fail with HTTP 500**: when the response isn't OK, show `<p role=\"alert\">Something went wrong.</p>` and hide the loading message. When it succeeds, list the user names.",
      requirements: ["Shows loading", "Shows an error for non-OK responses", "Lists users on success"],
      hints: [
        "fetch() only rejects on network failure. A 500 still resolves — check response.ok.",
        "try { ... if (!res.ok) throw new Error(...) } catch { setError(true) } finally { setLoading(false) }",
      ],
      starterCode: stubFn("UsersWithErrors"),
      solutionCode: `${imports}\n\ninterface User {\n  id: number;\n  name: string;\n}\n\nfunction UsersWithErrors() {\n  const [users, setUsers] = useState<User[]>([]);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState(false);\n\n  useEffect(() => {\n    async function load() {\n      try {\n        const res = await fetch("/api/users");\n        if (!res.ok) throw new Error(\`HTTP \${res.status}\`);\n        setUsers(await res.json());\n      } catch {\n        setError(true);\n      } finally {\n        setLoading(false);\n      }\n    }\n    load();\n  }, []);\n\n  if (loading) return <p>Loading...</p>;\n  if (error) return <p role="alert">Something went wrong.</p>;\n\n  return (\n    <ul>\n      {users.map((u) => (\n        <li key={u.id}>{u.name}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default UsersWithErrors;\n`,
      explanation: "Every request has three outcomes — loading, failed, succeeded — and the UI needs a state for each. `finally` guarantees loading ends either way.",
      mockApi: [{ url: "/api/users", status: 500, response: { error: "Server error" } }],
      tests: [
        test("shows an error", `renderComponent();\nexpectText("Loading...");\nawait waitFor(() => screen.getByRole("alert"));\nexpectText("Something went wrong.");\nexpectNoText("Loading...");`),
        hidden("still works when the request succeeds", `mockApi.setRoutes([{ url: "/api/users", response: [{ id: 1, name: "Ola" }] }]);\nrenderComponent();\nawait waitFor(() => expectText("Ola"));\nassert(!screen.queryByRole("alert"));`),
      ],
      wrongSolutions: [`import { useEffect, useState } from "react";\nfunction UsersWithErrors() {\n  const [users, setUsers] = useState(null);\n  useEffect(() => { fetch("/api/users").then((r) => r.json()).then(setUsers); }, []);\n  if (!users) return <p>Loading...</p>;\n  return <ul>{Array.isArray(users) && users.map((u) => <li key={u.id}>{u.name}</li>)}</ul>;\n}\nexport default UsersWithErrors;\n`],
    },
    {
      slug: "api-products-table",
      title: "Display API Data in a Table",
      difficulty: "EASY",
      tags: ["api", "fetch", "tables"],
      estimatedMinutes: 15,
      description:
        "Make `ProductTable` fetch `GET /api/products` (an array of `{ id, name, price }`) and render a table with headers `Product` and `Price`, one row per product, prices as `$X.XX`. Show `Loading...` until the data arrives.",
      requirements: ["Fetches on mount", "Table with one row per product", "Prices formatted with two decimals"],
      hints: ["Same loading/data pattern as Fetch Users.", "price.toFixed(2)"],
      starterCode: stubFn("ProductTable"),
      solutionCode: `${imports}\n\ninterface Product {\n  id: number;\n  name: string;\n  price: number;\n}\n\nfunction ProductTable() {\n  const [products, setProducts] = useState<Product[] | null>(null);\n\n  useEffect(() => {\n    fetch("/api/products")\n      .then((res) => res.json())\n      .then((data: Product[]) => setProducts(data));\n  }, []);\n\n  if (!products) return <p>Loading...</p>;\n\n  return (\n    <table>\n      <thead>\n        <tr>\n          <th>Product</th>\n          <th>Price</th>\n        </tr>\n      </thead>\n      <tbody>\n        {products.map((p) => (\n          <tr key={p.id}>\n            <td>{p.name}</td>\n            <td>\${p.price.toFixed(2)}</td>\n          </tr>\n        ))}\n      </tbody>\n    </table>\n  );\n}\n\nexport default ProductTable;\n`,
      explanation: "Using `null` as 'not loaded yet' combines the data and loading state into one variable — handy when an empty array is also a valid response.",
      mockApi: [{ url: "/api/products", response: [{ id: 1, name: "Lamp", price: 25 }, { id: 2, name: "Desk", price: 149.5 }] }],
      tests: [
        test("renders the products", `renderComponent();\nexpectText("Loading...");\nawait waitFor(() => screen.getByRole("cell", { name: "Lamp" }));\nscreen.getByRole("cell", { name: "$149.50" });\nscreen.getByRole("columnheader", { name: "Price" });`),
        hidden("renders other data", `mockApi.setRoutes([{ url: "/api/products", response: [{ id: 5, name: "Chair", price: 60 }] }]);\nrenderComponent();\nawait waitFor(() => screen.getByRole("cell", { name: "Chair" }));\nassertEqual(screen.getAllByRole("row").length, 2);\nscreen.getByRole("cell", { name: "$60.00" });`),
      ],
    },
    {
      slug: "api-fetch-on-click",
      title: "Fetch on Button Click",
      difficulty: "EASY",
      tags: ["api", "fetch", "events"],
      estimatedMinutes: 12,
      description:
        "Not every request belongs in an effect. Make `QuoteButton` render a button `Get quote`. Only when it's clicked, fetch `GET /api/quote` (returns `{ text }`), show `<p>Loading...</p>` while waiting, then show `<blockquote>{text}</blockquote>`.\n\nNo request should happen before the click.",
      requirements: ["No request on mount", "Fetches on click", "Shows loading then the quote"],
      hints: ["Make the click handler async.", "Requests triggered by a user action go in the event handler, not in an effect."],
      starterCode: stubFn("QuoteButton"),
      solutionCode: `import { useState } from "react";\n\nfunction QuoteButton() {\n  const [quote, setQuote] = useState<string | null>(null);\n  const [loading, setLoading] = useState(false);\n\n  async function handleClick() {\n    setLoading(true);\n    const res = await fetch("/api/quote");\n    const data: { text: string } = await res.json();\n    setQuote(data.text);\n    setLoading(false);\n  }\n\n  return (\n    <div>\n      <button onClick={handleClick}>Get quote</button>\n      {loading && <p>Loading...</p>}\n      {quote && !loading && <blockquote>{quote}</blockquote>}\n    </div>\n  );\n}\n\nexport default QuoteButton;\n`,
      explanation: "Effects are for synchronizing with something because the component is on screen. Requests caused by a specific user action belong in that action's event handler.",
      mockApi: [{ url: "/api/quote", delayMs: 30, response: { text: "Simplicity is prerequisite for reliability." } }],
      tests: [
        test("fetches after the click", `renderComponent();\nawait sleep(20);\nassertEqual(mockApi.calls.length, 0, "Don't fetch until the button is clicked");\n${click("Get quote")}\nexpectText("Loading...");\nawait waitFor(() => expectText("Simplicity is prerequisite for reliability."));`),
        hidden("shows the latest quote", `mockApi.setRoutes([{ url: "/api/quote", response: { text: "Make it work, then make it right." } }]);\nrenderComponent();\n${click("Get quote")}\nawait waitFor(() => expectText("Make it work, then make it right."));\nexpectNoText("Loading...");\nassertEqual(mockApi.calls.map((c) => c.url), ["/api/quote"]);`),
      ],
      wrongSolutions: [`import { useEffect, useState } from "react";\nfunction QuoteButton() {\n  const [q, setQ] = useState(null);\n  useEffect(() => { fetch("/api/quote").then((r) => r.json()).then((d) => setQ(d.text)); }, []);\n  return (<div><button>Get quote</button>{q && <blockquote>{q}</blockquote>}</div>);\n}\nexport default QuoteButton;\n`],
    },
    {
      slug: "api-empty-state",
      title: "Handle an Empty Response",
      difficulty: "EASY",
      tags: ["api", "empty-state"],
      estimatedMinutes: 12,
      description:
        "Make `PostFeed` fetch `GET /api/posts` (array of `{ id, title }`). Show `Loading...` first. If the array is empty, show `<p>No posts yet</p>`; otherwise list the titles.",
      requirements: ["Loading state", "Empty state", "Data state"],
      hints: ["Distinguish 'not loaded yet' (null) from 'loaded but empty' ([]).", "Check posts.length === 0 after loading."],
      starterCode: stubFn("PostFeed"),
      solutionCode: `${imports}\n\ninterface Post {\n  id: number;\n  title: string;\n}\n\nfunction PostFeed() {\n  const [posts, setPosts] = useState<Post[] | null>(null);\n\n  useEffect(() => {\n    fetch("/api/posts")\n      .then((r) => r.json())\n      .then(setPosts);\n  }, []);\n\n  if (posts === null) return <p>Loading...</p>;\n  if (posts.length === 0) return <p>No posts yet</p>;\n\n  return (\n    <ul>\n      {posts.map((p) => (\n        <li key={p.id}>{p.title}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default PostFeed;\n`,
      explanation: "'Loading' and 'empty' look similar in code but mean different things to users. null vs [] keeps them apart.",
      mockApi: [{ url: "/api/posts", response: [] }],
      tests: [
        test("shows the empty state", `renderComponent();\nexpectText("Loading...");\nawait waitFor(() => expectText("No posts yet"));`),
        hidden("lists posts when there are some", `mockApi.setRoutes([{ url: "/api/posts", response: [{ id: 1, title: "Launch day" }] }]);\nrenderComponent();\nawait waitFor(() => expectText("Launch day"));\nexpectNoText("No posts yet");`),
      ],
      wrongSolutions: [`import { useEffect, useState } from "react";\nfunction PostFeed() {\n  const [posts, setPosts] = useState([]);\n  useEffect(() => { fetch("/api/posts").then((r) => r.json()).then(setPosts); }, []);\n  if (posts.length === 0) return <p>No posts yet</p>;\n  return <ul>{posts.map((p) => <li key={p.id}>{p.title}</li>)}</ul>;\n}\nexport default PostFeed;\n`],
    },
    {
      slug: "api-fetch-by-id",
      title: "Fetch Based on a Prop",
      difficulty: "MEDIUM",
      tags: ["api", "useEffect", "dependencies"],
      estimatedMinutes: 15,
      description:
        "Make `UserDetails` accept `userId` and fetch `GET /api/users/{userId}`, which returns `{ id, name, email }`. Render `<h2>{name}</h2>` and `<p>{email}</p>` (or `Loading...` while fetching). When `userId` changes, fetch the new user.",
      requirements: ["Fetches the user for the given id", "Refetches when userId changes"],
      hints: ["Build the URL from the prop: `/api/users/${userId}`", "Put userId in the effect's dependency array."],
      starterCode: stubFn("UserDetails", "{ userId }: { userId: number }"),
      solutionCode: `${imports}\n\ninterface User {\n  id: number;\n  name: string;\n  email: string;\n}\n\nfunction UserDetails({ userId }: { userId: number }) {\n  const [user, setUser] = useState<User | null>(null);\n\n  useEffect(() => {\n    setUser(null);\n    fetch(\`/api/users/\${userId}\`)\n      .then((r) => r.json())\n      .then(setUser);\n  }, [userId]);\n\n  if (!user) return <p>Loading...</p>;\n\n  return (\n    <div>\n      <h2>{user.name}</h2>\n      <p>{user.email}</p>\n    </div>\n  );\n}\n\nexport default UserDetails;\n`,
      explanation: "Any prop the effect reads must be a dependency, so a new userId triggers a new request instead of showing stale data.",
      mockApi: [
        { url: "/api/users/1", response: { id: 1, name: "Alice", email: "alice@example.com" } },
        { url: "/api/users/2", response: { id: 2, name: "Bob", email: "bob@example.com" } },
      ],
      tests: [
        test("fetches the given user", `renderComponent({ userId: 1 });\nawait waitFor(() => screen.getByRole("heading", { name: "Alice" }));\nexpectText("alice@example.com");`),
        hidden("refetches on id change", `const { rerender } = renderComponent({ userId: 1 });\nawait waitFor(() => screen.getByRole("heading", { name: "Alice" }));\nrerender(<Component userId={2} />);\nawait waitFor(() => screen.getByRole("heading", { name: "Bob" }));\nassertEqual(mockApi.calls.map((c) => c.url), ["/api/users/1", "/api/users/2"]);`),
      ],
      wrongSolutions: [`import { useEffect, useState } from "react";\nfunction UserDetails({ userId }) {\n  const [user, setUser] = useState(null);\n  useEffect(() => { fetch("/api/users/" + userId).then((r) => r.json()).then(setUser); }, []);\n  if (!user) return <p>Loading...</p>;\n  return (<div><h2>{user.name}</h2><p>{user.email}</p></div>);\n}\nexport default UserDetails;\n`],
    },
    {
      slug: "api-retry",
      title: "Retry a Failed Request",
      difficulty: "MEDIUM",
      tags: ["api", "error-handling", "retry"],
      estimatedMinutes: 20,
      description:
        "Make `Stats` fetch `GET /api/stats` (returns `{ visitors }`) on mount and show `<p>Visitors: {n}</p>`.\n\nIf the request fails (non-OK), show `<p role=\"alert\">Could not load stats</p>` and a `Retry` button. Clicking Retry fetches again (showing `Loading...` meanwhile).",
      requirements: ["Shows an error and Retry button on failure", "Retry refetches", "Shows data after a successful retry"],
      hints: [
        "Put the request in a named function you can call from both the effect and the button.",
        "Reset the error and set loading at the start of every attempt.",
      ],
      starterCode: stubFn("Stats"),
      solutionCode: `${imports}\n\nfunction Stats() {\n  const [visitors, setVisitors] = useState<number | null>(null);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState(false);\n\n  async function load() {\n    setLoading(true);\n    setError(false);\n    try {\n      const res = await fetch("/api/stats");\n      if (!res.ok) throw new Error("Request failed");\n      const data: { visitors: number } = await res.json();\n      setVisitors(data.visitors);\n    } catch {\n      setError(true);\n    } finally {\n      setLoading(false);\n    }\n  }\n\n  useEffect(() => {\n    load();\n  }, []);\n\n  if (loading) return <p>Loading...</p>;\n  if (error) {\n    return (\n      <div>\n        <p role="alert">Could not load stats</p>\n        <button onClick={load}>Retry</button>\n      </div>\n    );\n  }\n  return <p>Visitors: {visitors}</p>;\n}\n\nexport default Stats;\n`,
      explanation: "Extracting the request into a function lets the same logic serve the initial load and any retries.",
      mockApi: [{ url: "/api/stats", status: 503, response: { error: "Unavailable" } }],
      tests: [
        test("shows error and retry", `renderComponent();\nawait waitFor(() => screen.getByRole("alert"));\nscreen.getByRole("button", { name: "Retry" });`),
        hidden("retry recovers", `renderComponent();\nawait waitFor(() => screen.getByRole("alert"));\nmockApi.setRoutes([{ url: "/api/stats", response: { visitors: 1234 } }]);\n${click("Retry")}\nawait waitFor(() => expectText("Visitors: 1234"));\nassert(!screen.queryByRole("alert"), "The error should be gone after a successful retry");\nassertEqual(mockApi.calls.length, 2);`),
      ],
    },
    {
      slug: "api-post-create",
      title: "Create an Item With POST",
      difficulty: "MEDIUM",
      tags: ["api", "post", "forms"],
      estimatedMinutes: 20,
      description:
        "Make `AddTodo` render an input labelled `New todo`, a submit button `Add`, and a `<ul>` of created todos.\n\nOn submit, send `POST /api/todos` with header `Content-Type: application/json` and body `{ \"title\": \"...\" }`. The server responds with the created todo `{ id, title }` — add **that** to the list and clear the input. While the request is in flight, the button shows `Adding...` and is disabled.",
      requirements: ["Sends a POST with a JSON body and header", "Appends the server's response", "Disables the button while saving"],
      hints: [
        "fetch(url, { method: \"POST\", headers: { \"Content-Type\": \"application/json\" }, body: JSON.stringify({ title }) })",
        "Use the response (it has the real id), not the local input.",
      ],
      starterCode: stubFn("AddTodo"),
      solutionCode: `import { useState, type FormEvent } from "react";\n\ninterface Todo {\n  id: number;\n  title: string;\n}\n\nfunction AddTodo() {\n  const [title, setTitle] = useState("");\n  const [todos, setTodos] = useState<Todo[]>([]);\n  const [saving, setSaving] = useState(false);\n\n  async function handleSubmit(event: FormEvent) {\n    event.preventDefault();\n    if (!title.trim()) return;\n    setSaving(true);\n    const res = await fetch("/api/todos", {\n      method: "POST",\n      headers: { "Content-Type": "application/json" },\n      body: JSON.stringify({ title: title.trim() }),\n    });\n    const created: Todo = await res.json();\n    setTodos((prev) => [...prev, created]);\n    setTitle("");\n    setSaving(false);\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <label>\n        New todo <input value={title} onChange={(e) => setTitle(e.target.value)} />\n      </label>\n      <button type="submit" disabled={saving}>\n        {saving ? "Adding..." : "Add"}\n      </button>\n      <ul>\n        {todos.map((t) => (\n          <li key={t.id}>{t.title}</li>\n        ))}\n      </ul>\n    </form>\n  );\n}\n\nexport default AddTodo;\n`,
      explanation: "Rendering the server's response (with its real id) keeps the UI consistent with what was actually saved.",
      mockApi: [{ method: "POST", url: "/api/todos", delayMs: 30, status: 201, response: { id: 101, title: "Water plants" } }],
      tests: [
        test("posts and shows the created todo", `renderComponent();\nawait userEvent.type(screen.getByLabelText("New todo"), "Water plants");\n${click("Add")}\nscreen.getByRole("button", { name: "Adding..." });\nawait waitFor(() => screen.getByText("Water plants", { selector: "li" }));\nassertEqual(screen.getByLabelText("New todo").value, "");`),
        hidden("sends the right request", `renderComponent();\nawait userEvent.type(screen.getByLabelText("New todo"), "Water plants");\n${click("Add")}\nawait waitFor(() => screen.getByRole("button", { name: "Add" }));\nconst call = mockApi.calls[0];\nassertEqual(call.method, "POST");\nassertEqual(call.url, "/api/todos");\nassertEqual(call.body, { title: "Water plants" });\nconst headers = call.headers;\nconst contentType = headers["Content-Type"] ?? headers["content-type"];\nassertEqual(contentType, "application/json");`),
        hidden("renders the server's version", `mockApi.setRoutes([{ method: "POST", url: "/api/todos", response: { id: 7, title: "Server title" } }]);\nrenderComponent();\nawait userEvent.type(screen.getByLabelText("New todo"), "local title");\n${click("Add")}\nawait waitFor(() => expectText("Server title"));`),
      ],
    },
    {
      slug: "api-delete-item",
      title: "Delete an Item via the API",
      difficulty: "MEDIUM",
      tags: ["api", "delete", "lists"],
      estimatedMinutes: 20,
      description:
        "Make `TodoManager` load `GET /api/todos` (array of `{ id, title }`) and list them, each with a `Delete` button. Clicking it sends `DELETE /api/todos/{id}`; once that succeeds, remove the item from the list. If the delete fails, keep the item and show `<p role=\"alert\">Could not delete</p>`.",
      requirements: ["Loads todos", "Sends DELETE for the right id", "Removes only after success", "Keeps the item on failure"],
      hints: ["Await the DELETE, check res.ok, then filter the item out of state.", "Find each item's button with its own <li>."],
      starterCode: stubFn("TodoManager"),
      solutionCode: `${imports}\n\ninterface Todo {\n  id: number;\n  title: string;\n}\n\nfunction TodoManager() {\n  const [todos, setTodos] = useState<Todo[]>([]);\n  const [error, setError] = useState(false);\n\n  useEffect(() => {\n    fetch("/api/todos")\n      .then((r) => r.json())\n      .then(setTodos);\n  }, []);\n\n  async function remove(id: number) {\n    setError(false);\n    const res = await fetch(\`/api/todos/\${id}\`, { method: "DELETE" });\n    if (!res.ok) {\n      setError(true);\n      return;\n    }\n    setTodos((prev) => prev.filter((t) => t.id !== id));\n  }\n\n  return (\n    <div>\n      {error && <p role="alert">Could not delete</p>}\n      <ul>\n        {todos.map((t) => (\n          <li key={t.id}>\n            <span>{t.title}</span>\n            <button onClick={() => remove(t.id)}>Delete</button>\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nexport default TodoManager;\n`,
      explanation: "Updating the UI only after the server confirms is a 'pessimistic' update: slower to feel, but never shows something that didn't happen.",
      mockApi: [
        { url: "/api/todos", response: [{ id: 1, title: "Read" }, { id: 2, title: "Write" }] },
        { method: "DELETE", url: "/api/todos/2", response: {} },
        { method: "DELETE", url: "/api/todos/1", status: 500, response: { error: "Locked" } },
      ],
      tests: [
        test("deletes an item", `renderComponent();\nawait waitFor(() => expectText("Write"));\nfireEvent.click(within(screen.getByText("Write").closest("li")).getByRole("button", { name: "Delete" }));\nawait waitFor(() => expectNoText("Write"));\nexpectText("Read");\nassert(mockApi.calls.some((c) => c.method === "DELETE" && c.url === "/api/todos/2"), "Send DELETE /api/todos/2");`),
        hidden("keeps the item when delete fails", `renderComponent();\nawait waitFor(() => expectText("Read"));\nfireEvent.click(within(screen.getByText("Read").closest("li")).getByRole("button", { name: "Delete" }));\nawait waitFor(() => screen.getByRole("alert"));\nexpectText("Read");`),
      ],
      wrongSolutions: [`import { useEffect, useState } from "react";\nfunction TodoManager() {\n  const [todos, setTodos] = useState([]);\n  useEffect(() => { fetch("/api/todos").then((r) => r.json()).then(setTodos); }, []);\n  return <ul>{todos.map((t) => <li key={t.id}><span>{t.title}</span><button onClick={() => { fetch("/api/todos/" + t.id, { method: "DELETE" }); setTodos(todos.filter((x) => x.id !== t.id)); }}>Delete</button></li>)}</ul>;\n}\nexport default TodoManager;\n`],
    },
    {
      slug: "api-search-query",
      title: "Search With a Query Parameter",
      difficulty: "MEDIUM",
      tags: ["api", "search", "url"],
      estimatedMinutes: 15,
      description:
        "Make `ProductSearch` render a form with an input labelled `Search products` and a submit button `Search`. On submit, fetch `GET /api/products?q={query}` — **URL-encode** the query — and list the result names, or show `<p>No products found</p>` for an empty result. Show nothing before the first search.",
      requirements: ["Query is URL-encoded", "Lists results", "Empty-results message"],
      hints: ["encodeURIComponent(\"red shoes\") → \"red%20shoes\"", "Alternatively: new URLSearchParams({ q: query }).toString()"],
      starterCode: stubFn("ProductSearch"),
      solutionCode: `import { useState, type FormEvent } from "react";\n\ninterface Product {\n  id: number;\n  name: string;\n}\n\nfunction ProductSearch() {\n  const [query, setQuery] = useState("");\n  const [results, setResults] = useState<Product[] | null>(null);\n\n  async function handleSubmit(event: FormEvent) {\n    event.preventDefault();\n    const res = await fetch(\`/api/products?q=\${encodeURIComponent(query)}\`);\n    setResults(await res.json());\n  }\n\n  return (\n    <div>\n      <form onSubmit={handleSubmit}>\n        <label>\n          Search products <input value={query} onChange={(e) => setQuery(e.target.value)} />\n        </label>\n        <button type="submit">Search</button>\n      </form>\n      {results && results.length === 0 && <p>No products found</p>}\n      {results && results.length > 0 && (\n        <ul>\n          {results.map((p) => (\n            <li key={p.id}>{p.name}</li>\n          ))}\n        </ul>\n      )}\n    </div>\n  );\n}\n\nexport default ProductSearch;\n`,
      explanation: "User input in a URL must be encoded — otherwise spaces, & and ? break the query string (or change its meaning).",
      mockApi: [
        { url: "/api/products?q=red%20shoes", response: [{ id: 1, name: "Red Running Shoes" }, { id: 2, name: "Red Loafers" }] },
        { url: "/api/products?q=hat", response: [] },
      ],
      tests: [
        test("searches with an encoded query", `renderComponent();\nawait userEvent.type(screen.getByLabelText("Search products"), "red shoes");\n${click("Search")}\nawait waitFor(() => expectText("Red Loafers"));\nassertEqual(mockApi.calls[0].url, "/api/products?q=red%20shoes");`),
        hidden("shows the empty message", `renderComponent();\nassert(!screen.queryByText("No products found"), "Nothing should show before searching");\nawait userEvent.type(screen.getByLabelText("Search products"), "hat");\n${click("Search")}\nawait waitFor(() => expectText("No products found"));`),
      ],
    },
    {
      slug: "api-pagination",
      title: "Paginate API Results",
      difficulty: "MEDIUM",
      tags: ["api", "pagination"],
      estimatedMinutes: 20,
      description:
        "Make `PagedPosts` fetch `GET /api/posts?page={n}`, starting at page 1. Each response is `{ items: { id, title }[], hasMore: boolean }`.\n\nRender the titles, `<p>Page {n}</p>`, and buttons `Previous` (disabled on page 1) and `Next` (disabled when `hasMore` is false).",
      requirements: ["Fetches the current page", "Next/Previous change pages", "Buttons disabled at the edges"],
      hints: ["Keep `page` in state and put it in the effect's dependencies.", "Store hasMore from the response alongside the items."],
      starterCode: stubFn("PagedPosts"),
      solutionCode: `${imports}\n\ninterface Page {\n  items: { id: number; title: string }[];\n  hasMore: boolean;\n}\n\nfunction PagedPosts() {\n  const [page, setPage] = useState(1);\n  const [data, setData] = useState<Page | null>(null);\n\n  useEffect(() => {\n    let ignore = false;\n    fetch(\`/api/posts?page=\${page}\`)\n      .then((r) => r.json())\n      .then((d: Page) => {\n        if (!ignore) setData(d);\n      });\n    return () => {\n      ignore = true;\n    };\n  }, [page]);\n\n  return (\n    <div>\n      <ul>\n        {data?.items.map((p) => (\n          <li key={p.id}>{p.title}</li>\n        ))}\n      </ul>\n      <p>Page {page}</p>\n      <button disabled={page === 1} onClick={() => setPage((p) => p - 1)}>Previous</button>\n      <button disabled={!data?.hasMore} onClick={() => setPage((p) => p + 1)}>Next</button>\n    </div>\n  );\n}\n\nexport default PagedPosts;\n`,
      explanation: "The page number is the state; the request is an effect of that state. Changing the page re-runs the effect.",
      mockApi: [
        { url: "/api/posts?page=1", response: { items: [{ id: 1, title: "Post 1" }, { id: 2, title: "Post 2" }], hasMore: true } },
        { url: "/api/posts?page=2", response: { items: [{ id: 3, title: "Post 3" }], hasMore: false } },
      ],
      tests: [
        test("loads page 1", `renderComponent();\nawait waitFor(() => expectText("Post 1"));\nexpectText("Page 1");\nassert(screen.getByRole("button", { name: "Previous" }).disabled);`),
        hidden("navigates pages", `renderComponent();\nawait waitFor(() => expectText("Post 1"));\n${click("Next")}\nawait waitFor(() => expectText("Post 3"));\nexpectText("Page 2");\nexpectNoText("Post 1");\nawait waitFor(() => assert(screen.getByRole("button", { name: "Next" }).disabled, "Next should be disabled on the last page"));\n${click("Previous")}\nawait waitFor(() => expectText("Post 1"));`),
      ],
    },
    {
      slug: "api-load-more",
      title: "Load More Results",
      difficulty: "MEDIUM",
      tags: ["api", "pagination", "infinite-loading"],
      estimatedMinutes: 20,
      description:
        "Make `CommentFeed` fetch `GET /api/comments?page=1` on mount (response `{ items: { id, text }[], hasMore }`) and list the comments. A `Load more` button fetches the next page and **appends** its items. Hide the button when `hasMore` is false. While loading more, the button shows `Loading...` and is disabled.",
      requirements: ["Initial page loads", "Load more appends", "Button hidden when there's no more"],
      hints: ["Append with setComments((prev) => [...prev, ...data.items])", "Track the next page number in state."],
      starterCode: stubFn("CommentFeed"),
      solutionCode: `${imports}\n\ninterface Comment {\n  id: number;\n  text: string;\n}\n\nfunction CommentFeed() {\n  const [comments, setComments] = useState<Comment[]>([]);\n  const [page, setPage] = useState(1);\n  const [hasMore, setHasMore] = useState(false);\n  const [loading, setLoading] = useState(false);\n\n  async function loadPage(n: number) {\n    setLoading(true);\n    const res = await fetch(\`/api/comments?page=\${n}\`);\n    const data: { items: Comment[]; hasMore: boolean } = await res.json();\n    setComments((prev) => [...prev, ...data.items]);\n    setHasMore(data.hasMore);\n    setPage(n);\n    setLoading(false);\n  }\n\n  useEffect(() => {\n    loadPage(1);\n  }, []);\n\n  return (\n    <div>\n      <ul>\n        {comments.map((c) => (\n          <li key={c.id}>{c.text}</li>\n        ))}\n      </ul>\n      {hasMore && (\n        <button disabled={loading} onClick={() => loadPage(page + 1)}>\n          {loading ? "Loading..." : "Load more"}\n        </button>\n      )}\n    </div>\n  );\n}\n\nexport default CommentFeed;\n`,
      explanation: "Unlike pagination, 'load more' accumulates: each page is appended to what's already shown.",
      mockApi: [
        { url: "/api/comments?page=1", response: { items: [{ id: 1, text: "First!" }, { id: 2, text: "Nice post" }], hasMore: true } },
        { url: "/api/comments?page=2", delayMs: 30, response: { items: [{ id: 3, text: "Thanks" }], hasMore: false } },
      ],
      tests: [
        test("loads the first page", `renderComponent();\nawait waitFor(() => expectText("Nice post"));\nscreen.getByRole("button", { name: "Load more" });`),
        hidden("appends and hides the button", `renderComponent();\nawait waitFor(() => expectText("Nice post"));\n${click("Load more")}\nscreen.getByRole("button", { name: "Loading..." });\nawait waitFor(() => expectText("Thanks"));\nassertEqual(${items}, ["First!", "Nice post", "Thanks"]);\nassert(!screen.queryByRole("button"), "Hide Load more when there are no more pages");`),
      ],
    },
    {
      slug: "api-parallel-requests",
      title: "Parallel Requests",
      difficulty: "MEDIUM",
      tags: ["api", "promise-all", "performance"],
      estimatedMinutes: 15,
      description:
        "Make `DashboardSummary` fetch `GET /api/users` **and** `GET /api/posts` at the same time (not one after the other), then show `<p>{u} users · {p} posts</p>`. Show `Loading...` until both have arrived.",
      requirements: ["Both requests start immediately", "Summary shows both counts"],
      hints: ["Promise.all([fetch(a), fetch(b)]) starts both before waiting.", "Awaiting the first fetch before starting the second makes them sequential."],
      starterCode: stubFn("DashboardSummary"),
      solutionCode: `${imports}\n\nfunction DashboardSummary() {\n  const [counts, setCounts] = useState<{ users: number; posts: number } | null>(null);\n\n  useEffect(() => {\n    async function load() {\n      const [usersRes, postsRes] = await Promise.all([fetch("/api/users"), fetch("/api/posts")]);\n      const [users, posts] = await Promise.all([usersRes.json(), postsRes.json()]);\n      setCounts({ users: users.length, posts: posts.length });\n    }\n    load();\n  }, []);\n\n  if (!counts) return <p>Loading...</p>;\n  return (\n    <p>\n      {counts.users} users · {counts.posts} posts\n    </p>\n  );\n}\n\nexport default DashboardSummary;\n`,
      explanation: "Independent requests should run in parallel: the total wait becomes the slowest request instead of the sum of all of them.",
      mockApi: [
        { url: "/api/users", delayMs: 60, response: [{ id: 1 }, { id: 2 }, { id: 3 }] },
        { url: "/api/posts", delayMs: 60, response: [{ id: 1 }, { id: 2 }] },
      ],
      tests: [
        test("shows both counts", `renderComponent();\nexpectText("Loading...");\nawait waitFor(() => expectText("3 users · 2 posts"));`),
        hidden("requests run in parallel", `renderComponent();\nawait sleep(20);\nassertEqual(mockApi.calls.length, 2, "Both requests should start immediately, not one after the other");\nawait waitFor(() => expectText("3 users · 2 posts"));`),
      ],
      wrongSolutions: [`import { useEffect, useState } from "react";\nfunction DashboardSummary() {\n  const [c, setC] = useState(null);\n  useEffect(() => { (async () => { const u = await (await fetch("/api/users")).json(); const p = await (await fetch("/api/posts")).json(); setC({ u: u.length, p: p.length }); })(); }, []);\n  if (!c) return <p>Loading...</p>;\n  return <p>{c.u} users · {c.p} posts</p>;\n}\nexport default DashboardSummary;\n`],
    },
    {
      slug: "api-dependent-requests",
      title: "Dependent Requests",
      difficulty: "HARD",
      tags: ["api", "async", "sequential"],
      estimatedMinutes: 20,
      description:
        "Make `MyOrders` first fetch `GET /api/me` (returns `{ id, name }`), then use that id to fetch `GET /api/users/{id}/orders` (returns `{ id, total }[]`). Render `<h2>{name}'s orders</h2>` and one `<li>` per order as `Order #{id}: ${total}` (two decimals). Show `Loading...` until both are done.",
      requirements: ["Second request uses the id from the first", "Renders the orders"],
      hints: ["Here sequential is correct: you can't build the second URL until the first resolves.", "await the first response before calling fetch the second time."],
      starterCode: stubFn("MyOrders"),
      solutionCode: `${imports}\n\ninterface Order {\n  id: number;\n  total: number;\n}\n\nfunction MyOrders() {\n  const [data, setData] = useState<{ name: string; orders: Order[] } | null>(null);\n\n  useEffect(() => {\n    async function load() {\n      const me: { id: number; name: string } = await (await fetch("/api/me")).json();\n      const orders: Order[] = await (await fetch(\`/api/users/\${me.id}/orders\`)).json();\n      setData({ name: me.name, orders });\n    }\n    load();\n  }, []);\n\n  if (!data) return <p>Loading...</p>;\n\n  return (\n    <div>\n      <h2>{data.name}'s orders</h2>\n      <ul>\n        {data.orders.map((o) => (\n          <li key={o.id}>\n            Order #{o.id}: \${o.total.toFixed(2)}\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nexport default MyOrders;\n`,
      explanation: "When one request needs data from another, they must run in sequence. Parallelize only requests that are independent.",
      mockApi: [
        { url: "/api/me", response: { id: 7, name: "Ana" } },
        { url: "/api/users/7/orders", response: [{ id: 501, total: 20 }, { id: 502, total: 7.5 }] },
      ],
      tests: [
        test("renders the orders", `renderComponent();\nawait waitFor(() => screen.getByRole("heading", { name: "Ana's orders" }));\nassertEqual(${items}, ["Order #501: $20.00", "Order #502: $7.50"]);`),
        hidden("uses the id from /api/me", `mockApi.setRoutes([{ url: "/api/me", response: { id: 9, name: "Kai" } }, { url: "/api/users/9/orders", response: [{ id: 1, total: 1 }] }]);\nrenderComponent();\nawait waitFor(() => screen.getByRole("heading", { name: "Kai's orders" }));\nassertEqual(mockApi.calls.map((c) => c.url), ["/api/me", "/api/users/9/orders"]);`),
      ],
    },
    {
      slug: "api-race-condition",
      title: "Ignore Stale Responses",
      difficulty: "HARD",
      tags: ["api", "race-conditions", "cleanup"],
      estimatedMinutes: 25,
      description:
        "Make `UserName` accept `userId`, fetch `GET /api/users/{userId}` (returns `{ name }`), and render `<p>{name}</p>` (or `Loading...`).\n\nCareful: if `userId` changes from 1 to 2 while user 1 is still loading, and user 1's response arrives **last**, a naive implementation shows the wrong user. In the tests, `/api/users/1` is slow and `/api/users/2` is fast.\n\nMake sure only the response for the **current** userId is ever shown.",
      requirements: ["Shows the user for the current id", "Late responses for old ids are ignored"],
      hints: [
        "The effect for userId 1 is cleaned up when userId changes to 2.",
        "Declare `let ignore = false;` in the effect, set `ignore = true` in the cleanup, and only set state if !ignore.",
        "An AbortController that cancels the old request also works.",
      ],
      starterCode: stubFn("UserName", "{ userId }: { userId: number }"),
      solutionCode: `${imports}\n\nfunction UserName({ userId }: { userId: number }) {\n  const [name, setName] = useState<string | null>(null);\n\n  useEffect(() => {\n    let ignore = false;\n    setName(null);\n    fetch(\`/api/users/\${userId}\`)\n      .then((r) => r.json())\n      .then((data: { name: string }) => {\n        if (!ignore) setName(data.name);\n      });\n    return () => {\n      ignore = true;\n    };\n  }, [userId]);\n\n  return <p>{name ?? "Loading..."}</p>;\n}\n\nexport default UserName;\n`,
      explanation: "Responses don't arrive in the order requests were sent. The cleanup marks old effects as stale, so their late responses are dropped instead of overwriting newer data.",
      alternativeApproach: "Create an AbortController in the effect, pass its signal to fetch, and call controller.abort() in the cleanup. This also cancels the network request.",
      mockApi: [
        { url: "/api/users/1", delayMs: 150, response: { name: "Old User" } },
        { url: "/api/users/2", delayMs: 10, response: { name: "New User" } },
      ],
      tests: [
        test("shows the user", `renderComponent({ userId: 2 });\nawait waitFor(() => expectText("New User"));`),
        hidden("ignores the stale response", `const { rerender } = renderComponent({ userId: 1 });\nrerender(<Component userId={2} />);\nawait waitFor(() => expectText("New User"));\nawait sleep(250);\nexpectText("New User");\nexpectNoText("Old User");`),
      ],
      wrongSolutions: [`import { useEffect, useState } from "react";\nfunction UserName({ userId }) {\n  const [name, setName] = useState(null);\n  useEffect(() => { fetch("/api/users/" + userId).then((r) => r.json()).then((d) => setName(d.name)); }, [userId]);\n  return <p>{name ?? "Loading..."}</p>;\n}\nexport default UserName;\n`],
    },
    {
      slug: "api-debounced-search",
      title: "Debounced Search API",
      difficulty: "HARD",
      tags: ["api", "debouncing", "race-conditions", "useEffect"],
      estimatedMinutes: 30,
      description:
        "Make `LiveSearch` accept an optional `delay` (default 300ms) and render an input labelled `Search`. As the user types, search `GET /api/search?q={query}` (URL-encoded), which returns `string[]`, and list the results.\n\n- Only search once the user has **stopped typing for `delay` ms** — typing `react` quickly must send one request, not five.\n- Don't search for an empty query; clear the results instead.\n- Ignore responses for queries that are no longer current.",
      requirements: ["One request per pause in typing", "No request for an empty query", "Stale responses are ignored"],
      hints: [
        "One effect on [query, delay]: schedule the request with setTimeout and clear it in the cleanup.",
        "In the same effect, use an `ignore` flag (also set in the cleanup) to drop late responses.",
        "If query.trim() is empty, clear the results and return early.",
      ],
      starterCode: stubFn("LiveSearch", "{ delay = 300 }: { delay?: number }"),
      solutionCode: `${imports}\n\nfunction LiveSearch({ delay = 300 }: { delay?: number }) {\n  const [query, setQuery] = useState("");\n  const [results, setResults] = useState<string[]>([]);\n\n  useEffect(() => {\n    if (!query.trim()) {\n      setResults([]);\n      return;\n    }\n    let ignore = false;\n    const id = setTimeout(async () => {\n      const res = await fetch(\`/api/search?q=\${encodeURIComponent(query)}\`);\n      const data: string[] = await res.json();\n      if (!ignore) setResults(data);\n    }, delay);\n    return () => {\n      ignore = true;\n      clearTimeout(id);\n    };\n  }, [query, delay]);\n\n  return (\n    <div>\n      <label>\n        Search <input value={query} onChange={(e) => setQuery(e.target.value)} />\n      </label>\n      <ul>\n        {results.map((r) => (\n          <li key={r}>{r}</li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nexport default LiveSearch;\n`,
      explanation: "Debouncing and stale-response protection both fall out of the effect cleanup: each keystroke's cleanup cancels the pending timer and marks any in-flight request as outdated.",
      alternativeApproach: "Combine a useDebounce(query, delay) hook with a separate fetching effect on the debounced value — same behaviour, split into two reusable pieces.",
      mockApi: [
        { url: "/api/search?q=react", response: ["React", "React Router", "React Query"] },
        { url: "/api/search?q=vue", delayMs: 120, response: ["Vue"] },
        { url: "/api/search?q=vu", delayMs: 10, response: ["Vuex"] },
      ],
      tests: [
        test("debounces typing into one request", `renderComponent({ delay: 60 });\nawait userEvent.type(screen.getByLabelText("Search"), "react");\nawait waitFor(() => expectText("React Router"));\nassertEqual(mockApi.calls.map((c) => c.url), ["/api/search?q=react"]);`),
        hidden("no request for empty query", `renderComponent({ delay: 30 });\nawait userEvent.type(screen.getByLabelText("Search"), "   ");\nawait sleep(100);\nassertEqual(mockApi.calls.length, 0);`),
        hidden("ignores a stale response", `renderComponent({ delay: 20 });\nconst input = screen.getByLabelText("Search");\nfireEvent.change(input, { target: { value: "vue" } });\nawait sleep(50);\nfireEvent.change(input, { target: { value: "vu" } });\nawait waitFor(() => expectText("Vuex"));\nawait sleep(200);\nexpectText("Vuex");\nexpectNoText("Vue");`),
      ],
      wrongSolutions: [
        `import { useEffect, useState } from "react";\nfunction LiveSearch({ delay = 300 }) {\n  const [q, setQ] = useState("");\n  const [r, setR] = useState([]);\n  useEffect(() => { if (!q.trim()) return; fetch("/api/search?q=" + encodeURIComponent(q)).then((x) => x.json()).then(setR); }, [q]);\n  return (<div><label>Search <input value={q} onChange={(e) => setQ(e.target.value)} /></label><ul>{r.map((x) => <li key={x}>{x}</li>)}</ul></div>);\n}\nexport default LiveSearch;\n`,
        `import { useEffect, useState } from "react";\nfunction LiveSearch({ delay = 300 }) {\n  const [q, setQ] = useState("");\n  const [r, setR] = useState([]);\n  useEffect(() => { if (!q.trim()) return; const id = setTimeout(() => { fetch("/api/search?q=" + encodeURIComponent(q)).then((x) => x.json()).then(setR); }, delay); return () => clearTimeout(id); }, [q, delay]);\n  return (<div><label>Search <input value={q} onChange={(e) => setQ(e.target.value)} /></label><ul>{r.map((x) => <li key={x}>{x}</li>)}</ul></div>);\n}\nexport default LiveSearch;\n`,
      ],
    },
    {
      slug: "api-saving-state",
      title: "Show a Saving State",
      difficulty: "EASY",
      tags: ["api", "post", "async-ui"],
      estimatedMinutes: 12,
      description:
        "Make `SaveSettings` render a button `Save`. Clicking it sends `POST /api/settings` (no body needed). While waiting, the button is disabled and reads `Saving...`. Afterwards it reads `Save` again and `<p>Saved!</p>` appears.",
      requirements: ["Disabled with 'Saving...' while in flight", "Shows 'Saved!' afterwards"],
      hints: ["A `status` state of \"idle\" | \"saving\" | \"saved\" covers every case.", "Set \"saving\" before awaiting fetch and \"saved\" after."],
      starterCode: stubFn("SaveSettings"),
      solutionCode: `import { useState } from "react";\n\nfunction SaveSettings() {\n  const [status, setStatus] = useState<"idle" | "saving" | "saved">("idle");\n\n  async function save() {\n    setStatus("saving");\n    await fetch("/api/settings", { method: "POST" });\n    setStatus("saved");\n  }\n\n  return (\n    <div>\n      <button disabled={status === "saving"} onClick={save}>\n        {status === "saving" ? "Saving..." : "Save"}\n      </button>\n      {status === "saved" && <p>Saved!</p>}\n    </div>\n  );\n}\n\nexport default SaveSettings;\n`,
      explanation: "One status value instead of several booleans makes impossible combinations (saving and saved at once) impossible to represent.",
      mockApi: [{ method: "POST", url: "/api/settings", delayMs: 40, response: { ok: true } }],
      tests: [
        test("saving then saved", `renderComponent();\n${click("Save")}\nconst btn = screen.getByRole("button", { name: "Saving..." });\nassert(btn.disabled);\nawait waitFor(() => expectText("Saved!"));\nscreen.getByRole("button", { name: "Save" });`),
        hidden("actually posts", `renderComponent();\n${click("Save")}\nawait waitFor(() => expectText("Saved!"));\nassertEqual(mockApi.calls.map((c) => c.method + " " + c.url), ["POST /api/settings"]);`),
      ],
      wrongSolutions: [`import { useState } from "react";\nfunction SaveSettings() {\n  const [saved, setSaved] = useState(false);\n  return (<div><button onClick={() => setSaved(true)}>Save</button>{saved && <p>Saved!</p>}</div>);\n}\nexport default SaveSettings;\n`],
    },
  ],
};
