import { hidden, test, type CategoryBank } from "./types.js";

const click = (name: string) => `fireEvent.click(screen.getByRole("button", { name: ${JSON.stringify(name)} }));`;
const items = `screen.getAllByRole("listitem").map((el) => el.textContent)`;

export const debugging: CategoryBank = {
  category: "Debugging",
  level: 15,
  type: "COMPONENT",
  prerequisites: ["useState", "useEffect", "Lists"],
  problems: [
    {
      slug: "debug-array-mutation",
      title: "Fix: New Guests Don't Appear",
      difficulty: "EASY",
      tags: ["debugging", "useState", "immutability"],
      problemType: "DEBUG",
      estimatedMinutes: 10,
      description: "Clicking `Add Bob` or `Add Cy` should add that guest to the list, but nothing appears. Find and fix the bug.",
      requirements: ["Each button adds its guest to the list"],
      hints: [
        "React decides whether to re-render by comparing the old and new state with Object.is.",
        "push() changes the existing array, so the 'new' state is the same array.",
        "Create a new array instead: setGuests([...guests, name])",
      ],
      starterCode: `import { useState } from "react";\n\nfunction GuestList() {\n  const [guests, setGuests] = useState(["Ana"]);\n\n  function addGuest(name: string) {\n    guests.push(name);\n    setGuests(guests);\n  }\n\n  return (\n    <div>\n      <button onClick={() => addGuest("Bob")}>Add Bob</button>\n      <button onClick={() => addGuest("Cy")}>Add Cy</button>\n      <ul>\n        {guests.map((g) => (\n          <li key={g}>{g}</li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nexport default GuestList;\n`,
      solutionCode: `import { useState } from "react";\n\nfunction GuestList() {\n  const [guests, setGuests] = useState(["Ana"]);\n\n  function addGuest(name: string) {\n    setGuests((prev) => [...prev, name]);\n  }\n\n  return (\n    <div>\n      <button onClick={() => addGuest("Bob")}>Add Bob</button>\n      <button onClick={() => addGuest("Cy")}>Add Cy</button>\n      <ul>\n        {guests.map((g) => (\n          <li key={g}>{g}</li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nexport default GuestList;\n`,
      explanation: "Setting state to the same object reference tells React nothing changed, so it skips the re-render. Immutable updates create a new reference React can detect.",
      tests: [
        test("adds Bob", `renderComponent();\n${click("Add Bob")}\nassertEqual(${items}, ["Ana", "Bob"]);`),
        hidden("adds several guests", `renderComponent();\n${click("Add Cy")}\n${click("Add Bob")}\nassertEqual(${items}, ["Ana", "Cy", "Bob"]);`),
      ],
    },
    {
      slug: "debug-object-mutation",
      title: "Fix: Profile Name Won't Update",
      difficulty: "EASY",
      tags: ["debugging", "useState", "objects"],
      problemType: "DEBUG",
      estimatedMinutes: 10,
      description: "Clicking `Rename` should change the heading from `Ada` to `Ada L.`, but the screen doesn't change. Fix it.",
      requirements: ["Rename updates the heading", "The role stays the same"],
      hints: ["Look at how the user object is updated.", "Spread into a new object: setUser({ ...user, name: \"Ada L.\" })"],
      starterCode: `import { useState } from "react";\n\nfunction ProfileHeader() {\n  const [user, setUser] = useState({ name: "Ada", role: "Engineer" });\n\n  function rename() {\n    user.name = "Ada L.";\n    setUser(user);\n  }\n\n  return (\n    <div>\n      <h2>{user.name}</h2>\n      <p>{user.role}</p>\n      <button onClick={rename}>Rename</button>\n    </div>\n  );\n}\n\nexport default ProfileHeader;\n`,
      solutionCode: `import { useState } from "react";\n\nfunction ProfileHeader() {\n  const [user, setUser] = useState({ name: "Ada", role: "Engineer" });\n\n  function rename() {\n    setUser((u) => ({ ...u, name: "Ada L." }));\n  }\n\n  return (\n    <div>\n      <h2>{user.name}</h2>\n      <p>{user.role}</p>\n      <button onClick={rename}>Rename</button>\n    </div>\n  );\n}\n\nexport default ProfileHeader;\n`,
      explanation: "Same bug as with arrays: mutating then setting the same object is invisible to React.",
      tests: [
        test("renames", `renderComponent();\n${click("Rename")}\nscreen.getByRole("heading", { name: "Ada L." });`),
        hidden("keeps the role", `renderComponent();\n${click("Rename")}\nexpectText("Engineer");`),
      ],
    },
    {
      slug: "debug-stale-interval",
      title: "Fix: Timer Stuck at 1",
      difficulty: "MEDIUM",
      tags: ["debugging", "useEffect", "stale-closure", "timers"],
      problemType: "DEBUG",
      estimatedMinutes: 15,
      description:
        "`Clock` should count up once every `intervalMs`, but it goes to `1` and stays there. Fix the bug without adding `seconds` to the dependency array (that would recreate the interval on every tick).",
      requirements: ["Counts up continuously", "The interval is created once"],
      hints: [
        "The interval callback was created during the first render, when seconds was 0. It 'closes over' that value forever.",
        "So it keeps calling setSeconds(0 + 1).",
        "Use the updater form, which always receives the latest value: setSeconds((s) => s + 1)",
      ],
      starterCode: `import { useEffect, useState } from "react";\n\nfunction Clock({ intervalMs = 1000 }: { intervalMs?: number }) {\n  const [seconds, setSeconds] = useState(0);\n\n  useEffect(() => {\n    const id = setInterval(() => {\n      setSeconds(seconds + 1);\n    }, intervalMs);\n    return () => clearInterval(id);\n  }, []);\n\n  return <p>Elapsed: {seconds}</p>;\n}\n\nexport default Clock;\n`,
      solutionCode: `import { useEffect, useState } from "react";\n\nfunction Clock({ intervalMs = 1000 }: { intervalMs?: number }) {\n  const [seconds, setSeconds] = useState(0);\n\n  useEffect(() => {\n    const id = setInterval(() => {\n      setSeconds((s) => s + 1);\n    }, intervalMs);\n    return () => clearInterval(id);\n  }, [intervalMs]);\n\n  return <p>Elapsed: {seconds}</p>;\n}\n\nexport default Clock;\n`,
      explanation: "Functions capture the variables of the render they were created in. An effect with [] keeps its first-render closure forever, so it sees a stale `seconds`. Updater functions sidestep this by asking React for the current value.",
      commonMistakes: ["Adding seconds to the deps 'works' but tears down and recreates the interval every second."],
      tests: [
        test("keeps counting", `renderComponent({ intervalMs: 20 });\nawait sleep(150);\nconst n = Number(screen.getByText(/Elapsed:/).textContent.replace("Elapsed: ", ""));\nassert(n >= 4, "Expected the clock to keep counting, got " + n);`),
        hidden("still counting later", `renderComponent({ intervalMs: 25 });\nawait waitFor(() => expectText("Elapsed: 3"), { timeout: 1000 });\nawait waitFor(() => expectText("Elapsed: 5"), { timeout: 1000 });`),
      ],
    },
    {
      slug: "debug-handler-called-in-render",
      title: "Fix: Too Many Re-renders",
      difficulty: "EASY",
      tags: ["debugging", "events"],
      problemType: "DEBUG",
      estimatedMinutes: 8,
      description: "This component crashes immediately with **\"Too many re-renders\"**. It should show a `Show details` button that reveals `<p>Details here</p>` when clicked. Fix it.",
      requirements: ["Renders without crashing", "Details appear only after clicking"],
      hints: ["Look closely at what's passed to onClick.", "onClick={setOpen(true)} calls setOpen during render, which re-renders, which calls it again...", "Pass a function: onClick={() => setOpen(true)}"],
      starterCode: `import { useState } from "react";\n\nfunction Details() {\n  const [open, setOpen] = useState(false);\n\n  return (\n    <div>\n      <button onClick={setOpen(true)}>Show details</button>\n      {open && <p>Details here</p>}\n    </div>\n  );\n}\n\nexport default Details;\n`,
      solutionCode: `import { useState } from "react";\n\nfunction Details() {\n  const [open, setOpen] = useState(false);\n\n  return (\n    <div>\n      <button onClick={() => setOpen(true)}>Show details</button>\n      {open && <p>Details here</p>}\n    </div>\n  );\n}\n\nexport default Details;\n`,
      explanation: "onClick needs a function to call later. `setOpen(true)` is a call that happens right now, during render — and setting state during render triggers another render, forever.",
      tests: [
        test("renders the button", `renderComponent();\nscreen.getByRole("button", { name: "Show details" });`),
        hidden("details only after click", `renderComponent();\nexpectNoText("Details here");\n${click("Show details")}\nexpectText("Details here");`),
      ],
    },
    {
      slug: "debug-readonly-input",
      title: "Fix: Can't Type Into the Input",
      difficulty: "BEGINNER",
      tags: ["debugging", "forms", "controlled-components"],
      problemType: "DEBUG",
      estimatedMinutes: 5,
      description: "Typing into the `Name` input does nothing, and React logs a warning about a `value` prop without an `onChange` handler. Fix it so the greeting updates as you type.",
      requirements: ["Typing updates the input and greeting", "No read-only warning"],
      hints: ["A controlled input needs both value and onChange.", "onChange={(e) => setName(e.target.value)}"],
      starterCode: `import { useState } from "react";\n\nfunction Greeter() {\n  const [name, setName] = useState("");\n\n  return (\n    <div>\n      <label>\n        Name <input value={name} />\n      </label>\n      <p>Hi, {name}</p>\n    </div>\n  );\n}\n\nexport default Greeter;\n`,
      solutionCode: `import { useState } from "react";\n\nfunction Greeter() {\n  const [name, setName] = useState("");\n\n  return (\n    <div>\n      <label>\n        Name <input value={name} onChange={(e) => setName(e.target.value)} />\n      </label>\n      <p>Hi, {name}</p>\n    </div>\n  );\n}\n\nexport default Greeter;\n`,
      explanation: "With value set, React forces the input to always show that value. Without onChange, nothing ever updates it, so keystrokes are discarded.",
      tests: [
        test("typing updates the greeting", `renderComponent();\nawait userEvent.type(screen.getByLabelText("Name"), "Lee");\nexpectText("Hi, Lee");`),
        hidden("no read-only warning", `renderComponent();\nassert(!anyConsoleError("without an \`onChange\` handler"), "React warned the input is read-only");`),
      ],
    },
    {
      slug: "debug-zero-renders",
      title: "Fix: A Stray 0 on the Screen",
      difficulty: "BEGINNER",
      tags: ["debugging", "conditional-rendering"],
      problemType: "DEBUG",
      estimatedMinutes: 5,
      description: "When there are no messages, this component shows a lone `0`. It should show nothing at all in that case. Fix it.",
      requirements: ["No output for an empty list", "List still shows when there are messages"],
      hints: ["What does `0 && <ul/>` evaluate to?", "Make the condition a boolean: messages.length > 0 && ..."],
      starterCode: `function Messages({ messages }: { messages: string[] }) {\n  return (\n    <div>\n      {messages.length && (\n        <ul>\n          {messages.map((m) => (\n            <li key={m}>{m}</li>\n          ))}\n        </ul>\n      )}\n    </div>\n  );\n}\n\nexport default Messages;\n`,
      solutionCode: `function Messages({ messages }: { messages: string[] }) {\n  return (\n    <div>\n      {messages.length > 0 && (\n        <ul>\n          {messages.map((m) => (\n            <li key={m}>{m}</li>\n          ))}\n        </ul>\n      )}\n    </div>\n  );\n}\n\nexport default Messages;\n`,
      explanation: "`&&` returns its left operand when it's falsy. 0 is falsy, but React renders numbers, so 0 appears on screen.",
      tests: [
        test("shows messages", `renderComponent({ messages: ["hi", "yo"] });\nassertEqual(${items}, ["hi", "yo"]);`),
        hidden("nothing for an empty list", `const { container } = renderComponent({ messages: [] });\nassertEqual(container.textContent, "", "Expected no output, got '" + container.textContent + "'");`),
      ],
    },
    {
      slug: "debug-missing-dependency",
      title: "Fix: Wrong User After Switching",
      difficulty: "MEDIUM",
      tags: ["debugging", "useEffect", "dependencies", "api"],
      problemType: "DEBUG",
      type: "API",
      estimatedMinutes: 12,
      description: "`UserCard` shows the right user at first, but when the parent switches `userId` from 1 to 2, it keeps showing user 1. Fix the bug.",
      requirements: ["Refetches when userId changes"],
      hints: ["When does this effect run?", "The effect reads userId, so userId must be in its dependency array."],
      starterCode: `import { useEffect, useState } from "react";\n\nfunction UserCard({ userId }: { userId: number }) {\n  const [name, setName] = useState("");\n\n  useEffect(() => {\n    fetch(\`/api/users/\${userId}\`)\n      .then((r) => r.json())\n      .then((user) => setName(user.name));\n  }, []);\n\n  return <h2>{name || "Loading..."}</h2>;\n}\n\nexport default UserCard;\n`,
      solutionCode: `import { useEffect, useState } from "react";\n\nfunction UserCard({ userId }: { userId: number }) {\n  const [name, setName] = useState("");\n\n  useEffect(() => {\n    let ignore = false;\n    fetch(\`/api/users/\${userId}\`)\n      .then((r) => r.json())\n      .then((user) => {\n        if (!ignore) setName(user.name);\n      });\n    return () => {\n      ignore = true;\n    };\n  }, [userId]);\n\n  return <h2>{name || "Loading..."}</h2>;\n}\n\nexport default UserCard;\n`,
      explanation: "An empty dependency array promises React the effect uses no props or state. It does use userId, so the promise is false and the effect never re-runs. The lint rule react-hooks/exhaustive-deps catches this.",
      mockApi: [
        { url: "/api/users/1", response: { name: "Alice" } },
        { url: "/api/users/2", response: { name: "Bob" } },
      ],
      tests: [
        test("loads the first user", `renderComponent({ userId: 1 });\nawait waitFor(() => screen.getByRole("heading", { name: "Alice" }));`),
        hidden("switches users", `const { rerender } = renderComponent({ userId: 1 });\nawait waitFor(() => screen.getByRole("heading", { name: "Alice" }));\nrerender(<Component userId={2} />);\nawait waitFor(() => screen.getByRole("heading", { name: "Bob" }), { timeout: 500 });`),
      ],
    },
    {
      slug: "debug-missing-cleanup",
      title: "Fix: Listener Leak After Unmount",
      difficulty: "MEDIUM",
      tags: ["debugging", "useEffect", "cleanup"],
      problemType: "DEBUG",
      estimatedMinutes: 10,
      description:
        "`ResizeReporter` calls `onResize` whenever the window resizes. After it unmounts, `onResize` keeps firing — and every remount adds another listener. Fix the leak.",
      requirements: ["Reports resizes while mounted", "No calls after unmount"],
      hints: ["What undoes addEventListener?", "Return a cleanup function from the effect that removes the same handler."],
      starterCode: `import { useEffect } from "react";\n\nfunction ResizeReporter({ onResize }: { onResize: () => void }) {\n  useEffect(() => {\n    window.addEventListener("resize", onResize);\n  }, [onResize]);\n\n  return <p>Watching window size</p>;\n}\n\nexport default ResizeReporter;\n`,
      solutionCode: `import { useEffect } from "react";\n\nfunction ResizeReporter({ onResize }: { onResize: () => void }) {\n  useEffect(() => {\n    window.addEventListener("resize", onResize);\n    return () => window.removeEventListener("resize", onResize);\n  }, [onResize]);\n\n  return <p>Watching window size</p>;\n}\n\nexport default ResizeReporter;\n`,
      explanation: "Every subscription made in an effect must be undone in its cleanup, or it outlives the component.",
      tests: [
        test("reports resizes", `const onResize = mockFn();\nrenderComponent({ onResize });\nact(() => { window.dispatchEvent(new window.Event("resize")); });\nassertEqual(onResize.calls.length, 1);`),
        hidden("stops after unmount", `const onResize = mockFn();\nconst { unmount } = renderComponent({ onResize });\nunmount();\nwindow.dispatchEvent(new window.Event("resize"));\nassertEqual(onResize.calls.length, 0, "onResize fired after unmount");`),
      ],
    },
    {
      slug: "debug-duplicate-keys",
      title: "Fix: Duplicate Keys",
      difficulty: "EASY",
      tags: ["debugging", "lists", "keys"],
      problemType: "DEBUG",
      estimatedMinutes: 8,
      description: "`Attendees` logs a React warning: *Encountered two children with the same key*. Two attendees share a name. Fix the keys.",
      requirements: ["Every attendee is shown", "No duplicate-key warning"],
      hints: ["Names aren't unique. What is?", "key={person.id}"],
      starterCode: `interface Person {\n  id: number;\n  name: string;\n}\n\nfunction Attendees({ people }: { people: Person[] }) {\n  return (\n    <ul>\n      {people.map((person) => (\n        <li key={person.name}>{person.name}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default Attendees;\n`,
      solutionCode: `interface Person {\n  id: number;\n  name: string;\n}\n\nfunction Attendees({ people }: { people: Person[] }) {\n  return (\n    <ul>\n      {people.map((person) => (\n        <li key={person.id}>{person.name}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default Attendees;\n`,
      explanation: "Keys must be unique among siblings. Duplicate keys confuse React's reconciliation and can drop or duplicate items when the list changes.",
      tests: [
        test("shows everyone", `renderComponent({ people: [{ id: 1, name: "Sam" }, { id: 2, name: "Sam" }, { id: 3, name: "Jo" }] });\nassertEqual(${items}, ["Sam", "Sam", "Jo"]);`),
        hidden("no duplicate-key warning", `renderComponent({ people: [{ id: 1, name: "Sam" }, { id: 2, name: "Sam" }] });\nassert(!anyConsoleError("same key"), "React warned about duplicate keys");`),
      ],
    },
    {
      slug: "debug-index-key-inputs",
      title: "Fix: Notes Jump to the Wrong Row",
      difficulty: "HARD",
      tags: ["debugging", "lists", "keys", "state-preservation"],
      problemType: "DEBUG",
      estimatedMinutes: 20,
      description:
        "Each row has a note input. Type a note for Ana and one for Ben, then remove Ana — Ben's row now shows **Ana's** note. Find the cause and fix it.",
      requirements: ["Notes stay with their person after a removal"],
      hints: [
        "React matches list items between renders by key.",
        "With key={index}, after removing the first row, Ben is now index 0 — so React reuses the DOM input that belonged to index 0 (Ana's).",
        "Use a stable identity: key={person.id}",
      ],
      starterCode: `import { useState } from "react";\n\nconst INITIAL = [\n  { id: 1, name: "Ana" },\n  { id: 2, name: "Ben" },\n  { id: 3, name: "Cy" },\n];\n\nfunction NotesList() {\n  const [people, setPeople] = useState(INITIAL);\n\n  return (\n    <ul>\n      {people.map((person, index) => (\n        <li key={index}>\n          <label>\n            {person.name} <input aria-label={\`Note for \${person.name}\`} />\n          </label>\n          <button onClick={() => setPeople((prev) => prev.filter((p) => p.id !== person.id))}>Remove {person.name}</button>\n        </li>\n      ))}\n    </ul>\n  );\n}\n\nexport default NotesList;\n`,
      solutionCode: `import { useState } from "react";\n\nconst INITIAL = [\n  { id: 1, name: "Ana" },\n  { id: 2, name: "Ben" },\n  { id: 3, name: "Cy" },\n];\n\nfunction NotesList() {\n  const [people, setPeople] = useState(INITIAL);\n\n  return (\n    <ul>\n      {people.map((person) => (\n        <li key={person.id}>\n          <label>\n            {person.name} <input aria-label={\`Note for \${person.name}\`} />\n          </label>\n          <button onClick={() => setPeople((prev) => prev.filter((p) => p.id !== person.id))}>Remove {person.name}</button>\n        </li>\n      ))}\n    </ul>\n  );\n}\n\nexport default NotesList;\n`,
      explanation: "Index keys are only safe when the list never reorders, inserts, or removes. Here, removal shifts indexes, so React pairs the wrong DOM nodes (and their typed text) with the wrong people. React doesn't warn about this — it's a silent bug.",
      tests: [
        test("removes a row", `renderComponent();\n${click("Remove Cy")}\nassertEqual(screen.getAllByRole("listitem").length, 2);`),
        hidden("notes stay with their person", `renderComponent();\nawait userEvent.type(screen.getByLabelText("Note for Ana"), "ana-note");\nawait userEvent.type(screen.getByLabelText("Note for Ben"), "ben-note");\n${click("Remove Ana")}\nassertEqual(screen.getByLabelText("Note for Ben").value, "ben-note", "Ben's note moved to the wrong row");`),
      ],
    },
    {
      slug: "debug-uncontrolled-to-controlled",
      title: "Fix: Uncontrolled to Controlled Warning",
      difficulty: "EASY",
      tags: ["debugging", "forms", "controlled-components"],
      problemType: "DEBUG",
      estimatedMinutes: 8,
      description:
        "Typing into `Email` works, but React warns: *A component is changing an uncontrolled input to be controlled*. Fix the cause of the warning.",
      requirements: ["Input works as before", "No uncontrolled-to-controlled warning"],
      hints: ["What is the initial value of `email`?", "useState() starts as undefined, and value={undefined} means 'uncontrolled'. Start with an empty string."],
      starterCode: `import { useState } from "react";\n\nfunction EmailInput() {\n  const [email, setEmail] = useState<string>();\n\n  return (\n    <div>\n      <label>\n        Email <input value={email} onChange={(e) => setEmail(e.target.value)} />\n      </label>\n      <p>{email ? \`Sending to \${email}\` : "No email yet"}</p>\n    </div>\n  );\n}\n\nexport default EmailInput;\n`,
      solutionCode: `import { useState } from "react";\n\nfunction EmailInput() {\n  const [email, setEmail] = useState("");\n\n  return (\n    <div>\n      <label>\n        Email <input value={email} onChange={(e) => setEmail(e.target.value)} />\n      </label>\n      <p>{email ? \`Sending to \${email}\` : "No email yet"}</p>\n    </div>\n  );\n}\n\nexport default EmailInput;\n`,
      explanation: "React decides once whether an input is controlled: value={undefined} means uncontrolled. Switching to a string later changes its mode mid-life, which React warns about.",
      tests: [
        test("works", `renderComponent();\nawait userEvent.type(screen.getByLabelText("Email"), "a@b.co");\nexpectText("Sending to a@b.co");`),
        hidden("no mode-switch warning", `renderComponent();\nawait userEvent.type(screen.getByLabelText("Email"), "x");\nassert(!anyConsoleError("uncontrolled input to be controlled"), "React warned about switching from uncontrolled to controlled");`),
      ],
    },
    {
      slug: "debug-wrong-prop-name",
      title: "Fix: Clicking a Color Does Nothing",
      difficulty: "BEGINNER",
      tags: ["debugging", "props", "callbacks"],
      problemType: "DEBUG",
      estimatedMinutes: 8,
      description: "Clicking a color swatch should update `Selected: ...`, but nothing happens. The child and the parent disagree about something. Fix it.",
      requirements: ["Clicking a swatch shows it as selected"],
      hints: ["Compare the prop name the parent passes with the one the child reads.", "Swatch calls onSelect, but the parent passes onClick."],
      starterCode: `import { useState } from "react";\n\nfunction Swatch({ color, onSelect }: { color: string; onSelect?: (color: string) => void }) {\n  return <button onClick={() => onSelect?.(color)}>Choose {color}</button>;\n}\n\nfunction Palette() {\n  const [selected, setSelected] = useState("none");\n\n  return (\n    <div>\n      {["red", "blue"].map((color) => (\n        <Swatch key={color} color={color} onClick={setSelected} />\n      ))}\n      <p>Selected: {selected}</p>\n    </div>\n  );\n}\n\nexport default Palette;\n`,
      solutionCode: `import { useState } from "react";\n\nfunction Swatch({ color, onSelect }: { color: string; onSelect?: (color: string) => void }) {\n  return <button onClick={() => onSelect?.(color)}>Choose {color}</button>;\n}\n\nfunction Palette() {\n  const [selected, setSelected] = useState("none");\n\n  return (\n    <div>\n      {["red", "blue"].map((color) => (\n        <Swatch key={color} color={color} onSelect={setSelected} />\n      ))}\n      <p>Selected: {selected}</p>\n    </div>\n  );\n}\n\nexport default Palette;\n`,
      explanation: "Misnamed props fail silently in plain JavaScript; Swatch just receives undefined. TypeScript would flag `onClick` as not existing on Swatch's props — one of the best reasons to type your props.",
      tests: [
        test("selects blue", `renderComponent();\n${click("Choose blue")}\nexpectText("Selected: blue");`),
        hidden("selects red", `renderComponent();\n${click("Choose red")}\nexpectText("Selected: red");`),
      ],
    },
    {
      slug: "debug-component-inside-component",
      title: "Fix: Input Loses Focus After Every Keystroke",
      difficulty: "HARD",
      tags: ["debugging", "components", "state-preservation"],
      problemType: "DEBUG",
      estimatedMinutes: 15,
      description:
        "In `SignupForm`, you can only type one character into `Name` before the input loses focus. The preview below it should show everything typed. Find out why and fix it.",
      requirements: ["Typing a whole word works", "Preview updates"],
      hints: [
        "Where is NameField defined?",
        "A component defined inside another component is a brand-new function on every render — so React sees a different component type and remounts it (a fresh input, without focus).",
        "Move NameField outside SignupForm and pass value/onChange as props.",
      ],
      starterCode: `import { useState } from "react";\n\nfunction SignupForm() {\n  const [name, setName] = useState("");\n\n  function NameField() {\n    return (\n      <label>\n        Name <input value={name} onChange={(e) => setName(e.target.value)} />\n      </label>\n    );\n  }\n\n  return (\n    <div>\n      <NameField />\n      <p>Preview: {name}</p>\n    </div>\n  );\n}\n\nexport default SignupForm;\n`,
      solutionCode: `import { useState } from "react";\n\nfunction NameField({ value, onChange }: { value: string; onChange: (value: string) => void }) {\n  return (\n    <label>\n      Name <input value={value} onChange={(e) => onChange(e.target.value)} />\n    </label>\n  );\n}\n\nfunction SignupForm() {\n  const [name, setName] = useState("");\n\n  return (\n    <div>\n      <NameField value={name} onChange={setName} />\n      <p>Preview: {name}</p>\n    </div>\n  );\n}\n\nexport default SignupForm;\n`,
      explanation: "React identifies components by function reference. Defining one inside another creates a new function each render, so React unmounts the old subtree and mounts a new one — losing focus and any internal state. Always define components at the top level.",
      tests: [
        test("typing a word works", `renderComponent();\nawait userEvent.type(screen.getByLabelText("Name"), "Grace");\nexpectText("Preview: Grace");`),
        hidden("keeps focus while typing", `renderComponent();\nawait userEvent.type(screen.getByLabelText("Name"), "ab");\nassertEqual(document.activeElement, screen.getByLabelText("Name"), "The input lost focus");`),
      ],
    },
    {
      slug: "debug-spinner-never-stops",
      title: "Fix: Spinner That Never Stops",
      difficulty: "MEDIUM",
      tags: ["debugging", "api", "error-handling"],
      problemType: "DEBUG",
      type: "API",
      estimatedMinutes: 12,
      description:
        "`Orders` loads `GET /api/orders`. When the request fails (HTTP 500), it should show `<p role=\"alert\">Failed to load orders</p>`, but instead it shows `Loading...` forever. Fix it so both success and failure end the loading state.",
      requirements: ["Shows an error on failure", "Loading always ends", "Success still works"],
      hints: [
        "A 500 response doesn't make fetch reject — so .then runs with a failed response.",
        "Check res.ok and handle the failure; make sure loading is turned off in every path (finally).",
      ],
      starterCode: `import { useEffect, useState } from "react";\n\ninterface Order {\n  id: number;\n  item: string;\n}\n\nfunction Orders() {\n  const [orders, setOrders] = useState<Order[]>([]);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState(false);\n\n  useEffect(() => {\n    fetch("/api/orders")\n      .then((res) => res.json())\n      .then((data) => {\n        if (Array.isArray(data)) {\n          setOrders(data);\n          setLoading(false);\n        }\n      })\n      .catch(() => setError(true));\n  }, []);\n\n  if (loading) return <p>Loading...</p>;\n  if (error) return <p role="alert">Failed to load orders</p>;\n  return (\n    <ul>\n      {orders.map((o) => (\n        <li key={o.id}>{o.item}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default Orders;\n`,
      solutionCode: `import { useEffect, useState } from "react";\n\ninterface Order {\n  id: number;\n  item: string;\n}\n\nfunction Orders() {\n  const [orders, setOrders] = useState<Order[]>([]);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState(false);\n\n  useEffect(() => {\n    fetch("/api/orders")\n      .then((res) => {\n        if (!res.ok) throw new Error(\`HTTP \${res.status}\`);\n        return res.json();\n      })\n      .then((data: Order[]) => setOrders(data))\n      .catch(() => setError(true))\n      .finally(() => setLoading(false));\n  }, []);\n\n  if (loading) return <p>Loading...</p>;\n  if (error) return <p role="alert">Failed to load orders</p>;\n  return (\n    <ul>\n      {orders.map((o) => (\n        <li key={o.id}>{o.item}</li>\n      ))}\n    </ul>\n  );\n}\n\nexport default Orders;\n`,
      explanation: "Two bugs combine: HTTP errors never reach catch (no res.ok check), and loading is only cleared on the happy path. `finally` is the right place for 'always do this when the request ends'.",
      mockApi: [{ url: "/api/orders", status: 500, response: { error: "boom" } }],
      tests: [
        test("shows the error", `renderComponent();\nawait waitFor(() => screen.getByRole("alert"), { timeout: 500 });\nexpectNoText("Loading...");`),
        hidden("success still works", `mockApi.setRoutes([{ url: "/api/orders", response: [{ id: 1, item: "Kettle" }] }]);\nrenderComponent();\nawait waitFor(() => expectText("Kettle"));\nassert(!screen.queryByRole("alert"));`),
      ],
    },
  ],
};
